/**
 * Icon pack: relation — auto-generated by scripts/convert-icons.ts
 */
import { registerIcon } from '../../iconRegistry';

import { RelationCheckboxIcon } from './relationCheckbox';
import { RelationDescriptionIcon } from './relationDescription';
import { RelationEmailIcon } from './relationEmail';
import { RelationFileIcon } from './relationFile';
import { RelationLongTextIcon } from './relationLongText';
import { RelationMultiSelectIcon } from './relationMultiSelect';
import { RelationNumberIcon } from './relationNumber';
import { RelationObjectIcon } from './relationObject';
import { RelationPhoneIcon } from './relationPhone';
import { RelationRelationsIcon } from './relationRelations';
import { RelationSelectIcon } from './relationSelect';
import { RelationShortTextIcon } from './relationShortText';
import { RelationTagIcon } from './relationTag';
import { RelationUrlIcon } from './relationUrl';

registerIcon('relationCheckbox', RelationCheckboxIcon);
registerIcon('relationDescription', RelationDescriptionIcon);
registerIcon('relationEmail', RelationEmailIcon);
registerIcon('relationFile', RelationFileIcon);
registerIcon('relationLongText', RelationLongTextIcon);
registerIcon('relationMultiSelect', RelationMultiSelectIcon);
registerIcon('relationNumber', RelationNumberIcon);
registerIcon('relationObject', RelationObjectIcon);
registerIcon('relationPhone', RelationPhoneIcon);
registerIcon('relationRelations', RelationRelationsIcon);
registerIcon('relationSelect', RelationSelectIcon);
registerIcon('relationShortText', RelationShortTextIcon);
registerIcon('relationTag', RelationTagIcon);
registerIcon('relationUrl', RelationUrlIcon);
