import { registerIcon } from '../../registry';
import Add from './add';
import Browse from './browse';
import Clear from './clear';
import Clipboard from './clipboard';
import Collection from './collection';
import Comment from './comment';
import Copy from './copy';
import CopyLink from './copyLink';
import Cut from './cut';
import CreateObject from './createObject';
import CreateWidget from './createWidget';
import Customize from './customize';
import Download from './download';
import Duplicate from './duplicate';
import Email from './email';
import Embed from './embed';
import Existing from './existing';
import Export from './export';
import Fav from './fav';
import Folder from './folder';
import FolderBlank from './folderBlank';
import Group from './group';
import Highlight from './highlight';
import History from './history';
import Import from './import';
import InviteMembers from './inviteMembers';
import Leave from './leave';
import Members from './members';
import Move from './move';
import Mute from './mute';
import Navigation from './navigation';
import NewTab from './newTab';
import NewWindow from './newWindow';
import Notification from './notification';
import Object from './object';
import PageLink from './pageLink';
import PageLock from './pageLock';
import PageUnlock from './pageUnlock';
import Phone from './phone';
import Paste from './paste';
import Pin from './pin';
import Print from './print';
import Quote from './quote';
import Redo from './redo';
import Relation from './relation';
import Reload from './reload';
import Remove from './remove';
import Rename from './rename';
import Replace from './replace';
import Reset from './reset';
import Resize from './resize';
import Restore from './restore';
import Search from './search';
import Set from './set';
import Settings from './settings';
import Share from './share';
import Sidebar from './sidebar';
import Source from './source';
import Store from './store';
import Template from './template';
import Turn from './turn';
import Undo from './undo';
import Unfav from './unfav';
import Unmute from './unmute';
import Unpin from './unpin';
import Upload from './upload';
import UploadComputer from './uploadComputer';
import Wrap from './wrap';

registerIcon('menu/action/add', Add);
registerIcon('menu/action/browse', Browse);
registerIcon('menu/action/clear', Clear);
registerIcon('menu/action/clipboard', Clipboard);
registerIcon('menu/action/collection', Collection);
registerIcon('menu/action/comment', Comment);
registerIcon('menu/action/copy', Copy);
registerIcon('menu/action/copyLink', CopyLink);
registerIcon('menu/action/cut', Cut);
registerIcon('menu/action/createObject', CreateObject);
registerIcon('menu/action/createWidget', CreateWidget);
registerIcon('menu/action/customize', Customize);
registerIcon('menu/action/download', Download);
registerIcon('menu/action/duplicate', Duplicate);
registerIcon('menu/action/email', Email);
registerIcon('menu/action/embed', Embed);
registerIcon('menu/action/existing', Existing);
registerIcon('menu/action/export', Export);
registerIcon('menu/action/fav', Fav);
registerIcon('menu/action/folder', Folder);
registerIcon('menu/action/folderBlank', FolderBlank);
registerIcon('menu/action/group', Group);
registerIcon('menu/action/highlight', Highlight);
registerIcon('menu/action/history', History);
registerIcon('menu/action/import', Import);
registerIcon('menu/action/inviteMembers', InviteMembers);
registerIcon('menu/action/leave', Leave);
registerIcon('menu/action/members', Members);
registerIcon('menu/action/move', Move);
registerIcon('menu/action/mute', Mute);
registerIcon('menu/action/navigation', Navigation);
registerIcon('menu/action/newTab', NewTab);
registerIcon('menu/action/newWindow', NewWindow);
registerIcon('menu/action/notification', Notification);
registerIcon('menu/action/object', Object);
registerIcon('menu/action/pageLink', PageLink);
registerIcon('menu/action/pageLock', PageLock);
registerIcon('menu/action/pageUnlock', PageUnlock);
registerIcon('menu/action/phone', Phone);
registerIcon('menu/action/paste', Paste);
registerIcon('menu/action/pin', Pin);
registerIcon('menu/action/print', Print);
registerIcon('menu/action/quote', Quote);
registerIcon('menu/action/redo', Redo);
registerIcon('menu/action/relation', Relation);
registerIcon('menu/action/reload', Reload);
registerIcon('menu/action/remove', Remove);
registerIcon('menu/action/rename', Rename);
registerIcon('menu/action/replace', Replace);
registerIcon('menu/action/reset', Reset);
registerIcon('menu/action/resize', Resize);
registerIcon('menu/action/restore', Restore);
registerIcon('menu/action/search', Search);
registerIcon('menu/action/set', Set);
registerIcon('menu/action/settings', Settings);
registerIcon('menu/action/share', Share);
registerIcon('menu/action/sidebar', Sidebar);
registerIcon('menu/action/source', Source);
registerIcon('menu/action/store', Store);
registerIcon('menu/action/template', Template);
registerIcon('menu/action/turn', Turn);
registerIcon('menu/action/undo', Undo);
registerIcon('menu/action/unfav', Unfav);
registerIcon('menu/action/unmute', Unmute);
registerIcon('menu/action/unpin', Unpin);
registerIcon('menu/action/upload', Upload);
registerIcon('menu/action/uploadComputer', UploadComputer);
registerIcon('menu/action/wrap', Wrap);
