import { registerIcon } from '../../../registry';
import AppleMusic from './appleMusic';
import Bandcamp from './bandcamp';
import Bilibili from './bilibili';
import Chart from './chart';
import Codepen from './codepen';
import Drawio from './drawio';
import Excalidraw from './excalidraw';
import Facebook from './facebook';
import Figma from './figma';
import GithubGist from './githubGist';
import GoogleMaps from './googleMaps';
import Graphviz from './graphviz';
import Image from './image';
import Instagram from './instagram';
import Kroki from './kroki';
import Latex from './latex';
import Mermaid from './mermaid';
import Miro from './miro';
import OpenStreetMap from './openStreetMap';
import Reddit from './reddit';
import Sketchfab from './sketchfab';
import Soundcloud from './soundcloud';
import Spotify from './spotify';
import Telegram from './telegram';
import Twitter from './twitter';
import Vimeo from './vimeo';
import Youtube from './youtube';

registerIcon('menu/block/embed/appleMusic', AppleMusic);
registerIcon('menu/block/embed/bandcamp', Bandcamp);
registerIcon('menu/block/embed/bilibili', Bilibili);
registerIcon('menu/block/embed/chart', Chart);
registerIcon('menu/block/embed/codepen', Codepen);
registerIcon('menu/block/embed/drawio', Drawio);
registerIcon('menu/block/embed/excalidraw', Excalidraw);
registerIcon('menu/block/embed/facebook', Facebook);
registerIcon('menu/block/embed/figma', Figma);
registerIcon('menu/block/embed/githubGist', GithubGist);
registerIcon('menu/block/embed/googleMaps', GoogleMaps);
registerIcon('menu/block/embed/graphviz', Graphviz);
registerIcon('menu/block/embed/image', Image);
registerIcon('menu/block/embed/instagram', Instagram);
registerIcon('menu/block/embed/kroki', Kroki);
registerIcon('menu/block/embed/latex', Latex);
registerIcon('menu/block/embed/mermaid', Mermaid);
registerIcon('menu/block/embed/miro', Miro);
registerIcon('menu/block/embed/openStreetMap', OpenStreetMap);
registerIcon('menu/block/embed/reddit', Reddit);
registerIcon('menu/block/embed/sketchfab', Sketchfab);
registerIcon('menu/block/embed/soundcloud', Soundcloud);
registerIcon('menu/block/embed/spotify', Spotify);
registerIcon('menu/block/embed/telegram', Telegram);
registerIcon('menu/block/embed/twitter', Twitter);
registerIcon('menu/block/embed/vimeo', Vimeo);
registerIcon('menu/block/embed/youtube', Youtube);
