export default {
	Code: {
		ANYTYPE_NEEDS_UPGRADE:				 	10,
		NO_ACCOUNTS_FOUND:					 	101,
		FAILED_TO_FIND_ACCOUNT_INFO:		 	104,
		ANOTHER_ANYTYPE_PROCESS_IS_RUNNING:	 	108,
		ACCOUNT_IS_DELETED:					 	109,
		PROTOCOL_NEEDS_UPGRADE:				 	110,
		NOT_FOUND:							 	3,
		OBJECT_DELETED:						 	4,
		NO_OBJECTS_TO_IMPORT:				 	5,
		IMPORT_IS_CANCELED:					 	6,
		LIMIT_OF_ROWS_OR_RELATIONS_EXCEEDED: 	7,
		FILE_LOAD_ERROR:						8,
		INSUFFICIENT_PERMISSIONS:				9,
		ACCOUNT_STORE_NOT_MIGRATED:				113,

		Import: {
			INTERNAL_ERROR:								3,
			NOTION_NO_OBJECTS_IN_INTEGRATION:			5,
			IMPORT_IS_CANCELED:							6,
			CSV_LIMIT_OF_ROWS_OR_RELATIONS_EXCEEDED:	7,
			FILE_LOAD_ERROR:							8,
			INSUFFICIENT_PERMISSIONS:					9,
			HTML_WRONG_HTML_STRUCTURE:					10,
			PB_NOT_ANYBLOCK_FORMAT:						11,
			NOTION_SERVER_IS_UNAVAILABLE:				12,
			NOTION_RATE_LIMIT_EXCEEDED:					13,
			FILE_IMPORT_NO_OBJECTS_IN_ZIP_ARCHIVE:		14,
			FILE_IMPORT_NO_OBJECTS_IN_DIRECTORY:		17,
		},

		Publish: {
			PAGE_SIZE_EXCEEDED: 	103
		},

		SpaceInviteView: {
			INVITE_NOT_FOUND: 		101,
			SPACE_IS_DELETED:		103,
		},
	},

	'Error: net::ERR_TIMED_OUT': 'Network time-out',
	'Error: net::ERR_CONNECTION_CLOSED': 'Connection closed',
};
