export default {

	enabled: [
		'be-BY',
		'cs-CZ',
		'da-DK',
		'de-DE',
		'en-US',
		'es-ES',
		'fa-IR',
		'fr-FR',
		'hi-IN',
		'id-ID',
		'it-IT',
		'lt-LT',
		'ja-JP',
		'ko-KR',
		'nl-NL',
		'no-NO',
		'pl-PL',
		'pt-BR',
		'ro-RO',
		'ru-RU',
		'tr-TR',
		'uk-UA',
		'vi-VN',
		'zh-CN',
		'zh-TW'
	],

	spelling: {
		af: 'Afrikaans',
		bg: 'Български',
		ca: 'Català',
		cs: 'Česky',
		cy: 'Cymraeg',
		da: 'Dansk',
		de: 'Deutsch',
		'de-DE': 'Deutsch (Deutschland)',
		el: 'Ελληνικά',
		en: 'English',
		'en-AU': 'English (Australia)',
		'en-CA': 'English (Canada)',
		'en-GB': 'English (United Kingdom)',
		'en-GB-oxendict': 'English (United Kingdom Oxford spelling)',
		'en-US': 'English (United States)',
		es: 'Español',
		'es-419': 'Español (Caribe)',
		'es-AR': 'Español (Argentina)',
		'es-ES': 'Español (España)',
		'es-MX': 'Español (México)',
		'es-US': 'Español (Estados Unidos)',
		et: 'Eesti',
		fa: 'فارسی',
		fo: 'Føroyskt',
		fr: 'Français',
		'fr-FR': 'Français (France)',
		he: 'עברית',
		hi: 'हिन्दी',
		hr: 'Hrvatski',
		hu: 'Magyar',
		hy: 'Հայերեն',
		id: 'Bahasa Indonesia',
		it: 'Italiano',
		'it-IT': 'Italiano (Italia)',
		ko: '한국어',
		lt: 'Lietuvių',
		lv: 'Latviešu',
		nb: 'Norsk (bokmål)',
		nl: 'Nederlands',
		pl: 'Polski',
		pt: 'Português',
		'pt-BR': 'Português (Brasil)',
		'pt-PT': 'Português (Portugal)',
		ro: 'Română',
		ru: 'Русский',
		sh: 'Srpskohrvatski / Српскохрватски',
		sk: 'Slovenčina',
		sl: 'Slovenščina',
		sq: 'Shqip',
		sr: 'Српски',
		sv: 'Svenska',
		ta: 'தமிழ்',
		tg: 'Тоҷикӣ',
		tr: 'Türkçe',
		uk: 'Українська',
		vi: 'Tiếng Việt',
	},

	interfaceToSpellingLangMap: {
		'da-DK': 'da',
		'de-DE': 'de-DE',
		'en-US': 'en',
		'es-ES': 'es',
		'fa-IR': 'fa',
		'fr-FR': 'fr-FR',
		'hi-IN': 'hi',
		'id-ID': 'id',
		'it-IT': 'it-IT',
		'lt-LT': 'lt',
		'ko-KR': 'ko',
		'nl-NL': 'nl',
		'no-NO': 'nb',
		'pl-PL': 'pl',
		'pt-BR': 'pt-BR',
		'ro-RO': 'ro',
		'ru-RU': 'ru',
		'tr-TR': 'tr',
		'uk-UA': 'uk',
		'vi-VN': 'vi',
	}
};