export default {
	default: [
		'id',
		'spaceId',
		'name',
		'description',
		'snippet',
		'iconEmoji',
		'iconImage',
		'iconName',
		'iconOption',
		'relationFormat',
		'type',
		'layout',
		'isHidden',
		'isArchived',
		'isReadonly',
		'isDeleted',
		'done',
		'fileExt',
		'fileMimeType',
		'sizeInBytes',
		'restrictions',
		'defaultTemplateId',
		'createdDate',
		'timestamp',
		'resolvedLayout',
	],

	sidebar: [
		'id',
		'spaceId',
		'name',
		'description',
		'snippet',
		'layout',
		'type',
		'iconEmoji',
		'iconImage',
		'iconName',
		'iconOption',
		'isReadonly',
		'isHidden',
		'isDeleted',
		'isArchived',
		'done',
		'relationFormat',
		'fileExt',
		'fileMimeType',
		'links',
		'restrictions',
		'source',
		'timestamp',
	],

	relation: [
		'id',
		'spaceId',
		'type',
		'layout',
		'name',
		'relationFormat',
		'relationKey',
		'isReadonly',
		'isHidden',
		'isDeleted',
		'isArchived',
		'restrictions',
		'relationMaxCount',
		'relationReadonlyValue',
		'relationDefaultValue',
		'relationFormatObjectTypes',
		'relationFormatIncludeTime',
		'sourceObject',
		'restrictions',
	],

	cover: [
		'coverId',
		'coverType',
		'coverX',
		'coverY',
		'coverScale'
	],

	option: [
		'id',
		'relationKey',
		'type',
		'layout',
		'name',
		'createdDate',
		'relationOptionColor',
		'orderId',
	],

	type: [
		'featuredRelations',
		'recommendedRelations',
		'recommendedFeaturedRelations',
		'recommendedHiddenRelations',
		'recommendedFileRelations',
		'recommendedLayout',
		'sourceObject',
		'uniqueKey',
		'defaultTemplateId',
		'defaultTypeId',
		'defaultViewType',
		'layoutAlign',
		'layoutWidth',
		'iconName',
		'iconOption',
		'pluralName',
		'headerRelationsLayout',
		'setOf',
		'orderId',
		'widgetLayout',
		'widgetLimit',
		'widgetViewId',
	],

	graph: [
		'id',
		'name',
		'pluralName',
		'snippet',
		'description',
		'iconEmoji',
		'iconImage',
		'iconName',
		'iconOption',
		'relationFormat',
		'type',
		'layout',
		'resolvedLayout',
		'done',
		'fileExt',
		'fileMimeType',
		'isDeleted',
		'isArchived',
		'restrictions',
		'timestamp',
	],

	template: [
		'templateIsBundled',
		'type',
		'targetObjectType',
		'internalFlags',
		'sourceObject'
	],

	space: [
		'spaceDashboardId',
		'spaceAccountStatus',
		'spaceLocalStatus',
		'spaceAccessType',
		'readersLimit',
		'writersLimit',
		'targetSpaceId',
		'creator',
		'createdDate',
		'chatId',
		'spaceUxType',
		'spacePushNotificationMode',
		'spaceOrder',
		'spaceJoinDate',
	],

	participant: [
		'identity',
		'participantPermissions',
		'participantStatus',
		'globalName'
	],

	syncStatus: [
		'syncStatus',
		'syncDate',
		'syncError',
	],

	pageCover: 'pageCover',

	key: {
		mention: 'mentions',
	}
};
