import { registerIcon } from '../registry';
import Accessibility from './accessibility';
import AddCircle from './add-circle';
import Airplane from './airplane';
import Alarm from './alarm';
import Albums from './albums';
import AlertCircle from './alert-circle';
import AmericanFootball from './american-football';
import Analytics from './analytics';
import Aperture from './aperture';
import Apps from './apps';
import Archive from './archive';
import ArrowBackCircle from './arrow-back-circle';
import ArrowDownCircle from './arrow-down-circle';
import ArrowForwardCircle from './arrow-forward-circle';
import ArrowRedoCircle from './arrow-redo-circle';
import ArrowRedo from './arrow-redo';
import ArrowUndoCircle from './arrow-undo-circle';
import ArrowUndo from './arrow-undo';
import ArrowUpCircle from './arrow-up-circle';
import AtCircle from './at-circle';
import Attach from './attach';
import Backspace from './backspace';
import BagAdd from './bag-add';
import BagCheck from './bag-check';
import BagHandle from './bag-handle';
import BagRemove from './bag-remove';
import Bag from './bag';
import Balloon from './balloon';
import Ban from './ban';
import Bandage from './bandage';
import BarChart from './bar-chart';
import Barbell from './barbell';
import Barcode from './barcode';
import Baseball from './baseball';
import Basket from './basket';
import Basketball from './basketball';
import BatteryCharging from './battery-charging';
import BatteryDead from './battery-dead';
import BatteryFull from './battery-full';
import BatteryHalf from './battery-half';
import Beaker from './beaker';
import Bed from './bed';
import Beer from './beer';
import Bicycle from './bicycle';
import Binoculars from './binoculars';
import Bluetooth from './bluetooth';
import Boat from './boat';
import Body from './body';
import Bonfire from './bonfire';
import Book from './book';
import Bookmark from './bookmark';
import Bookmarks from './bookmarks';
import BowlingBall from './bowling-ball';
import Briefcase from './briefcase';
import Browsers from './browsers';
import Brush from './brush';
import Bug from './bug';
import Build from './build';
import Bulb from './bulb';
import Bus from './bus';
import Business from './business';
import Cafe from './cafe';
import Calculator from './calculator';
import CalendarClear from './calendar-clear';
import CalendarNumber from './calendar-number';
import Calendar from './calendar';
import Call from './call';
import CameraReverse from './camera-reverse';
import Camera from './camera';
import CarSport from './car-sport';
import Car from './car';
import Card from './card';
import CaretBackCircle from './caret-back-circle';
import CaretBack from './caret-back';
import CaretDownCircle from './caret-down-circle';
import CaretDown from './caret-down';
import CaretForwardCircle from './caret-forward-circle';
import CaretForward from './caret-forward';
import CaretUpCircle from './caret-up-circle';
import CaretUp from './caret-up';
import Cart from './cart';
import Cash from './cash';
import Cellular from './cellular';
import ChatboxEllipses from './chatbox-ellipses';
import Chatbox from './chatbox';
import ChatbubbleEllipses from './chatbubble-ellipses';
import Chatbubble from './chatbubble';
import Chatbubbles from './chatbubbles';
import Checkbox from './checkbox';
import CheckmarkCircle from './checkmark-circle';
import CheckmarkDoneCircle from './checkmark-done-circle';
import ChevronBackCircle from './chevron-back-circle';
import ChevronDownCircle from './chevron-down-circle';
import ChevronForwardCircle from './chevron-forward-circle';
import ChevronUpCircle from './chevron-up-circle';
import Clipboard from './clipboard';
import CloseCircle from './close-circle';
import CloudCircle from './cloud-circle';
import CloudDone from './cloud-done';
import CloudDownload from './cloud-download';
import CloudOffline from './cloud-offline';
import CloudUpload from './cloud-upload';
import Cloud from './cloud';
import CloudyNight from './cloudy-night';
import Cloudy from './cloudy';
import CodeSlash from './code-slash';
import Code from './code';
import Cog from './cog';
import ColorFill from './color-fill';
import ColorFilter from './color-filter';
import ColorPalette from './color-palette';
import ColorWand from './color-wand';
import Compass from './compass';
import Construct from './construct';
import Contact from './contact';
import Contract from './contract';
import Contrast from './contrast';
import Copy from './copy';
import Create from './create';
import Crop from './crop';
import Cube from './cube';
import Cut from './cut';
import Desktop from './desktop';
import Diamond from './diamond';
import Dice from './dice';
import Disc from './disc';
import DocumentAttach from './document-attach';
import DocumentLock from './document-lock';
import DocumentText from './document-text';
import Document from './document';
import Documents from './documents';
import Download from './download';
import Duplicate from './duplicate';
import Ear from './ear';
import Earth from './earth';
import Easel from './easel';
import Egg from './egg';
import Ellipse from './ellipse';
import EllipsisHorizontalCircle from './ellipsis-horizontal-circle';
import EllipsisVerticalCircle from './ellipsis-vertical-circle';
import Enter from './enter';
import Exit from './exit';
import Expand from './expand';
import ExtensionPuzzle from './extension-puzzle';
import EyeOff from './eye-off';
import Eye from './eye';
import Eyedrop from './eyedrop';
import FastFood from './fast-food';
import Female from './female';
import FileTrayFull from './file-tray-full';
import FileTrayStacked from './file-tray-stacked';
import FileTray from './file-tray';
import Film from './film';
import FilterCircle from './filter-circle';
import FingerPrint from './finger-print';
import Fish from './fish';
import Fitness from './fitness';
import Flag from './flag';
import Flame from './flame';
import FlashOff from './flash-off';
import Flash from './flash';
import Flashlight from './flashlight';
import Flask from './flask';
import Flower from './flower';
import FolderOpen from './folder-open';
import Folder from './folder';
import Football from './football';
import Footsteps from './footsteps';
import Funnel from './funnel';
import GameController from './game-controller';
import Gift from './gift';
import GitBranch from './git-branch';
import GitCommit from './git-commit';
import GitCompare from './git-compare';
import GitMerge from './git-merge';
import GitNetwork from './git-network';
import GitPullRequest from './git-pull-request';
import Glasses from './glasses';
import Globe from './globe';
import Golf from './golf';
import Grid from './grid';
import Hammer from './hammer';
import HandLeft from './hand-left';
import HandRight from './hand-right';
import Happy from './happy';
import HardwareChip from './hardware-chip';
import Headset from './headset';
import HeartCircle from './heart-circle';
import HeartDislikeCircle from './heart-dislike-circle';
import HeartDislike from './heart-dislike';
import HeartHalf from './heart-half';
import Heart from './heart';
import HelpBuoy from './help-buoy';
import HelpCircle from './help-circle';
import Home from './home';
import Hourglass from './hourglass';
import IceCream from './ice-cream';
import IdCard from './id-card';
import Image from './image';
import Images from './images';
import Infinite from './infinite';
import InformationCircle from './information-circle';
import InvertMode from './invert-mode';
import Journal from './journal';
import Key from './key';
import Keypad from './keypad';
import Language from './language';
import Laptop from './laptop';
import Layers from './layers';
import Leaf from './leaf';
import Library from './library';
import Link from './link';
import ListCircle from './list-circle';
import List from './list';
import Locate from './locate';
import Location from './location';
import LockClosed from './lock-closed';
import LockOpen from './lock-open';
import LogIn from './log-in';
import LogOut from './log-out';
import LogoAlipay from './logo-alipay';
import LogoAmazon from './logo-amazon';
import LogoAmplify from './logo-amplify';
import LogoAndroid from './logo-android';
import Magnet from './magnet';
import MailOpen from './mail-open';
import MailUnread from './mail-unread';
import Mail from './mail';
import MaleFemale from './male-female';
import Male from './male';
import Man from './man';
import Map from './map';
import Medal from './medal';
import Medical from './medical';
import Medkit from './medkit';
import Megaphone from './megaphone';
import Menu from './menu';
import MicCircle from './mic-circle';
import MicOffCircle from './mic-off-circle';
import MicOff from './mic-off';
import Mic from './mic';
import Moon from './moon';
import Move from './move';
import MusicalNote from './musical-note';
import MusicalNotes from './musical-notes';
import NavigateCircle from './navigate-circle';
import Navigate from './navigate';
import Newspaper from './newspaper';
import NotificationsCircle from './notifications-circle';
import NotificationsOffCircle from './notifications-off-circle';
import NotificationsOff from './notifications-off';
import Notifications from './notifications';
import Nuclear from './nuclear';
import Nutrition from './nutrition';
import Options from './options';
import PaperPlane from './paper-plane';
import PartlySunny from './partly-sunny';
import PauseCircle from './pause-circle';
import Pause from './pause';
import Paw from './paw';
import Pencil from './pencil';
import PeopleCircle from './people-circle';
import People from './people';
import PersonAdd from './person-add';
import PersonCircle from './person-circle';
import PersonRemove from './person-remove';
import Person from './person';
import PhoneLandscape from './phone-landscape';
import PhonePortrait from './phone-portrait';
import PieChart from './pie-chart';
import Pin from './pin';
import Pint from './pint';
import Pizza from './pizza';
import Planet from './planet';
import PlayBackCircle from './play-back-circle';
import PlayBack from './play-back';
import PlayCircle from './play-circle';
import PlayForwardCircle from './play-forward-circle';
import PlayForward from './play-forward';
import PlaySkipBackCircle from './play-skip-back-circle';
import PlaySkipBack from './play-skip-back';
import PlaySkipForwardCircle from './play-skip-forward-circle';
import PlaySkipForward from './play-skip-forward';
import Play from './play';
import Podium from './podium';
import Power from './power';
import Pricetag from './pricetag';
import Pricetags from './pricetags';
import Print from './print';
import Prism from './prism';
import Pulse from './pulse';
import Push from './push';
import QrCode from './qr-code';
import RadioButtonOff from './radio-button-off';
import RadioButtonOn from './radio-button-on';
import Radio from './radio';
import Rainy from './rainy';
import Reader from './reader';
import Receipt from './receipt';
import Recording from './recording';
import RefreshCircle from './refresh-circle';
import Refresh from './refresh';
import ReloadCircle from './reload-circle';
import Reload from './reload';
import RemoveCircle from './remove-circle';
import Repeat from './repeat';
import Resize from './resize';
import Restaurant from './restaurant';
import Ribbon from './ribbon';
import Rocket from './rocket';
import Rose from './rose';
import Sad from './sad';
import Save from './save';
import Scale from './scale';
import ScanCircle from './scan-circle';
import Scan from './scan';
import School from './school';
import SearchCircle from './search-circle';
import Search from './search';
import Send from './send';
import Server from './server';
import Settings from './settings';
import Shapes from './shapes';
import ShareSocial from './share-social';
import Share from './share';
import ShieldCheckmark from './shield-checkmark';
import ShieldHalf from './shield-half';
import Shield from './shield';
import Shirt from './shirt';
import Shuffle from './shuffle';
import Skull from './skull';
import Snow from './snow';
import Sparkles from './sparkles';
import Speedometer from './speedometer';
import Square from './square';
import StarHalf from './star-half';
import Star from './star';
import StatsChart from './stats-chart';
import StopCircle from './stop-circle';
import Stop from './stop';
import Stopwatch from './stopwatch';
import Storefront from './storefront';
import Subway from './subway';
import Sunny from './sunny';
import SwapHorizontal from './swap-horizontal';
import SwapVertical from './swap-vertical';
import SyncCircle from './sync-circle';
import Sync from './sync';
import TabletLandscape from './tablet-landscape';
import TabletPortrait from './tablet-portrait';
import Telescope from './telescope';
import Tennisball from './tennisball';
import Terminal from './terminal';
import Text from './text';
import Thermometer from './thermometer';
import ThumbsDown from './thumbs-down';
import ThumbsUp from './thumbs-up';
import Thunderstorm from './thunderstorm';
import Ticket from './ticket';
import Time from './time';
import Timer from './timer';
import Today from './today';
import Toggle from './toggle';
import TrailSign from './trail-sign';
import Train from './train';
import Transgender from './transgender';
import TrashBin from './trash-bin';
import Trash from './trash';
import TrendingDown from './trending-down';
import TrendingUp from './trending-up';
import Triangle from './triangle';
import Trophy from './trophy';
import Tv from './tv';
import Umbrella from './umbrella';
import Unlink from './unlink';
import VideocamOff from './videocam-off';
import Videocam from './videocam';
import VolumeHigh from './volume-high';
import VolumeLow from './volume-low';
import VolumeMedium from './volume-medium';
import VolumeMute from './volume-mute';
import VolumeOff from './volume-off';
import Walk from './walk';
import Wallet from './wallet';
import Warning from './warning';
import Watch from './watch';
import Water from './water';
import Wifi from './wifi';
import Wine from './wine';
import Woman from './woman';

registerIcon('type/accessibility', Accessibility);
registerIcon('type/add-circle', AddCircle);
registerIcon('type/airplane', Airplane);
registerIcon('type/alarm', Alarm);
registerIcon('type/albums', Albums);
registerIcon('type/alert-circle', AlertCircle);
registerIcon('type/american-football', AmericanFootball);
registerIcon('type/analytics', Analytics);
registerIcon('type/aperture', Aperture);
registerIcon('type/apps', Apps);
registerIcon('type/archive', Archive);
registerIcon('type/arrow-back-circle', ArrowBackCircle);
registerIcon('type/arrow-down-circle', ArrowDownCircle);
registerIcon('type/arrow-forward-circle', ArrowForwardCircle);
registerIcon('type/arrow-redo-circle', ArrowRedoCircle);
registerIcon('type/arrow-redo', ArrowRedo);
registerIcon('type/arrow-undo-circle', ArrowUndoCircle);
registerIcon('type/arrow-undo', ArrowUndo);
registerIcon('type/arrow-up-circle', ArrowUpCircle);
registerIcon('type/at-circle', AtCircle);
registerIcon('type/attach', Attach);
registerIcon('type/backspace', Backspace);
registerIcon('type/bag-add', BagAdd);
registerIcon('type/bag-check', BagCheck);
registerIcon('type/bag-handle', BagHandle);
registerIcon('type/bag-remove', BagRemove);
registerIcon('type/bag', Bag);
registerIcon('type/balloon', Balloon);
registerIcon('type/ban', Ban);
registerIcon('type/bandage', Bandage);
registerIcon('type/bar-chart', BarChart);
registerIcon('type/barbell', Barbell);
registerIcon('type/barcode', Barcode);
registerIcon('type/baseball', Baseball);
registerIcon('type/basket', Basket);
registerIcon('type/basketball', Basketball);
registerIcon('type/battery-charging', BatteryCharging);
registerIcon('type/battery-dead', BatteryDead);
registerIcon('type/battery-full', BatteryFull);
registerIcon('type/battery-half', BatteryHalf);
registerIcon('type/beaker', Beaker);
registerIcon('type/bed', Bed);
registerIcon('type/beer', Beer);
registerIcon('type/bicycle', Bicycle);
registerIcon('type/binoculars', Binoculars);
registerIcon('type/bluetooth', Bluetooth);
registerIcon('type/boat', Boat);
registerIcon('type/body', Body);
registerIcon('type/bonfire', Bonfire);
registerIcon('type/book', Book);
registerIcon('type/bookmark', Bookmark);
registerIcon('type/bookmarks', Bookmarks);
registerIcon('type/bowling-ball', BowlingBall);
registerIcon('type/briefcase', Briefcase);
registerIcon('type/browsers', Browsers);
registerIcon('type/brush', Brush);
registerIcon('type/bug', Bug);
registerIcon('type/build', Build);
registerIcon('type/bulb', Bulb);
registerIcon('type/bus', Bus);
registerIcon('type/business', Business);
registerIcon('type/cafe', Cafe);
registerIcon('type/calculator', Calculator);
registerIcon('type/calendar-clear', CalendarClear);
registerIcon('type/calendar-number', CalendarNumber);
registerIcon('type/calendar', Calendar);
registerIcon('type/call', Call);
registerIcon('type/camera-reverse', CameraReverse);
registerIcon('type/camera', Camera);
registerIcon('type/car-sport', CarSport);
registerIcon('type/car', Car);
registerIcon('type/card', Card);
registerIcon('type/caret-back-circle', CaretBackCircle);
registerIcon('type/caret-back', CaretBack);
registerIcon('type/caret-down-circle', CaretDownCircle);
registerIcon('type/caret-down', CaretDown);
registerIcon('type/caret-forward-circle', CaretForwardCircle);
registerIcon('type/caret-forward', CaretForward);
registerIcon('type/caret-up-circle', CaretUpCircle);
registerIcon('type/caret-up', CaretUp);
registerIcon('type/cart', Cart);
registerIcon('type/cash', Cash);
registerIcon('type/cellular', Cellular);
registerIcon('type/chatbox-ellipses', ChatboxEllipses);
registerIcon('type/chatbox', Chatbox);
registerIcon('type/chatbubble-ellipses', ChatbubbleEllipses);
registerIcon('type/chatbubble', Chatbubble);
registerIcon('type/chatbubbles', Chatbubbles);
registerIcon('type/checkbox', Checkbox);
registerIcon('type/checkmark-circle', CheckmarkCircle);
registerIcon('type/checkmark-done-circle', CheckmarkDoneCircle);
registerIcon('type/chevron-back-circle', ChevronBackCircle);
registerIcon('type/chevron-down-circle', ChevronDownCircle);
registerIcon('type/chevron-forward-circle', ChevronForwardCircle);
registerIcon('type/chevron-up-circle', ChevronUpCircle);
registerIcon('type/clipboard', Clipboard);
registerIcon('type/close-circle', CloseCircle);
registerIcon('type/cloud-circle', CloudCircle);
registerIcon('type/cloud-done', CloudDone);
registerIcon('type/cloud-download', CloudDownload);
registerIcon('type/cloud-offline', CloudOffline);
registerIcon('type/cloud-upload', CloudUpload);
registerIcon('type/cloud', Cloud);
registerIcon('type/cloudy-night', CloudyNight);
registerIcon('type/cloudy', Cloudy);
registerIcon('type/code-slash', CodeSlash);
registerIcon('type/code', Code);
registerIcon('type/cog', Cog);
registerIcon('type/color-fill', ColorFill);
registerIcon('type/color-filter', ColorFilter);
registerIcon('type/color-palette', ColorPalette);
registerIcon('type/color-wand', ColorWand);
registerIcon('type/compass', Compass);
registerIcon('type/construct', Construct);
registerIcon('type/contact', Contact);
registerIcon('type/contract', Contract);
registerIcon('type/contrast', Contrast);
registerIcon('type/copy', Copy);
registerIcon('type/create', Create);
registerIcon('type/crop', Crop);
registerIcon('type/cube', Cube);
registerIcon('type/cut', Cut);
registerIcon('type/desktop', Desktop);
registerIcon('type/diamond', Diamond);
registerIcon('type/dice', Dice);
registerIcon('type/disc', Disc);
registerIcon('type/document-attach', DocumentAttach);
registerIcon('type/document-lock', DocumentLock);
registerIcon('type/document-text', DocumentText);
registerIcon('type/document', Document);
registerIcon('type/documents', Documents);
registerIcon('type/download', Download);
registerIcon('type/duplicate', Duplicate);
registerIcon('type/ear', Ear);
registerIcon('type/earth', Earth);
registerIcon('type/easel', Easel);
registerIcon('type/egg', Egg);
registerIcon('type/ellipse', Ellipse);
registerIcon('type/ellipsis-horizontal-circle', EllipsisHorizontalCircle);
registerIcon('type/ellipsis-vertical-circle', EllipsisVerticalCircle);
registerIcon('type/enter', Enter);
registerIcon('type/exit', Exit);
registerIcon('type/expand', Expand);
registerIcon('type/extension-puzzle', ExtensionPuzzle);
registerIcon('type/eye-off', EyeOff);
registerIcon('type/eye', Eye);
registerIcon('type/eyedrop', Eyedrop);
registerIcon('type/fast-food', FastFood);
registerIcon('type/female', Female);
registerIcon('type/file-tray-full', FileTrayFull);
registerIcon('type/file-tray-stacked', FileTrayStacked);
registerIcon('type/file-tray', FileTray);
registerIcon('type/film', Film);
registerIcon('type/filter-circle', FilterCircle);
registerIcon('type/finger-print', FingerPrint);
registerIcon('type/fish', Fish);
registerIcon('type/fitness', Fitness);
registerIcon('type/flag', Flag);
registerIcon('type/flame', Flame);
registerIcon('type/flash-off', FlashOff);
registerIcon('type/flash', Flash);
registerIcon('type/flashlight', Flashlight);
registerIcon('type/flask', Flask);
registerIcon('type/flower', Flower);
registerIcon('type/folder-open', FolderOpen);
registerIcon('type/folder', Folder);
registerIcon('type/football', Football);
registerIcon('type/footsteps', Footsteps);
registerIcon('type/funnel', Funnel);
registerIcon('type/game-controller', GameController);
registerIcon('type/gift', Gift);
registerIcon('type/git-branch', GitBranch);
registerIcon('type/git-commit', GitCommit);
registerIcon('type/git-compare', GitCompare);
registerIcon('type/git-merge', GitMerge);
registerIcon('type/git-network', GitNetwork);
registerIcon('type/git-pull-request', GitPullRequest);
registerIcon('type/glasses', Glasses);
registerIcon('type/globe', Globe);
registerIcon('type/golf', Golf);
registerIcon('type/grid', Grid);
registerIcon('type/hammer', Hammer);
registerIcon('type/hand-left', HandLeft);
registerIcon('type/hand-right', HandRight);
registerIcon('type/happy', Happy);
registerIcon('type/hardware-chip', HardwareChip);
registerIcon('type/headset', Headset);
registerIcon('type/heart-circle', HeartCircle);
registerIcon('type/heart-dislike-circle', HeartDislikeCircle);
registerIcon('type/heart-dislike', HeartDislike);
registerIcon('type/heart-half', HeartHalf);
registerIcon('type/heart', Heart);
registerIcon('type/help-buoy', HelpBuoy);
registerIcon('type/help-circle', HelpCircle);
registerIcon('type/home', Home);
registerIcon('type/hourglass', Hourglass);
registerIcon('type/ice-cream', IceCream);
registerIcon('type/id-card', IdCard);
registerIcon('type/image', Image);
registerIcon('type/images', Images);
registerIcon('type/infinite', Infinite);
registerIcon('type/information-circle', InformationCircle);
registerIcon('type/invert-mode', InvertMode);
registerIcon('type/journal', Journal);
registerIcon('type/key', Key);
registerIcon('type/keypad', Keypad);
registerIcon('type/language', Language);
registerIcon('type/laptop', Laptop);
registerIcon('type/layers', Layers);
registerIcon('type/leaf', Leaf);
registerIcon('type/library', Library);
registerIcon('type/link', Link);
registerIcon('type/list-circle', ListCircle);
registerIcon('type/list', List);
registerIcon('type/locate', Locate);
registerIcon('type/location', Location);
registerIcon('type/lock-closed', LockClosed);
registerIcon('type/lock-open', LockOpen);
registerIcon('type/log-in', LogIn);
registerIcon('type/log-out', LogOut);
registerIcon('type/logo-alipay', LogoAlipay);
registerIcon('type/logo-amazon', LogoAmazon);
registerIcon('type/logo-amplify', LogoAmplify);
registerIcon('type/logo-android', LogoAndroid);
registerIcon('type/magnet', Magnet);
registerIcon('type/mail-open', MailOpen);
registerIcon('type/mail-unread', MailUnread);
registerIcon('type/mail', Mail);
registerIcon('type/male-female', MaleFemale);
registerIcon('type/male', Male);
registerIcon('type/man', Man);
registerIcon('type/map', Map);
registerIcon('type/medal', Medal);
registerIcon('type/medical', Medical);
registerIcon('type/medkit', Medkit);
registerIcon('type/megaphone', Megaphone);
registerIcon('type/menu', Menu);
registerIcon('type/mic-circle', MicCircle);
registerIcon('type/mic-off-circle', MicOffCircle);
registerIcon('type/mic-off', MicOff);
registerIcon('type/mic', Mic);
registerIcon('type/moon', Moon);
registerIcon('type/move', Move);
registerIcon('type/musical-note', MusicalNote);
registerIcon('type/musical-notes', MusicalNotes);
registerIcon('type/navigate-circle', NavigateCircle);
registerIcon('type/navigate', Navigate);
registerIcon('type/newspaper', Newspaper);
registerIcon('type/notifications-circle', NotificationsCircle);
registerIcon('type/notifications-off-circle', NotificationsOffCircle);
registerIcon('type/notifications-off', NotificationsOff);
registerIcon('type/notifications', Notifications);
registerIcon('type/nuclear', Nuclear);
registerIcon('type/nutrition', Nutrition);
registerIcon('type/options', Options);
registerIcon('type/paper-plane', PaperPlane);
registerIcon('type/partly-sunny', PartlySunny);
registerIcon('type/pause-circle', PauseCircle);
registerIcon('type/pause', Pause);
registerIcon('type/paw', Paw);
registerIcon('type/pencil', Pencil);
registerIcon('type/people-circle', PeopleCircle);
registerIcon('type/people', People);
registerIcon('type/person-add', PersonAdd);
registerIcon('type/person-circle', PersonCircle);
registerIcon('type/person-remove', PersonRemove);
registerIcon('type/person', Person);
registerIcon('type/phone-landscape', PhoneLandscape);
registerIcon('type/phone-portrait', PhonePortrait);
registerIcon('type/pie-chart', PieChart);
registerIcon('type/pin', Pin);
registerIcon('type/pint', Pint);
registerIcon('type/pizza', Pizza);
registerIcon('type/planet', Planet);
registerIcon('type/play-back-circle', PlayBackCircle);
registerIcon('type/play-back', PlayBack);
registerIcon('type/play-circle', PlayCircle);
registerIcon('type/play-forward-circle', PlayForwardCircle);
registerIcon('type/play-forward', PlayForward);
registerIcon('type/play-skip-back-circle', PlaySkipBackCircle);
registerIcon('type/play-skip-back', PlaySkipBack);
registerIcon('type/play-skip-forward-circle', PlaySkipForwardCircle);
registerIcon('type/play-skip-forward', PlaySkipForward);
registerIcon('type/play', Play);
registerIcon('type/podium', Podium);
registerIcon('type/power', Power);
registerIcon('type/pricetag', Pricetag);
registerIcon('type/pricetags', Pricetags);
registerIcon('type/print', Print);
registerIcon('type/prism', Prism);
registerIcon('type/pulse', Pulse);
registerIcon('type/push', Push);
registerIcon('type/qr-code', QrCode);
registerIcon('type/radio-button-off', RadioButtonOff);
registerIcon('type/radio-button-on', RadioButtonOn);
registerIcon('type/radio', Radio);
registerIcon('type/rainy', Rainy);
registerIcon('type/reader', Reader);
registerIcon('type/receipt', Receipt);
registerIcon('type/recording', Recording);
registerIcon('type/refresh-circle', RefreshCircle);
registerIcon('type/refresh', Refresh);
registerIcon('type/reload-circle', ReloadCircle);
registerIcon('type/reload', Reload);
registerIcon('type/remove-circle', RemoveCircle);
registerIcon('type/repeat', Repeat);
registerIcon('type/resize', Resize);
registerIcon('type/restaurant', Restaurant);
registerIcon('type/ribbon', Ribbon);
registerIcon('type/rocket', Rocket);
registerIcon('type/rose', Rose);
registerIcon('type/sad', Sad);
registerIcon('type/save', Save);
registerIcon('type/scale', Scale);
registerIcon('type/scan-circle', ScanCircle);
registerIcon('type/scan', Scan);
registerIcon('type/school', School);
registerIcon('type/search-circle', SearchCircle);
registerIcon('type/search', Search);
registerIcon('type/send', Send);
registerIcon('type/server', Server);
registerIcon('type/settings', Settings);
registerIcon('type/shapes', Shapes);
registerIcon('type/share-social', ShareSocial);
registerIcon('type/share', Share);
registerIcon('type/shield-checkmark', ShieldCheckmark);
registerIcon('type/shield-half', ShieldHalf);
registerIcon('type/shield', Shield);
registerIcon('type/shirt', Shirt);
registerIcon('type/shuffle', Shuffle);
registerIcon('type/skull', Skull);
registerIcon('type/snow', Snow);
registerIcon('type/sparkles', Sparkles);
registerIcon('type/speedometer', Speedometer);
registerIcon('type/square', Square);
registerIcon('type/star-half', StarHalf);
registerIcon('type/star', Star);
registerIcon('type/stats-chart', StatsChart);
registerIcon('type/stop-circle', StopCircle);
registerIcon('type/stop', Stop);
registerIcon('type/stopwatch', Stopwatch);
registerIcon('type/storefront', Storefront);
registerIcon('type/subway', Subway);
registerIcon('type/sunny', Sunny);
registerIcon('type/swap-horizontal', SwapHorizontal);
registerIcon('type/swap-vertical', SwapVertical);
registerIcon('type/sync-circle', SyncCircle);
registerIcon('type/sync', Sync);
registerIcon('type/tablet-landscape', TabletLandscape);
registerIcon('type/tablet-portrait', TabletPortrait);
registerIcon('type/telescope', Telescope);
registerIcon('type/tennisball', Tennisball);
registerIcon('type/terminal', Terminal);
registerIcon('type/text', Text);
registerIcon('type/thermometer', Thermometer);
registerIcon('type/thumbs-down', ThumbsDown);
registerIcon('type/thumbs-up', ThumbsUp);
registerIcon('type/thunderstorm', Thunderstorm);
registerIcon('type/ticket', Ticket);
registerIcon('type/time', Time);
registerIcon('type/timer', Timer);
registerIcon('type/today', Today);
registerIcon('type/toggle', Toggle);
registerIcon('type/trail-sign', TrailSign);
registerIcon('type/train', Train);
registerIcon('type/transgender', Transgender);
registerIcon('type/trash-bin', TrashBin);
registerIcon('type/trash', Trash);
registerIcon('type/trending-down', TrendingDown);
registerIcon('type/trending-up', TrendingUp);
registerIcon('type/triangle', Triangle);
registerIcon('type/trophy', Trophy);
registerIcon('type/tv', Tv);
registerIcon('type/umbrella', Umbrella);
registerIcon('type/unlink', Unlink);
registerIcon('type/videocam-off', VideocamOff);
registerIcon('type/videocam', Videocam);
registerIcon('type/volume-high', VolumeHigh);
registerIcon('type/volume-low', VolumeLow);
registerIcon('type/volume-medium', VolumeMedium);
registerIcon('type/volume-mute', VolumeMute);
registerIcon('type/volume-off', VolumeOff);
registerIcon('type/walk', Walk);
registerIcon('type/wallet', Wallet);
registerIcon('type/warning', Warning);
registerIcon('type/watch', Watch);
registerIcon('type/water', Water);
registerIcon('type/wifi', Wifi);
registerIcon('type/wine', Wine);
registerIcon('type/woman', Woman);
