import { registerIcon } from '../../registry';
import Activation from './activation';
import AnyId from './anyId';
import Confirm from './confirm';
import Create from './create';
import Emoji from './emoji';
import Error from './error';
import Invite from './invite';
import Join from './join';
import Key from './key';
import Lock from './lock';
import RedLock from './redLock';
import Success from './success';
import Update from './update';
import Updated from './updated';
import Warning from './warning';

registerIcon('popup/header/activation', Activation);
registerIcon('popup/header/anyId', AnyId);
registerIcon('popup/header/confirm', Confirm);
registerIcon('popup/header/create', Create);
registerIcon('popup/header/emoji', Emoji);
registerIcon('popup/header/error', Error);
registerIcon('popup/header/invite', Invite);
registerIcon('popup/header/join', Join);
registerIcon('popup/header/key', Key);
registerIcon('popup/header/lock', Lock);
registerIcon('popup/header/redLock', RedLock);
registerIcon('popup/header/success', Success);
registerIcon('popup/header/update', Update);
registerIcon('popup/header/updated', Updated);
registerIcon('popup/header/warning', Warning);
