 export enum AIMode {
	Default			 = 0,
	Summarize		 = 1,
	Grammar			 = 2,
	Shorten			 = 3,
	Expand			 = 4,
	Bullet			 = 5,
	Table			 = 6,
	Casual			 = 7,
	Funny			 = 8,
	Confident		 = 9,
	Straightforward	 = 10,
	Professional	 = 11,
	Translate		 = 12,
};