// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.36.0
// source: pb/protos/changes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Value } from "../../google/protobuf/struct";
import {
  Block,
  Block_Position,
  DeviceInfo,
  FileInfo,
  Notification,
  Notification_Status,
  RelationLink,
  SmartBlockSnapshotBase,
} from "../../pkg/lib/pb/model/protos/models";
import { Event_Message } from "./events";

export const protobufPackage = "anytype";

export enum ModifyOp {
  Set = 0,
  Unset = 1,
  Inc = 2,
  AddToSet = 3,
  Pull = 4,
  UNRECOGNIZED = -1,
}

/** the element of change tree used to store and internal apply smartBlock history */
export interface Change {
  /** set of actions to apply */
  content: Change_Content[];
  /** snapshot - when not null, the Content will be ignored */
  snapshot:
    | Change_Snapshot
    | undefined;
  /** file keys related to changes content */
  fileKeys: Change_FileKeys[];
  /** creation timestamp */
  timestamp: number;
  /** version of business logic */
  version: number;
  /** business-level type of change applied to object */
  changeType: number;
}

export interface Change_Snapshot {
  /** logId -> lastChangeId */
  logHeads: { [key: string]: string };
  /** snapshot data */
  data:
    | SmartBlockSnapshotBase
    | undefined;
  /** all file keys related to doc */
  fileKeys: Change_FileKeys[];
}

export interface Change_Snapshot_LogHeadsEntry {
  key: string;
  value: string;
}

export interface Change_FileKeys {
  hash: string;
  keys: { [key: string]: string };
}

export interface Change_FileKeys_KeysEntry {
  key: string;
  value: string;
}

export interface Change_Content {
  blockCreate?: Change_BlockCreate | undefined;
  blockUpdate?: Change_BlockUpdate | undefined;
  blockRemove?: Change_BlockRemove | undefined;
  blockMove?: Change_BlockMove | undefined;
  blockDuplicate?: Change_BlockDuplicate | undefined;
  relationAdd?: Change_RelationAdd | undefined;
  relationRemove?: Change_RelationRemove | undefined;
  detailsSet?: Change_DetailsSet | undefined;
  detailsUnset?: Change_DetailsUnset | undefined;
  objectTypeAdd?: Change_ObjectTypeAdd | undefined;
  objectTypeRemove?: Change_ObjectTypeRemove | undefined;
  storeKeySet?: Change_StoreKeySet | undefined;
  storeKeyUnset?: Change_StoreKeyUnset | undefined;
  storeSliceUpdate?: Change_StoreSliceUpdate | undefined;
  originalCreatedTimestampSet?: Change_OriginalCreatedTimestampSet | undefined;
  setFileInfo?: Change_SetFileInfo | undefined;
  notificationCreate?: Change_NotificationCreate | undefined;
  notificationUpdate?: Change_NotificationUpdate | undefined;
  deviceAdd?: Change_DeviceAdd | undefined;
  deviceUpdate?: Change_DeviceUpdate | undefined;
}

export interface Change_BlockCreate {
  targetId: string;
  position: Block_Position;
  blocks: Block[];
}

export interface Change_BlockUpdate {
  events: Event_Message[];
}

export interface Change_BlockRemove {
  ids: string[];
}

export interface Change_BlockMove {
  targetId: string;
  position: Block_Position;
  ids: string[];
}

export interface Change_BlockDuplicate {
  targetId: string;
  position: Block_Position;
  ids: string[];
}

export interface Change_DetailsSet {
  key: string;
  value: any | undefined;
}

export interface Change_DetailsUnset {
  key: string;
}

export interface Change_RelationAdd {
  relationLinks: RelationLink[];
}

export interface Change_RelationRemove {
  relationKey: string[];
}

export interface Change_ObjectTypeAdd {
  url: string;
  key: string;
}

export interface Change_ObjectTypeRemove {
  url: string;
  key: string;
}

export interface Change_StoreKeySet {
  path: string[];
  value: any | undefined;
}

export interface Change_StoreKeyUnset {
  path: string[];
}

export interface Change_StoreSliceUpdate {
  key: string;
  add?: Change_StoreSliceUpdate_Add | undefined;
  remove?: Change_StoreSliceUpdate_Remove | undefined;
  move?: Change_StoreSliceUpdate_Move | undefined;
}

export interface Change_StoreSliceUpdate_Add {
  afterId: string;
  ids: string[];
}

export interface Change_StoreSliceUpdate_Remove {
  ids: string[];
}

export interface Change_StoreSliceUpdate_Move {
  afterId: string;
  ids: string[];
}

export interface Change_OriginalCreatedTimestampSet {
  ts: number;
}

export interface Change_SetFileInfo {
  fileInfo: FileInfo | undefined;
}

export interface Change_NotificationCreate {
  notification: Notification | undefined;
}

export interface Change_NotificationUpdate {
  id: string;
  status: Notification_Status;
}

export interface Change_DeviceAdd {
  device: DeviceInfo | undefined;
}

export interface Change_DeviceUpdate {
  id: string;
  name: string;
}

export interface ChangeNoSnapshot {
  /** set of actions to apply */
  content: Change_Content[];
  /** file keys related to changes content */
  fileKeys: Change_FileKeys[];
  /** creation timestamp */
  timestamp: number;
  /** version of business logic */
  version: number;
  /** business-level type of change applied to object */
  changeType: number;
}

export interface StoreChange {
  changeSet: StoreChangeContent[];
}

export interface StoreChangeContent {
  create?: DocumentCreate | undefined;
  modify?: DocumentModify | undefined;
  delete?: DocumentDelete | undefined;
}

export interface DocumentCreate {
  collection: string;
  documentId: string;
  /** json */
  value: string;
}

export interface DocumentModify {
  collection: string;
  documentId: string;
  keys: KeyModify[];
}

export interface KeyModify {
  /** key path; example: [user, email] */
  keyPath: string[];
  /** modify op: set, unset, inc, etc. */
  modifyOp: ModifyOp;
  /** json value; example: '"new@email.com"' */
  modifyValue: string;
}

export interface DocumentDelete {
  collection: string;
  documentId: string;
}

function createBaseChange(): Change {
  return { content: [], snapshot: undefined, fileKeys: [], timestamp: 0, version: 0, changeType: 0 };
}

export const Change: MessageFns<Change> = {
  encode(message: Change, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.content) {
      Change_Content.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.snapshot !== undefined) {
      Change_Snapshot.encode(message.snapshot, writer.uint32(34).fork()).join();
    }
    for (const v of message.fileKeys) {
      Change_FileKeys.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(56).int64(message.timestamp);
    }
    if (message.version !== 0) {
      writer.uint32(64).uint32(message.version);
    }
    if (message.changeType !== 0) {
      writer.uint32(72).uint32(message.changeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content.push(Change_Content.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.snapshot = Change_Snapshot.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileKeys.push(Change_FileKeys.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.changeType = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change>, I>>(base?: I): Change {
    return Change.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change>, I>>(object: I): Change {
    const message = createBaseChange();
    message.content = object.content?.map((e) => Change_Content.fromPartial(e)) || [];
    message.snapshot = (object.snapshot !== undefined && object.snapshot !== null)
      ? Change_Snapshot.fromPartial(object.snapshot)
      : undefined;
    message.fileKeys = object.fileKeys?.map((e) => Change_FileKeys.fromPartial(e)) || [];
    message.timestamp = object.timestamp ?? 0;
    message.version = object.version ?? 0;
    message.changeType = object.changeType ?? 0;
    return message;
  },
};

function createBaseChange_Snapshot(): Change_Snapshot {
  return { logHeads: {}, data: undefined, fileKeys: [] };
}

export const Change_Snapshot: MessageFns<Change_Snapshot> = {
  encode(message: Change_Snapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.logHeads).forEach(([key, value]: [string, string]) => {
      Change_Snapshot_LogHeadsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    if (message.data !== undefined) {
      SmartBlockSnapshotBase.encode(message.data, writer.uint32(18).fork()).join();
    }
    for (const v of message.fileKeys) {
      Change_FileKeys.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_Snapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_Snapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = Change_Snapshot_LogHeadsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.logHeads[entry1.key] = entry1.value;
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = SmartBlockSnapshotBase.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fileKeys.push(Change_FileKeys.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_Snapshot>, I>>(base?: I): Change_Snapshot {
    return Change_Snapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_Snapshot>, I>>(object: I): Change_Snapshot {
    const message = createBaseChange_Snapshot();
    message.logHeads = (globalThis.Object.entries(object.logHeads ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.data = (object.data !== undefined && object.data !== null)
      ? SmartBlockSnapshotBase.fromPartial(object.data)
      : undefined;
    message.fileKeys = object.fileKeys?.map((e) => Change_FileKeys.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChange_Snapshot_LogHeadsEntry(): Change_Snapshot_LogHeadsEntry {
  return { key: "", value: "" };
}

export const Change_Snapshot_LogHeadsEntry: MessageFns<Change_Snapshot_LogHeadsEntry> = {
  encode(message: Change_Snapshot_LogHeadsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_Snapshot_LogHeadsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_Snapshot_LogHeadsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_Snapshot_LogHeadsEntry>, I>>(base?: I): Change_Snapshot_LogHeadsEntry {
    return Change_Snapshot_LogHeadsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_Snapshot_LogHeadsEntry>, I>>(
    object: I,
  ): Change_Snapshot_LogHeadsEntry {
    const message = createBaseChange_Snapshot_LogHeadsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseChange_FileKeys(): Change_FileKeys {
  return { hash: "", keys: {} };
}

export const Change_FileKeys: MessageFns<Change_FileKeys> = {
  encode(message: Change_FileKeys, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hash !== "") {
      writer.uint32(10).string(message.hash);
    }
    globalThis.Object.entries(message.keys).forEach(([key, value]: [string, string]) => {
      Change_FileKeys_KeysEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_FileKeys {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_FileKeys();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = Change_FileKeys_KeysEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.keys[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_FileKeys>, I>>(base?: I): Change_FileKeys {
    return Change_FileKeys.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_FileKeys>, I>>(object: I): Change_FileKeys {
    const message = createBaseChange_FileKeys();
    message.hash = object.hash ?? "";
    message.keys = (globalThis.Object.entries(object.keys ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseChange_FileKeys_KeysEntry(): Change_FileKeys_KeysEntry {
  return { key: "", value: "" };
}

export const Change_FileKeys_KeysEntry: MessageFns<Change_FileKeys_KeysEntry> = {
  encode(message: Change_FileKeys_KeysEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_FileKeys_KeysEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_FileKeys_KeysEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_FileKeys_KeysEntry>, I>>(base?: I): Change_FileKeys_KeysEntry {
    return Change_FileKeys_KeysEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_FileKeys_KeysEntry>, I>>(object: I): Change_FileKeys_KeysEntry {
    const message = createBaseChange_FileKeys_KeysEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseChange_Content(): Change_Content {
  return {};
}

export const Change_Content: MessageFns<Change_Content> = {
  encode(message: Change_Content, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockCreate !== undefined) {
      Change_BlockCreate.encode(message.blockCreate, writer.uint32(10).fork()).join();
    }
    if (message.blockUpdate !== undefined) {
      Change_BlockUpdate.encode(message.blockUpdate, writer.uint32(18).fork()).join();
    }
    if (message.blockRemove !== undefined) {
      Change_BlockRemove.encode(message.blockRemove, writer.uint32(26).fork()).join();
    }
    if (message.blockMove !== undefined) {
      Change_BlockMove.encode(message.blockMove, writer.uint32(34).fork()).join();
    }
    if (message.blockDuplicate !== undefined) {
      Change_BlockDuplicate.encode(message.blockDuplicate, writer.uint32(42).fork()).join();
    }
    if (message.relationAdd !== undefined) {
      Change_RelationAdd.encode(message.relationAdd, writer.uint32(402).fork()).join();
    }
    if (message.relationRemove !== undefined) {
      Change_RelationRemove.encode(message.relationRemove, writer.uint32(410).fork()).join();
    }
    if (message.detailsSet !== undefined) {
      Change_DetailsSet.encode(message.detailsSet, writer.uint32(802).fork()).join();
    }
    if (message.detailsUnset !== undefined) {
      Change_DetailsUnset.encode(message.detailsUnset, writer.uint32(810).fork()).join();
    }
    if (message.objectTypeAdd !== undefined) {
      Change_ObjectTypeAdd.encode(message.objectTypeAdd, writer.uint32(842).fork()).join();
    }
    if (message.objectTypeRemove !== undefined) {
      Change_ObjectTypeRemove.encode(message.objectTypeRemove, writer.uint32(850).fork()).join();
    }
    if (message.storeKeySet !== undefined) {
      Change_StoreKeySet.encode(message.storeKeySet, writer.uint32(858).fork()).join();
    }
    if (message.storeKeyUnset !== undefined) {
      Change_StoreKeyUnset.encode(message.storeKeyUnset, writer.uint32(866).fork()).join();
    }
    if (message.storeSliceUpdate !== undefined) {
      Change_StoreSliceUpdate.encode(message.storeSliceUpdate, writer.uint32(874).fork()).join();
    }
    if (message.originalCreatedTimestampSet !== undefined) {
      Change_OriginalCreatedTimestampSet.encode(message.originalCreatedTimestampSet, writer.uint32(882).fork()).join();
    }
    if (message.setFileInfo !== undefined) {
      Change_SetFileInfo.encode(message.setFileInfo, writer.uint32(890).fork()).join();
    }
    if (message.notificationCreate !== undefined) {
      Change_NotificationCreate.encode(message.notificationCreate, writer.uint32(898).fork()).join();
    }
    if (message.notificationUpdate !== undefined) {
      Change_NotificationUpdate.encode(message.notificationUpdate, writer.uint32(906).fork()).join();
    }
    if (message.deviceAdd !== undefined) {
      Change_DeviceAdd.encode(message.deviceAdd, writer.uint32(914).fork()).join();
    }
    if (message.deviceUpdate !== undefined) {
      Change_DeviceUpdate.encode(message.deviceUpdate, writer.uint32(922).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_Content {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_Content();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockCreate = Change_BlockCreate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.blockUpdate = Change_BlockUpdate.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.blockRemove = Change_BlockRemove.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.blockMove = Change_BlockMove.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.blockDuplicate = Change_BlockDuplicate.decode(reader, reader.uint32());
          continue;
        }
        case 50: {
          if (tag !== 402) {
            break;
          }

          message.relationAdd = Change_RelationAdd.decode(reader, reader.uint32());
          continue;
        }
        case 51: {
          if (tag !== 410) {
            break;
          }

          message.relationRemove = Change_RelationRemove.decode(reader, reader.uint32());
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.detailsSet = Change_DetailsSet.decode(reader, reader.uint32());
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.detailsUnset = Change_DetailsUnset.decode(reader, reader.uint32());
          continue;
        }
        case 105: {
          if (tag !== 842) {
            break;
          }

          message.objectTypeAdd = Change_ObjectTypeAdd.decode(reader, reader.uint32());
          continue;
        }
        case 106: {
          if (tag !== 850) {
            break;
          }

          message.objectTypeRemove = Change_ObjectTypeRemove.decode(reader, reader.uint32());
          continue;
        }
        case 107: {
          if (tag !== 858) {
            break;
          }

          message.storeKeySet = Change_StoreKeySet.decode(reader, reader.uint32());
          continue;
        }
        case 108: {
          if (tag !== 866) {
            break;
          }

          message.storeKeyUnset = Change_StoreKeyUnset.decode(reader, reader.uint32());
          continue;
        }
        case 109: {
          if (tag !== 874) {
            break;
          }

          message.storeSliceUpdate = Change_StoreSliceUpdate.decode(reader, reader.uint32());
          continue;
        }
        case 110: {
          if (tag !== 882) {
            break;
          }

          message.originalCreatedTimestampSet = Change_OriginalCreatedTimestampSet.decode(reader, reader.uint32());
          continue;
        }
        case 111: {
          if (tag !== 890) {
            break;
          }

          message.setFileInfo = Change_SetFileInfo.decode(reader, reader.uint32());
          continue;
        }
        case 112: {
          if (tag !== 898) {
            break;
          }

          message.notificationCreate = Change_NotificationCreate.decode(reader, reader.uint32());
          continue;
        }
        case 113: {
          if (tag !== 906) {
            break;
          }

          message.notificationUpdate = Change_NotificationUpdate.decode(reader, reader.uint32());
          continue;
        }
        case 114: {
          if (tag !== 914) {
            break;
          }

          message.deviceAdd = Change_DeviceAdd.decode(reader, reader.uint32());
          continue;
        }
        case 115: {
          if (tag !== 922) {
            break;
          }

          message.deviceUpdate = Change_DeviceUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_Content>, I>>(base?: I): Change_Content {
    return Change_Content.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_Content>, I>>(object: I): Change_Content {
    const message = createBaseChange_Content();
    message.blockCreate = (object.blockCreate !== undefined && object.blockCreate !== null)
      ? Change_BlockCreate.fromPartial(object.blockCreate)
      : undefined;
    message.blockUpdate = (object.blockUpdate !== undefined && object.blockUpdate !== null)
      ? Change_BlockUpdate.fromPartial(object.blockUpdate)
      : undefined;
    message.blockRemove = (object.blockRemove !== undefined && object.blockRemove !== null)
      ? Change_BlockRemove.fromPartial(object.blockRemove)
      : undefined;
    message.blockMove = (object.blockMove !== undefined && object.blockMove !== null)
      ? Change_BlockMove.fromPartial(object.blockMove)
      : undefined;
    message.blockDuplicate = (object.blockDuplicate !== undefined && object.blockDuplicate !== null)
      ? Change_BlockDuplicate.fromPartial(object.blockDuplicate)
      : undefined;
    message.relationAdd = (object.relationAdd !== undefined && object.relationAdd !== null)
      ? Change_RelationAdd.fromPartial(object.relationAdd)
      : undefined;
    message.relationRemove = (object.relationRemove !== undefined && object.relationRemove !== null)
      ? Change_RelationRemove.fromPartial(object.relationRemove)
      : undefined;
    message.detailsSet = (object.detailsSet !== undefined && object.detailsSet !== null)
      ? Change_DetailsSet.fromPartial(object.detailsSet)
      : undefined;
    message.detailsUnset = (object.detailsUnset !== undefined && object.detailsUnset !== null)
      ? Change_DetailsUnset.fromPartial(object.detailsUnset)
      : undefined;
    message.objectTypeAdd = (object.objectTypeAdd !== undefined && object.objectTypeAdd !== null)
      ? Change_ObjectTypeAdd.fromPartial(object.objectTypeAdd)
      : undefined;
    message.objectTypeRemove = (object.objectTypeRemove !== undefined && object.objectTypeRemove !== null)
      ? Change_ObjectTypeRemove.fromPartial(object.objectTypeRemove)
      : undefined;
    message.storeKeySet = (object.storeKeySet !== undefined && object.storeKeySet !== null)
      ? Change_StoreKeySet.fromPartial(object.storeKeySet)
      : undefined;
    message.storeKeyUnset = (object.storeKeyUnset !== undefined && object.storeKeyUnset !== null)
      ? Change_StoreKeyUnset.fromPartial(object.storeKeyUnset)
      : undefined;
    message.storeSliceUpdate = (object.storeSliceUpdate !== undefined && object.storeSliceUpdate !== null)
      ? Change_StoreSliceUpdate.fromPartial(object.storeSliceUpdate)
      : undefined;
    message.originalCreatedTimestampSet =
      (object.originalCreatedTimestampSet !== undefined && object.originalCreatedTimestampSet !== null)
        ? Change_OriginalCreatedTimestampSet.fromPartial(object.originalCreatedTimestampSet)
        : undefined;
    message.setFileInfo = (object.setFileInfo !== undefined && object.setFileInfo !== null)
      ? Change_SetFileInfo.fromPartial(object.setFileInfo)
      : undefined;
    message.notificationCreate = (object.notificationCreate !== undefined && object.notificationCreate !== null)
      ? Change_NotificationCreate.fromPartial(object.notificationCreate)
      : undefined;
    message.notificationUpdate = (object.notificationUpdate !== undefined && object.notificationUpdate !== null)
      ? Change_NotificationUpdate.fromPartial(object.notificationUpdate)
      : undefined;
    message.deviceAdd = (object.deviceAdd !== undefined && object.deviceAdd !== null)
      ? Change_DeviceAdd.fromPartial(object.deviceAdd)
      : undefined;
    message.deviceUpdate = (object.deviceUpdate !== undefined && object.deviceUpdate !== null)
      ? Change_DeviceUpdate.fromPartial(object.deviceUpdate)
      : undefined;
    return message;
  },
};

function createBaseChange_BlockCreate(): Change_BlockCreate {
  return { targetId: "", position: 0, blocks: [] };
}

export const Change_BlockCreate: MessageFns<Change_BlockCreate> = {
  encode(message: Change_BlockCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetId !== "") {
      writer.uint32(10).string(message.targetId);
    }
    if (message.position !== 0) {
      writer.uint32(16).int32(message.position);
    }
    for (const v of message.blocks) {
      Block.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_BlockCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_BlockCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.blocks.push(Block.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_BlockCreate>, I>>(base?: I): Change_BlockCreate {
    return Change_BlockCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_BlockCreate>, I>>(object: I): Change_BlockCreate {
    const message = createBaseChange_BlockCreate();
    message.targetId = object.targetId ?? "";
    message.position = object.position ?? 0;
    message.blocks = object.blocks?.map((e) => Block.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChange_BlockUpdate(): Change_BlockUpdate {
  return { events: [] };
}

export const Change_BlockUpdate: MessageFns<Change_BlockUpdate> = {
  encode(message: Change_BlockUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.events) {
      Event_Message.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_BlockUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_BlockUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.events.push(Event_Message.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_BlockUpdate>, I>>(base?: I): Change_BlockUpdate {
    return Change_BlockUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_BlockUpdate>, I>>(object: I): Change_BlockUpdate {
    const message = createBaseChange_BlockUpdate();
    message.events = object.events?.map((e) => Event_Message.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChange_BlockRemove(): Change_BlockRemove {
  return { ids: [] };
}

export const Change_BlockRemove: MessageFns<Change_BlockRemove> = {
  encode(message: Change_BlockRemove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_BlockRemove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_BlockRemove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_BlockRemove>, I>>(base?: I): Change_BlockRemove {
    return Change_BlockRemove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_BlockRemove>, I>>(object: I): Change_BlockRemove {
    const message = createBaseChange_BlockRemove();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_BlockMove(): Change_BlockMove {
  return { targetId: "", position: 0, ids: [] };
}

export const Change_BlockMove: MessageFns<Change_BlockMove> = {
  encode(message: Change_BlockMove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetId !== "") {
      writer.uint32(10).string(message.targetId);
    }
    if (message.position !== 0) {
      writer.uint32(16).int32(message.position);
    }
    for (const v of message.ids) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_BlockMove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_BlockMove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_BlockMove>, I>>(base?: I): Change_BlockMove {
    return Change_BlockMove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_BlockMove>, I>>(object: I): Change_BlockMove {
    const message = createBaseChange_BlockMove();
    message.targetId = object.targetId ?? "";
    message.position = object.position ?? 0;
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_BlockDuplicate(): Change_BlockDuplicate {
  return { targetId: "", position: 0, ids: [] };
}

export const Change_BlockDuplicate: MessageFns<Change_BlockDuplicate> = {
  encode(message: Change_BlockDuplicate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetId !== "") {
      writer.uint32(10).string(message.targetId);
    }
    if (message.position !== 0) {
      writer.uint32(16).int32(message.position);
    }
    for (const v of message.ids) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_BlockDuplicate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_BlockDuplicate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_BlockDuplicate>, I>>(base?: I): Change_BlockDuplicate {
    return Change_BlockDuplicate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_BlockDuplicate>, I>>(object: I): Change_BlockDuplicate {
    const message = createBaseChange_BlockDuplicate();
    message.targetId = object.targetId ?? "";
    message.position = object.position ?? 0;
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_DetailsSet(): Change_DetailsSet {
  return { key: "", value: undefined };
}

export const Change_DetailsSet: MessageFns<Change_DetailsSet> = {
  encode(message: Change_DetailsSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Value.encode(Value.wrap(message.value), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_DetailsSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_DetailsSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_DetailsSet>, I>>(base?: I): Change_DetailsSet {
    return Change_DetailsSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_DetailsSet>, I>>(object: I): Change_DetailsSet {
    const message = createBaseChange_DetailsSet();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseChange_DetailsUnset(): Change_DetailsUnset {
  return { key: "" };
}

export const Change_DetailsUnset: MessageFns<Change_DetailsUnset> = {
  encode(message: Change_DetailsUnset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_DetailsUnset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_DetailsUnset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_DetailsUnset>, I>>(base?: I): Change_DetailsUnset {
    return Change_DetailsUnset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_DetailsUnset>, I>>(object: I): Change_DetailsUnset {
    const message = createBaseChange_DetailsUnset();
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseChange_RelationAdd(): Change_RelationAdd {
  return { relationLinks: [] };
}

export const Change_RelationAdd: MessageFns<Change_RelationAdd> = {
  encode(message: Change_RelationAdd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.relationLinks) {
      RelationLink.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_RelationAdd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_RelationAdd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.relationLinks.push(RelationLink.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_RelationAdd>, I>>(base?: I): Change_RelationAdd {
    return Change_RelationAdd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_RelationAdd>, I>>(object: I): Change_RelationAdd {
    const message = createBaseChange_RelationAdd();
    message.relationLinks = object.relationLinks?.map((e) => RelationLink.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChange_RelationRemove(): Change_RelationRemove {
  return { relationKey: [] };
}

export const Change_RelationRemove: MessageFns<Change_RelationRemove> = {
  encode(message: Change_RelationRemove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.relationKey) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_RelationRemove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_RelationRemove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.relationKey.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_RelationRemove>, I>>(base?: I): Change_RelationRemove {
    return Change_RelationRemove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_RelationRemove>, I>>(object: I): Change_RelationRemove {
    const message = createBaseChange_RelationRemove();
    message.relationKey = object.relationKey?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_ObjectTypeAdd(): Change_ObjectTypeAdd {
  return { url: "", key: "" };
}

export const Change_ObjectTypeAdd: MessageFns<Change_ObjectTypeAdd> = {
  encode(message: Change_ObjectTypeAdd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_ObjectTypeAdd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_ObjectTypeAdd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_ObjectTypeAdd>, I>>(base?: I): Change_ObjectTypeAdd {
    return Change_ObjectTypeAdd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_ObjectTypeAdd>, I>>(object: I): Change_ObjectTypeAdd {
    const message = createBaseChange_ObjectTypeAdd();
    message.url = object.url ?? "";
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseChange_ObjectTypeRemove(): Change_ObjectTypeRemove {
  return { url: "", key: "" };
}

export const Change_ObjectTypeRemove: MessageFns<Change_ObjectTypeRemove> = {
  encode(message: Change_ObjectTypeRemove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_ObjectTypeRemove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_ObjectTypeRemove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_ObjectTypeRemove>, I>>(base?: I): Change_ObjectTypeRemove {
    return Change_ObjectTypeRemove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_ObjectTypeRemove>, I>>(object: I): Change_ObjectTypeRemove {
    const message = createBaseChange_ObjectTypeRemove();
    message.url = object.url ?? "";
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseChange_StoreKeySet(): Change_StoreKeySet {
  return { path: [], value: undefined };
}

export const Change_StoreKeySet: MessageFns<Change_StoreKeySet> = {
  encode(message: Change_StoreKeySet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.path) {
      writer.uint32(10).string(v!);
    }
    if (message.value !== undefined) {
      Value.encode(Value.wrap(message.value), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreKeySet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreKeySet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreKeySet>, I>>(base?: I): Change_StoreKeySet {
    return Change_StoreKeySet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreKeySet>, I>>(object: I): Change_StoreKeySet {
    const message = createBaseChange_StoreKeySet();
    message.path = object.path?.map((e) => e) || [];
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseChange_StoreKeyUnset(): Change_StoreKeyUnset {
  return { path: [] };
}

export const Change_StoreKeyUnset: MessageFns<Change_StoreKeyUnset> = {
  encode(message: Change_StoreKeyUnset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.path) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreKeyUnset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreKeyUnset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreKeyUnset>, I>>(base?: I): Change_StoreKeyUnset {
    return Change_StoreKeyUnset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreKeyUnset>, I>>(object: I): Change_StoreKeyUnset {
    const message = createBaseChange_StoreKeyUnset();
    message.path = object.path?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_StoreSliceUpdate(): Change_StoreSliceUpdate {
  return { key: "" };
}

export const Change_StoreSliceUpdate: MessageFns<Change_StoreSliceUpdate> = {
  encode(message: Change_StoreSliceUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.add !== undefined) {
      Change_StoreSliceUpdate_Add.encode(message.add, writer.uint32(18).fork()).join();
    }
    if (message.remove !== undefined) {
      Change_StoreSliceUpdate_Remove.encode(message.remove, writer.uint32(26).fork()).join();
    }
    if (message.move !== undefined) {
      Change_StoreSliceUpdate_Move.encode(message.move, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreSliceUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreSliceUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.add = Change_StoreSliceUpdate_Add.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.remove = Change_StoreSliceUpdate_Remove.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.move = Change_StoreSliceUpdate_Move.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreSliceUpdate>, I>>(base?: I): Change_StoreSliceUpdate {
    return Change_StoreSliceUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreSliceUpdate>, I>>(object: I): Change_StoreSliceUpdate {
    const message = createBaseChange_StoreSliceUpdate();
    message.key = object.key ?? "";
    message.add = (object.add !== undefined && object.add !== null)
      ? Change_StoreSliceUpdate_Add.fromPartial(object.add)
      : undefined;
    message.remove = (object.remove !== undefined && object.remove !== null)
      ? Change_StoreSliceUpdate_Remove.fromPartial(object.remove)
      : undefined;
    message.move = (object.move !== undefined && object.move !== null)
      ? Change_StoreSliceUpdate_Move.fromPartial(object.move)
      : undefined;
    return message;
  },
};

function createBaseChange_StoreSliceUpdate_Add(): Change_StoreSliceUpdate_Add {
  return { afterId: "", ids: [] };
}

export const Change_StoreSliceUpdate_Add: MessageFns<Change_StoreSliceUpdate_Add> = {
  encode(message: Change_StoreSliceUpdate_Add, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.afterId !== "") {
      writer.uint32(10).string(message.afterId);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreSliceUpdate_Add {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreSliceUpdate_Add();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.afterId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Add>, I>>(base?: I): Change_StoreSliceUpdate_Add {
    return Change_StoreSliceUpdate_Add.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Add>, I>>(object: I): Change_StoreSliceUpdate_Add {
    const message = createBaseChange_StoreSliceUpdate_Add();
    message.afterId = object.afterId ?? "";
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_StoreSliceUpdate_Remove(): Change_StoreSliceUpdate_Remove {
  return { ids: [] };
}

export const Change_StoreSliceUpdate_Remove: MessageFns<Change_StoreSliceUpdate_Remove> = {
  encode(message: Change_StoreSliceUpdate_Remove, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreSliceUpdate_Remove {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreSliceUpdate_Remove();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Remove>, I>>(base?: I): Change_StoreSliceUpdate_Remove {
    return Change_StoreSliceUpdate_Remove.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Remove>, I>>(
    object: I,
  ): Change_StoreSliceUpdate_Remove {
    const message = createBaseChange_StoreSliceUpdate_Remove();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_StoreSliceUpdate_Move(): Change_StoreSliceUpdate_Move {
  return { afterId: "", ids: [] };
}

export const Change_StoreSliceUpdate_Move: MessageFns<Change_StoreSliceUpdate_Move> = {
  encode(message: Change_StoreSliceUpdate_Move, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.afterId !== "") {
      writer.uint32(10).string(message.afterId);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_StoreSliceUpdate_Move {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_StoreSliceUpdate_Move();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.afterId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Move>, I>>(base?: I): Change_StoreSliceUpdate_Move {
    return Change_StoreSliceUpdate_Move.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_StoreSliceUpdate_Move>, I>>(object: I): Change_StoreSliceUpdate_Move {
    const message = createBaseChange_StoreSliceUpdate_Move();
    message.afterId = object.afterId ?? "";
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseChange_OriginalCreatedTimestampSet(): Change_OriginalCreatedTimestampSet {
  return { ts: 0 };
}

export const Change_OriginalCreatedTimestampSet: MessageFns<Change_OriginalCreatedTimestampSet> = {
  encode(message: Change_OriginalCreatedTimestampSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ts !== 0) {
      writer.uint32(8).int64(message.ts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_OriginalCreatedTimestampSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_OriginalCreatedTimestampSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ts = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_OriginalCreatedTimestampSet>, I>>(
    base?: I,
  ): Change_OriginalCreatedTimestampSet {
    return Change_OriginalCreatedTimestampSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_OriginalCreatedTimestampSet>, I>>(
    object: I,
  ): Change_OriginalCreatedTimestampSet {
    const message = createBaseChange_OriginalCreatedTimestampSet();
    message.ts = object.ts ?? 0;
    return message;
  },
};

function createBaseChange_SetFileInfo(): Change_SetFileInfo {
  return { fileInfo: undefined };
}

export const Change_SetFileInfo: MessageFns<Change_SetFileInfo> = {
  encode(message: Change_SetFileInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileInfo !== undefined) {
      FileInfo.encode(message.fileInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_SetFileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_SetFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileInfo = FileInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_SetFileInfo>, I>>(base?: I): Change_SetFileInfo {
    return Change_SetFileInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_SetFileInfo>, I>>(object: I): Change_SetFileInfo {
    const message = createBaseChange_SetFileInfo();
    message.fileInfo = (object.fileInfo !== undefined && object.fileInfo !== null)
      ? FileInfo.fromPartial(object.fileInfo)
      : undefined;
    return message;
  },
};

function createBaseChange_NotificationCreate(): Change_NotificationCreate {
  return { notification: undefined };
}

export const Change_NotificationCreate: MessageFns<Change_NotificationCreate> = {
  encode(message: Change_NotificationCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.notification !== undefined) {
      Notification.encode(message.notification, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_NotificationCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_NotificationCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.notification = Notification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_NotificationCreate>, I>>(base?: I): Change_NotificationCreate {
    return Change_NotificationCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_NotificationCreate>, I>>(object: I): Change_NotificationCreate {
    const message = createBaseChange_NotificationCreate();
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? Notification.fromPartial(object.notification)
      : undefined;
    return message;
  },
};

function createBaseChange_NotificationUpdate(): Change_NotificationUpdate {
  return { id: "", status: 0 };
}

export const Change_NotificationUpdate: MessageFns<Change_NotificationUpdate> = {
  encode(message: Change_NotificationUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_NotificationUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_NotificationUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_NotificationUpdate>, I>>(base?: I): Change_NotificationUpdate {
    return Change_NotificationUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_NotificationUpdate>, I>>(object: I): Change_NotificationUpdate {
    const message = createBaseChange_NotificationUpdate();
    message.id = object.id ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseChange_DeviceAdd(): Change_DeviceAdd {
  return { device: undefined };
}

export const Change_DeviceAdd: MessageFns<Change_DeviceAdd> = {
  encode(message: Change_DeviceAdd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.device !== undefined) {
      DeviceInfo.encode(message.device, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_DeviceAdd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_DeviceAdd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.device = DeviceInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_DeviceAdd>, I>>(base?: I): Change_DeviceAdd {
    return Change_DeviceAdd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_DeviceAdd>, I>>(object: I): Change_DeviceAdd {
    const message = createBaseChange_DeviceAdd();
    message.device = (object.device !== undefined && object.device !== null)
      ? DeviceInfo.fromPartial(object.device)
      : undefined;
    return message;
  },
};

function createBaseChange_DeviceUpdate(): Change_DeviceUpdate {
  return { id: "", name: "" };
}

export const Change_DeviceUpdate: MessageFns<Change_DeviceUpdate> = {
  encode(message: Change_DeviceUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Change_DeviceUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChange_DeviceUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Change_DeviceUpdate>, I>>(base?: I): Change_DeviceUpdate {
    return Change_DeviceUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Change_DeviceUpdate>, I>>(object: I): Change_DeviceUpdate {
    const message = createBaseChange_DeviceUpdate();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseChangeNoSnapshot(): ChangeNoSnapshot {
  return { content: [], fileKeys: [], timestamp: 0, version: 0, changeType: 0 };
}

export const ChangeNoSnapshot: MessageFns<ChangeNoSnapshot> = {
  encode(message: ChangeNoSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.content) {
      Change_Content.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.fileKeys) {
      Change_FileKeys.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(56).int64(message.timestamp);
    }
    if (message.version !== 0) {
      writer.uint32(64).uint32(message.version);
    }
    if (message.changeType !== 0) {
      writer.uint32(72).uint32(message.changeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeNoSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeNoSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content.push(Change_Content.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileKeys.push(Change_FileKeys.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.changeType = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChangeNoSnapshot>, I>>(base?: I): ChangeNoSnapshot {
    return ChangeNoSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeNoSnapshot>, I>>(object: I): ChangeNoSnapshot {
    const message = createBaseChangeNoSnapshot();
    message.content = object.content?.map((e) => Change_Content.fromPartial(e)) || [];
    message.fileKeys = object.fileKeys?.map((e) => Change_FileKeys.fromPartial(e)) || [];
    message.timestamp = object.timestamp ?? 0;
    message.version = object.version ?? 0;
    message.changeType = object.changeType ?? 0;
    return message;
  },
};

function createBaseStoreChange(): StoreChange {
  return { changeSet: [] };
}

export const StoreChange: MessageFns<StoreChange> = {
  encode(message: StoreChange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.changeSet) {
      StoreChangeContent.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreChange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreChange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.changeSet.push(StoreChangeContent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StoreChange>, I>>(base?: I): StoreChange {
    return StoreChange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreChange>, I>>(object: I): StoreChange {
    const message = createBaseStoreChange();
    message.changeSet = object.changeSet?.map((e) => StoreChangeContent.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStoreChangeContent(): StoreChangeContent {
  return {};
}

export const StoreChangeContent: MessageFns<StoreChangeContent> = {
  encode(message: StoreChangeContent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.create !== undefined) {
      DocumentCreate.encode(message.create, writer.uint32(10).fork()).join();
    }
    if (message.modify !== undefined) {
      DocumentModify.encode(message.modify, writer.uint32(18).fork()).join();
    }
    if (message.delete !== undefined) {
      DocumentDelete.encode(message.delete, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoreChangeContent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreChangeContent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.create = DocumentCreate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modify = DocumentModify.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.delete = DocumentDelete.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StoreChangeContent>, I>>(base?: I): StoreChangeContent {
    return StoreChangeContent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreChangeContent>, I>>(object: I): StoreChangeContent {
    const message = createBaseStoreChangeContent();
    message.create = (object.create !== undefined && object.create !== null)
      ? DocumentCreate.fromPartial(object.create)
      : undefined;
    message.modify = (object.modify !== undefined && object.modify !== null)
      ? DocumentModify.fromPartial(object.modify)
      : undefined;
    message.delete = (object.delete !== undefined && object.delete !== null)
      ? DocumentDelete.fromPartial(object.delete)
      : undefined;
    return message;
  },
};

function createBaseDocumentCreate(): DocumentCreate {
  return { collection: "", documentId: "", value: "" };
}

export const DocumentCreate: MessageFns<DocumentCreate> = {
  encode(message: DocumentCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.collection !== "") {
      writer.uint32(10).string(message.collection);
    }
    if (message.documentId !== "") {
      writer.uint32(18).string(message.documentId);
    }
    if (message.value !== "") {
      writer.uint32(26).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.collection = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.documentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DocumentCreate>, I>>(base?: I): DocumentCreate {
    return DocumentCreate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentCreate>, I>>(object: I): DocumentCreate {
    const message = createBaseDocumentCreate();
    message.collection = object.collection ?? "";
    message.documentId = object.documentId ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDocumentModify(): DocumentModify {
  return { collection: "", documentId: "", keys: [] };
}

export const DocumentModify: MessageFns<DocumentModify> = {
  encode(message: DocumentModify, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.collection !== "") {
      writer.uint32(10).string(message.collection);
    }
    if (message.documentId !== "") {
      writer.uint32(18).string(message.documentId);
    }
    for (const v of message.keys) {
      KeyModify.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentModify {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentModify();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.collection = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.documentId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keys.push(KeyModify.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DocumentModify>, I>>(base?: I): DocumentModify {
    return DocumentModify.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentModify>, I>>(object: I): DocumentModify {
    const message = createBaseDocumentModify();
    message.collection = object.collection ?? "";
    message.documentId = object.documentId ?? "";
    message.keys = object.keys?.map((e) => KeyModify.fromPartial(e)) || [];
    return message;
  },
};

function createBaseKeyModify(): KeyModify {
  return { keyPath: [], modifyOp: 0, modifyValue: "" };
}

export const KeyModify: MessageFns<KeyModify> = {
  encode(message: KeyModify, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.keyPath) {
      writer.uint32(10).string(v!);
    }
    if (message.modifyOp !== 0) {
      writer.uint32(24).int32(message.modifyOp);
    }
    if (message.modifyValue !== "") {
      writer.uint32(34).string(message.modifyValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyModify {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyModify();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyPath.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.modifyOp = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.modifyValue = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<KeyModify>, I>>(base?: I): KeyModify {
    return KeyModify.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyModify>, I>>(object: I): KeyModify {
    const message = createBaseKeyModify();
    message.keyPath = object.keyPath?.map((e) => e) || [];
    message.modifyOp = object.modifyOp ?? 0;
    message.modifyValue = object.modifyValue ?? "";
    return message;
  },
};

function createBaseDocumentDelete(): DocumentDelete {
  return { collection: "", documentId: "" };
}

export const DocumentDelete: MessageFns<DocumentDelete> = {
  encode(message: DocumentDelete, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.collection !== "") {
      writer.uint32(10).string(message.collection);
    }
    if (message.documentId !== "") {
      writer.uint32(18).string(message.documentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DocumentDelete {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocumentDelete();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.collection = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.documentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DocumentDelete>, I>>(base?: I): DocumentDelete {
    return DocumentDelete.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DocumentDelete>, I>>(object: I): DocumentDelete {
    const message = createBaseDocumentDelete();
    message.collection = object.collection ?? "";
    message.documentId = object.documentId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
