// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.5
// source: pb/protos/snapshot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  Block_Content_Widget_Layout,
  block_Content_Widget_LayoutFromJSON,
  block_Content_Widget_LayoutToJSON,
  SmartBlockType,
  smartBlockTypeFromJSON,
  smartBlockTypeToJSON,
} from "../../pkg/lib/pb/model/protos/models";
import { Change_Snapshot } from "./changes";

export const protobufPackage = "anytype";

export interface SnapshotWithType {
  sbType: SmartBlockType;
  snapshot: Change_Snapshot | undefined;
}

export interface Profile {
  name: string;
  avatar: string;
  address: string;
  spaceDashboardId: string;
  profileId: string;
  analyticsId: string;
  /** deprecated */
  startingPage: string;
  widgets: WidgetBlock[];
}

export interface WidgetBlock {
  layout: Block_Content_Widget_Layout;
  targetObjectId: string;
  objectLimit: number;
}

function createBaseSnapshotWithType(): SnapshotWithType {
  return { sbType: 0, snapshot: undefined };
}

export const SnapshotWithType: MessageFns<SnapshotWithType> = {
  encode(message: SnapshotWithType, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sbType !== 0) {
      writer.uint32(8).int32(message.sbType);
    }
    if (message.snapshot !== undefined) {
      Change_Snapshot.encode(message.snapshot, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SnapshotWithType {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSnapshotWithType();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sbType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.snapshot = Change_Snapshot.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SnapshotWithType {
    return {
      sbType: isSet(object.sbType) ? smartBlockTypeFromJSON(object.sbType) : 0,
      snapshot: isSet(object.snapshot) ? Change_Snapshot.fromJSON(object.snapshot) : undefined,
    };
  },

  toJSON(message: SnapshotWithType): unknown {
    const obj: any = {};
    if (message.sbType !== 0) {
      obj.sbType = smartBlockTypeToJSON(message.sbType);
    }
    if (message.snapshot !== undefined) {
      obj.snapshot = Change_Snapshot.toJSON(message.snapshot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SnapshotWithType>, I>>(base?: I): SnapshotWithType {
    return SnapshotWithType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SnapshotWithType>, I>>(object: I): SnapshotWithType {
    const message = createBaseSnapshotWithType();
    message.sbType = object.sbType ?? 0;
    message.snapshot = (object.snapshot !== undefined && object.snapshot !== null)
      ? Change_Snapshot.fromPartial(object.snapshot)
      : undefined;
    return message;
  },
};

function createBaseProfile(): Profile {
  return {
    name: "",
    avatar: "",
    address: "",
    spaceDashboardId: "",
    profileId: "",
    analyticsId: "",
    startingPage: "",
    widgets: [],
  };
}

export const Profile: MessageFns<Profile> = {
  encode(message: Profile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(18).string(message.avatar);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.spaceDashboardId !== "") {
      writer.uint32(42).string(message.spaceDashboardId);
    }
    if (message.profileId !== "") {
      writer.uint32(50).string(message.profileId);
    }
    if (message.analyticsId !== "") {
      writer.uint32(58).string(message.analyticsId);
    }
    if (message.startingPage !== "") {
      writer.uint32(66).string(message.startingPage);
    }
    for (const v of message.widgets) {
      WidgetBlock.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Profile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.spaceDashboardId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.profileId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.analyticsId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.startingPage = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.widgets.push(WidgetBlock.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Profile {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      spaceDashboardId: isSet(object.spaceDashboardId) ? globalThis.String(object.spaceDashboardId) : "",
      profileId: isSet(object.profileId) ? globalThis.String(object.profileId) : "",
      analyticsId: isSet(object.analyticsId) ? globalThis.String(object.analyticsId) : "",
      startingPage: isSet(object.startingPage) ? globalThis.String(object.startingPage) : "",
      widgets: globalThis.Array.isArray(object?.widgets) ? object.widgets.map((e: any) => WidgetBlock.fromJSON(e)) : [],
    };
  },

  toJSON(message: Profile): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.spaceDashboardId !== "") {
      obj.spaceDashboardId = message.spaceDashboardId;
    }
    if (message.profileId !== "") {
      obj.profileId = message.profileId;
    }
    if (message.analyticsId !== "") {
      obj.analyticsId = message.analyticsId;
    }
    if (message.startingPage !== "") {
      obj.startingPage = message.startingPage;
    }
    if (message.widgets?.length) {
      obj.widgets = message.widgets.map((e) => WidgetBlock.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Profile>, I>>(base?: I): Profile {
    return Profile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Profile>, I>>(object: I): Profile {
    const message = createBaseProfile();
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.address = object.address ?? "";
    message.spaceDashboardId = object.spaceDashboardId ?? "";
    message.profileId = object.profileId ?? "";
    message.analyticsId = object.analyticsId ?? "";
    message.startingPage = object.startingPage ?? "";
    message.widgets = object.widgets?.map((e) => WidgetBlock.fromPartial(e)) || [];
    return message;
  },
};

function createBaseWidgetBlock(): WidgetBlock {
  return { layout: 0, targetObjectId: "", objectLimit: 0 };
}

export const WidgetBlock: MessageFns<WidgetBlock> = {
  encode(message: WidgetBlock, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layout !== 0) {
      writer.uint32(8).int32(message.layout);
    }
    if (message.targetObjectId !== "") {
      writer.uint32(18).string(message.targetObjectId);
    }
    if (message.objectLimit !== 0) {
      writer.uint32(24).int32(message.objectLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WidgetBlock {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWidgetBlock();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layout = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetObjectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.objectLimit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WidgetBlock {
    return {
      layout: isSet(object.layout) ? block_Content_Widget_LayoutFromJSON(object.layout) : 0,
      targetObjectId: isSet(object.targetObjectId) ? globalThis.String(object.targetObjectId) : "",
      objectLimit: isSet(object.objectLimit) ? globalThis.Number(object.objectLimit) : 0,
    };
  },

  toJSON(message: WidgetBlock): unknown {
    const obj: any = {};
    if (message.layout !== 0) {
      obj.layout = block_Content_Widget_LayoutToJSON(message.layout);
    }
    if (message.targetObjectId !== "") {
      obj.targetObjectId = message.targetObjectId;
    }
    if (message.objectLimit !== 0) {
      obj.objectLimit = Math.round(message.objectLimit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WidgetBlock>, I>>(base?: I): WidgetBlock {
    return WidgetBlock.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WidgetBlock>, I>>(object: I): WidgetBlock {
    const message = createBaseWidgetBlock();
    message.layout = object.layout ?? 0;
    message.targetObjectId = object.targetObjectId ?? "";
    message.objectLimit = object.objectLimit ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
