import { registerIcon } from '../registry';
import Api from './api';
import Chat from './chat';
import Drive from './drive';
import Home from './home';
import Language from './language';
import Location from './location';
import Membership from './membership';
import More from './more';
import Offline from './offline';
import Overview from './overview';
import Personal from './personal';
import Phrase from './phrase';
import Pin from './pin';
import PushOff from './pushOff';
import PushOn from './pushOn';
import Relation from './relation';
import Remove from './remove';
import SidebarView from './sidebarView';
import Sites from './sites';
import Spaces from './spaces';
import Storage from './storage';
import Type from './type';

import './space';

registerIcon('settings/api', Api);
registerIcon('settings/chat', Chat);
registerIcon('settings/drive', Drive);
registerIcon('settings/home', Home);
registerIcon('settings/language', Language);
registerIcon('settings/location', Location);
registerIcon('settings/membership', Membership);
registerIcon('settings/more', More);
registerIcon('settings/offline', Offline);
registerIcon('settings/overview', Overview);
registerIcon('settings/personal', Personal);
registerIcon('settings/phrase', Phrase);
registerIcon('settings/pin', Pin);
registerIcon('settings/pushOff', PushOff);
registerIcon('settings/pushOn', PushOn);
registerIcon('settings/relation', Relation);
registerIcon('settings/remove', Remove);
registerIcon('settings/sidebarView', SidebarView);
registerIcon('settings/sites', Sites);
registerIcon('settings/spaces', Spaces);
registerIcon('settings/storage', Storage);
registerIcon('settings/type', Type);
