import { registerIcon } from '../registry';
import Button from './button';
import Calendar from './calendar';
import Chevron from './chevron';
import ChevronDown from './chevronDown';
import DoubleChevron from './doubleChevron';
import ChevronLeft from './chevronLeft';
import ChevronUp from './chevronUp';
import Filter from './filter';
import Forward from './forward';
import Gallery from './gallery';
import Item from './item';
import MenuDirection from './menuDirection';
import Nav from './nav';
import Pager from './pager';
import PagerEnd from './pagerEnd';
import Select from './select';
import SelectBig from './selectBig';
import ShowAll from './showAll';
import Small from './small';
import SmallMedium from './smallMedium';
import Template from './template';
import Usecase from './usecase';
import Widget from './widget';

registerIcon('arrow/button', Button);
registerIcon('arrow/calendar', Calendar);
registerIcon('arrow/chevron', Chevron);
registerIcon('arrow/chevronDown', ChevronDown);
registerIcon('arrow/doubleChevron', DoubleChevron);
registerIcon('arrow/chevronLeft', ChevronLeft);
registerIcon('arrow/chevronUp', ChevronUp);
registerIcon('arrow/filter', Filter);
registerIcon('arrow/forward', Forward);
registerIcon('arrow/gallery', Gallery);
registerIcon('arrow/item', Item);
registerIcon('arrow/menuDirection', MenuDirection);
registerIcon('arrow/nav', Nav);
registerIcon('arrow/pager', Pager);
registerIcon('arrow/pagerEnd', PagerEnd);
registerIcon('arrow/select', Select);
registerIcon('arrow/selectBig', SelectBig);
registerIcon('arrow/showAll', ShowAll);
registerIcon('arrow/small', Small);
registerIcon('arrow/smallMedium', SmallMedium);
registerIcon('arrow/template', Template);
registerIcon('arrow/usecase', Usecase);
registerIcon('arrow/widget', Widget);
