// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.5
// source: pkg/lib/pb/model/protos/localstore.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../../../../google/protobuf/struct";
import { Relation } from "./models";

export const protobufPackage = "anytype.model";

export interface ObjectInfo {
  id: string;
  /** DEPRECATED */
  objectTypeUrls: string[];
  details:
    | { [key: string]: any }
    | undefined;
  /** DEPRECATED */
  relations: Relation[];
  snippet: string;
  /** DEPRECATED */
  hasInboundLinks: boolean;
}

export interface ObjectDetails {
  details: { [key: string]: any } | undefined;
}

export interface ObjectLinks {
  inboundIDs: string[];
  outboundIDs: string[];
}

export interface ObjectLinksInfo {
  inbound: ObjectInfo[];
  outbound: ObjectInfo[];
}

export interface ObjectInfoWithLinks {
  id: string;
  info: ObjectInfo | undefined;
  links: ObjectLinksInfo | undefined;
}

export interface ObjectInfoWithOutboundLinks {
  id: string;
  info: ObjectInfo | undefined;
  outboundLinks: ObjectInfo[];
}

export interface ObjectInfoWithOutboundLinksIDs {
  id: string;
  info: ObjectInfo | undefined;
  outboundLinks: string[];
}

export interface ObjectStoreChecksums {
  bundledObjectTypes: string;
  bundledRelations: string;
  bundledLayouts: string;
  /** increased in order to trigger all objects reindex */
  objectsForceReindexCounter: number;
  /** increased in order to fully reindex all objects */
  filesForceReindexCounter: number;
  /** increased in order to remove indexes and reindex everything. Automatically triggers objects and files reindex(one time only) */
  idxRebuildCounter: number;
  /** DEPRECATED increased in order to perform fulltext indexing for all type of objects (useful when we change fulltext config) */
  fulltextRebuild: number;
  /** DEPRECATED remove all the fulltext indexes and add to reindex queue after */
  fulltextErase: number;
  bundledTemplates: string;
  /** anytypeProfile and maybe some others in the feature */
  bundledObjects: number;
  filestoreKeysForceReindexCounter: number;
  areOldFilesRemoved: boolean;
  /** DEPRECATED */
  areDeletedObjectsReindexed: boolean;
  linksErase: number;
  marketplaceForceReindexCounter: number;
  reindexDeletedObjects: number;
  reindexParticipants: number;
  reindexChats: number;
}

function createBaseObjectInfo(): ObjectInfo {
  return { id: "", objectTypeUrls: [], details: undefined, relations: [], snippet: "", hasInboundLinks: false };
}

export const ObjectInfo: MessageFns<ObjectInfo> = {
  encode(message: ObjectInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.objectTypeUrls) {
      writer.uint32(18).string(v!);
    }
    if (message.details !== undefined) {
      Struct.encode(Struct.wrap(message.details), writer.uint32(26).fork()).join();
    }
    for (const v of message.relations) {
      Relation.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.snippet !== "") {
      writer.uint32(42).string(message.snippet);
    }
    if (message.hasInboundLinks !== false) {
      writer.uint32(48).bool(message.hasInboundLinks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectTypeUrls.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.details = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.relations.push(Relation.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.hasInboundLinks = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      objectTypeUrls: globalThis.Array.isArray(object?.objectTypeUrls)
        ? object.objectTypeUrls.map((e: any) => globalThis.String(e))
        : [],
      details: isObject(object.details) ? object.details : undefined,
      relations: globalThis.Array.isArray(object?.relations)
        ? object.relations.map((e: any) => Relation.fromJSON(e))
        : [],
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
      hasInboundLinks: isSet(object.hasInboundLinks) ? globalThis.Boolean(object.hasInboundLinks) : false,
    };
  },

  toJSON(message: ObjectInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.objectTypeUrls?.length) {
      obj.objectTypeUrls = message.objectTypeUrls;
    }
    if (message.details !== undefined) {
      obj.details = message.details;
    }
    if (message.relations?.length) {
      obj.relations = message.relations.map((e) => Relation.toJSON(e));
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    if (message.hasInboundLinks !== false) {
      obj.hasInboundLinks = message.hasInboundLinks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectInfo>, I>>(base?: I): ObjectInfo {
    return ObjectInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectInfo>, I>>(object: I): ObjectInfo {
    const message = createBaseObjectInfo();
    message.id = object.id ?? "";
    message.objectTypeUrls = object.objectTypeUrls?.map((e) => e) || [];
    message.details = object.details ?? undefined;
    message.relations = object.relations?.map((e) => Relation.fromPartial(e)) || [];
    message.snippet = object.snippet ?? "";
    message.hasInboundLinks = object.hasInboundLinks ?? false;
    return message;
  },
};

function createBaseObjectDetails(): ObjectDetails {
  return { details: undefined };
}

export const ObjectDetails: MessageFns<ObjectDetails> = {
  encode(message: ObjectDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.details !== undefined) {
      Struct.encode(Struct.wrap(message.details), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.details = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectDetails {
    return { details: isObject(object.details) ? object.details : undefined };
  },

  toJSON(message: ObjectDetails): unknown {
    const obj: any = {};
    if (message.details !== undefined) {
      obj.details = message.details;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectDetails>, I>>(base?: I): ObjectDetails {
    return ObjectDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectDetails>, I>>(object: I): ObjectDetails {
    const message = createBaseObjectDetails();
    message.details = object.details ?? undefined;
    return message;
  },
};

function createBaseObjectLinks(): ObjectLinks {
  return { inboundIDs: [], outboundIDs: [] };
}

export const ObjectLinks: MessageFns<ObjectLinks> = {
  encode(message: ObjectLinks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.inboundIDs) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.outboundIDs) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectLinks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectLinks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inboundIDs.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outboundIDs.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectLinks {
    return {
      inboundIDs: globalThis.Array.isArray(object?.inboundIDs)
        ? object.inboundIDs.map((e: any) => globalThis.String(e))
        : [],
      outboundIDs: globalThis.Array.isArray(object?.outboundIDs)
        ? object.outboundIDs.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ObjectLinks): unknown {
    const obj: any = {};
    if (message.inboundIDs?.length) {
      obj.inboundIDs = message.inboundIDs;
    }
    if (message.outboundIDs?.length) {
      obj.outboundIDs = message.outboundIDs;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectLinks>, I>>(base?: I): ObjectLinks {
    return ObjectLinks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectLinks>, I>>(object: I): ObjectLinks {
    const message = createBaseObjectLinks();
    message.inboundIDs = object.inboundIDs?.map((e) => e) || [];
    message.outboundIDs = object.outboundIDs?.map((e) => e) || [];
    return message;
  },
};

function createBaseObjectLinksInfo(): ObjectLinksInfo {
  return { inbound: [], outbound: [] };
}

export const ObjectLinksInfo: MessageFns<ObjectLinksInfo> = {
  encode(message: ObjectLinksInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.inbound) {
      ObjectInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.outbound) {
      ObjectInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectLinksInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectLinksInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inbound.push(ObjectInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outbound.push(ObjectInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectLinksInfo {
    return {
      inbound: globalThis.Array.isArray(object?.inbound) ? object.inbound.map((e: any) => ObjectInfo.fromJSON(e)) : [],
      outbound: globalThis.Array.isArray(object?.outbound)
        ? object.outbound.map((e: any) => ObjectInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ObjectLinksInfo): unknown {
    const obj: any = {};
    if (message.inbound?.length) {
      obj.inbound = message.inbound.map((e) => ObjectInfo.toJSON(e));
    }
    if (message.outbound?.length) {
      obj.outbound = message.outbound.map((e) => ObjectInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectLinksInfo>, I>>(base?: I): ObjectLinksInfo {
    return ObjectLinksInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectLinksInfo>, I>>(object: I): ObjectLinksInfo {
    const message = createBaseObjectLinksInfo();
    message.inbound = object.inbound?.map((e) => ObjectInfo.fromPartial(e)) || [];
    message.outbound = object.outbound?.map((e) => ObjectInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseObjectInfoWithLinks(): ObjectInfoWithLinks {
  return { id: "", info: undefined, links: undefined };
}

export const ObjectInfoWithLinks: MessageFns<ObjectInfoWithLinks> = {
  encode(message: ObjectInfoWithLinks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.info !== undefined) {
      ObjectInfo.encode(message.info, writer.uint32(18).fork()).join();
    }
    if (message.links !== undefined) {
      ObjectLinksInfo.encode(message.links, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectInfoWithLinks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectInfoWithLinks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.info = ObjectInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.links = ObjectLinksInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectInfoWithLinks {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      info: isSet(object.info) ? ObjectInfo.fromJSON(object.info) : undefined,
      links: isSet(object.links) ? ObjectLinksInfo.fromJSON(object.links) : undefined,
    };
  },

  toJSON(message: ObjectInfoWithLinks): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.info !== undefined) {
      obj.info = ObjectInfo.toJSON(message.info);
    }
    if (message.links !== undefined) {
      obj.links = ObjectLinksInfo.toJSON(message.links);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectInfoWithLinks>, I>>(base?: I): ObjectInfoWithLinks {
    return ObjectInfoWithLinks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectInfoWithLinks>, I>>(object: I): ObjectInfoWithLinks {
    const message = createBaseObjectInfoWithLinks();
    message.id = object.id ?? "";
    message.info = (object.info !== undefined && object.info !== null)
      ? ObjectInfo.fromPartial(object.info)
      : undefined;
    message.links = (object.links !== undefined && object.links !== null)
      ? ObjectLinksInfo.fromPartial(object.links)
      : undefined;
    return message;
  },
};

function createBaseObjectInfoWithOutboundLinks(): ObjectInfoWithOutboundLinks {
  return { id: "", info: undefined, outboundLinks: [] };
}

export const ObjectInfoWithOutboundLinks: MessageFns<ObjectInfoWithOutboundLinks> = {
  encode(message: ObjectInfoWithOutboundLinks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.info !== undefined) {
      ObjectInfo.encode(message.info, writer.uint32(18).fork()).join();
    }
    for (const v of message.outboundLinks) {
      ObjectInfo.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectInfoWithOutboundLinks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectInfoWithOutboundLinks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.info = ObjectInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outboundLinks.push(ObjectInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectInfoWithOutboundLinks {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      info: isSet(object.info) ? ObjectInfo.fromJSON(object.info) : undefined,
      outboundLinks: globalThis.Array.isArray(object?.outboundLinks)
        ? object.outboundLinks.map((e: any) => ObjectInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ObjectInfoWithOutboundLinks): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.info !== undefined) {
      obj.info = ObjectInfo.toJSON(message.info);
    }
    if (message.outboundLinks?.length) {
      obj.outboundLinks = message.outboundLinks.map((e) => ObjectInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectInfoWithOutboundLinks>, I>>(base?: I): ObjectInfoWithOutboundLinks {
    return ObjectInfoWithOutboundLinks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectInfoWithOutboundLinks>, I>>(object: I): ObjectInfoWithOutboundLinks {
    const message = createBaseObjectInfoWithOutboundLinks();
    message.id = object.id ?? "";
    message.info = (object.info !== undefined && object.info !== null)
      ? ObjectInfo.fromPartial(object.info)
      : undefined;
    message.outboundLinks = object.outboundLinks?.map((e) => ObjectInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseObjectInfoWithOutboundLinksIDs(): ObjectInfoWithOutboundLinksIDs {
  return { id: "", info: undefined, outboundLinks: [] };
}

export const ObjectInfoWithOutboundLinksIDs: MessageFns<ObjectInfoWithOutboundLinksIDs> = {
  encode(message: ObjectInfoWithOutboundLinksIDs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.info !== undefined) {
      ObjectInfo.encode(message.info, writer.uint32(18).fork()).join();
    }
    for (const v of message.outboundLinks) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectInfoWithOutboundLinksIDs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectInfoWithOutboundLinksIDs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.info = ObjectInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outboundLinks.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectInfoWithOutboundLinksIDs {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      info: isSet(object.info) ? ObjectInfo.fromJSON(object.info) : undefined,
      outboundLinks: globalThis.Array.isArray(object?.outboundLinks)
        ? object.outboundLinks.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ObjectInfoWithOutboundLinksIDs): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.info !== undefined) {
      obj.info = ObjectInfo.toJSON(message.info);
    }
    if (message.outboundLinks?.length) {
      obj.outboundLinks = message.outboundLinks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectInfoWithOutboundLinksIDs>, I>>(base?: I): ObjectInfoWithOutboundLinksIDs {
    return ObjectInfoWithOutboundLinksIDs.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectInfoWithOutboundLinksIDs>, I>>(
    object: I,
  ): ObjectInfoWithOutboundLinksIDs {
    const message = createBaseObjectInfoWithOutboundLinksIDs();
    message.id = object.id ?? "";
    message.info = (object.info !== undefined && object.info !== null)
      ? ObjectInfo.fromPartial(object.info)
      : undefined;
    message.outboundLinks = object.outboundLinks?.map((e) => e) || [];
    return message;
  },
};

function createBaseObjectStoreChecksums(): ObjectStoreChecksums {
  return {
    bundledObjectTypes: "",
    bundledRelations: "",
    bundledLayouts: "",
    objectsForceReindexCounter: 0,
    filesForceReindexCounter: 0,
    idxRebuildCounter: 0,
    fulltextRebuild: 0,
    fulltextErase: 0,
    bundledTemplates: "",
    bundledObjects: 0,
    filestoreKeysForceReindexCounter: 0,
    areOldFilesRemoved: false,
    areDeletedObjectsReindexed: false,
    linksErase: 0,
    marketplaceForceReindexCounter: 0,
    reindexDeletedObjects: 0,
    reindexParticipants: 0,
    reindexChats: 0,
  };
}

export const ObjectStoreChecksums: MessageFns<ObjectStoreChecksums> = {
  encode(message: ObjectStoreChecksums, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bundledObjectTypes !== "") {
      writer.uint32(10).string(message.bundledObjectTypes);
    }
    if (message.bundledRelations !== "") {
      writer.uint32(18).string(message.bundledRelations);
    }
    if (message.bundledLayouts !== "") {
      writer.uint32(26).string(message.bundledLayouts);
    }
    if (message.objectsForceReindexCounter !== 0) {
      writer.uint32(32).int32(message.objectsForceReindexCounter);
    }
    if (message.filesForceReindexCounter !== 0) {
      writer.uint32(40).int32(message.filesForceReindexCounter);
    }
    if (message.idxRebuildCounter !== 0) {
      writer.uint32(48).int32(message.idxRebuildCounter);
    }
    if (message.fulltextRebuild !== 0) {
      writer.uint32(56).int32(message.fulltextRebuild);
    }
    if (message.fulltextErase !== 0) {
      writer.uint32(88).int32(message.fulltextErase);
    }
    if (message.bundledTemplates !== "") {
      writer.uint32(66).string(message.bundledTemplates);
    }
    if (message.bundledObjects !== 0) {
      writer.uint32(72).int32(message.bundledObjects);
    }
    if (message.filestoreKeysForceReindexCounter !== 0) {
      writer.uint32(80).int32(message.filestoreKeysForceReindexCounter);
    }
    if (message.areOldFilesRemoved !== false) {
      writer.uint32(96).bool(message.areOldFilesRemoved);
    }
    if (message.areDeletedObjectsReindexed !== false) {
      writer.uint32(104).bool(message.areDeletedObjectsReindexed);
    }
    if (message.linksErase !== 0) {
      writer.uint32(112).int32(message.linksErase);
    }
    if (message.marketplaceForceReindexCounter !== 0) {
      writer.uint32(120).int32(message.marketplaceForceReindexCounter);
    }
    if (message.reindexDeletedObjects !== 0) {
      writer.uint32(128).int32(message.reindexDeletedObjects);
    }
    if (message.reindexParticipants !== 0) {
      writer.uint32(136).int32(message.reindexParticipants);
    }
    if (message.reindexChats !== 0) {
      writer.uint32(144).int32(message.reindexChats);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectStoreChecksums {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectStoreChecksums();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bundledObjectTypes = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bundledRelations = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bundledLayouts = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.objectsForceReindexCounter = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.filesForceReindexCounter = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.idxRebuildCounter = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fulltextRebuild = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.fulltextErase = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bundledTemplates = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.bundledObjects = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.filestoreKeysForceReindexCounter = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.areOldFilesRemoved = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.areDeletedObjectsReindexed = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.linksErase = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.marketplaceForceReindexCounter = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.reindexDeletedObjects = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.reindexParticipants = reader.int32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.reindexChats = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectStoreChecksums {
    return {
      bundledObjectTypes: isSet(object.bundledObjectTypes) ? globalThis.String(object.bundledObjectTypes) : "",
      bundledRelations: isSet(object.bundledRelations) ? globalThis.String(object.bundledRelations) : "",
      bundledLayouts: isSet(object.bundledLayouts) ? globalThis.String(object.bundledLayouts) : "",
      objectsForceReindexCounter: isSet(object.objectsForceReindexCounter)
        ? globalThis.Number(object.objectsForceReindexCounter)
        : 0,
      filesForceReindexCounter: isSet(object.filesForceReindexCounter)
        ? globalThis.Number(object.filesForceReindexCounter)
        : 0,
      idxRebuildCounter: isSet(object.idxRebuildCounter) ? globalThis.Number(object.idxRebuildCounter) : 0,
      fulltextRebuild: isSet(object.fulltextRebuild) ? globalThis.Number(object.fulltextRebuild) : 0,
      fulltextErase: isSet(object.fulltextErase) ? globalThis.Number(object.fulltextErase) : 0,
      bundledTemplates: isSet(object.bundledTemplates) ? globalThis.String(object.bundledTemplates) : "",
      bundledObjects: isSet(object.bundledObjects) ? globalThis.Number(object.bundledObjects) : 0,
      filestoreKeysForceReindexCounter: isSet(object.filestoreKeysForceReindexCounter)
        ? globalThis.Number(object.filestoreKeysForceReindexCounter)
        : 0,
      areOldFilesRemoved: isSet(object.areOldFilesRemoved) ? globalThis.Boolean(object.areOldFilesRemoved) : false,
      areDeletedObjectsReindexed: isSet(object.areDeletedObjectsReindexed)
        ? globalThis.Boolean(object.areDeletedObjectsReindexed)
        : false,
      linksErase: isSet(object.linksErase) ? globalThis.Number(object.linksErase) : 0,
      marketplaceForceReindexCounter: isSet(object.marketplaceForceReindexCounter)
        ? globalThis.Number(object.marketplaceForceReindexCounter)
        : 0,
      reindexDeletedObjects: isSet(object.reindexDeletedObjects) ? globalThis.Number(object.reindexDeletedObjects) : 0,
      reindexParticipants: isSet(object.reindexParticipants) ? globalThis.Number(object.reindexParticipants) : 0,
      reindexChats: isSet(object.reindexChats) ? globalThis.Number(object.reindexChats) : 0,
    };
  },

  toJSON(message: ObjectStoreChecksums): unknown {
    const obj: any = {};
    if (message.bundledObjectTypes !== "") {
      obj.bundledObjectTypes = message.bundledObjectTypes;
    }
    if (message.bundledRelations !== "") {
      obj.bundledRelations = message.bundledRelations;
    }
    if (message.bundledLayouts !== "") {
      obj.bundledLayouts = message.bundledLayouts;
    }
    if (message.objectsForceReindexCounter !== 0) {
      obj.objectsForceReindexCounter = Math.round(message.objectsForceReindexCounter);
    }
    if (message.filesForceReindexCounter !== 0) {
      obj.filesForceReindexCounter = Math.round(message.filesForceReindexCounter);
    }
    if (message.idxRebuildCounter !== 0) {
      obj.idxRebuildCounter = Math.round(message.idxRebuildCounter);
    }
    if (message.fulltextRebuild !== 0) {
      obj.fulltextRebuild = Math.round(message.fulltextRebuild);
    }
    if (message.fulltextErase !== 0) {
      obj.fulltextErase = Math.round(message.fulltextErase);
    }
    if (message.bundledTemplates !== "") {
      obj.bundledTemplates = message.bundledTemplates;
    }
    if (message.bundledObjects !== 0) {
      obj.bundledObjects = Math.round(message.bundledObjects);
    }
    if (message.filestoreKeysForceReindexCounter !== 0) {
      obj.filestoreKeysForceReindexCounter = Math.round(message.filestoreKeysForceReindexCounter);
    }
    if (message.areOldFilesRemoved !== false) {
      obj.areOldFilesRemoved = message.areOldFilesRemoved;
    }
    if (message.areDeletedObjectsReindexed !== false) {
      obj.areDeletedObjectsReindexed = message.areDeletedObjectsReindexed;
    }
    if (message.linksErase !== 0) {
      obj.linksErase = Math.round(message.linksErase);
    }
    if (message.marketplaceForceReindexCounter !== 0) {
      obj.marketplaceForceReindexCounter = Math.round(message.marketplaceForceReindexCounter);
    }
    if (message.reindexDeletedObjects !== 0) {
      obj.reindexDeletedObjects = Math.round(message.reindexDeletedObjects);
    }
    if (message.reindexParticipants !== 0) {
      obj.reindexParticipants = Math.round(message.reindexParticipants);
    }
    if (message.reindexChats !== 0) {
      obj.reindexChats = Math.round(message.reindexChats);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectStoreChecksums>, I>>(base?: I): ObjectStoreChecksums {
    return ObjectStoreChecksums.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectStoreChecksums>, I>>(object: I): ObjectStoreChecksums {
    const message = createBaseObjectStoreChecksums();
    message.bundledObjectTypes = object.bundledObjectTypes ?? "";
    message.bundledRelations = object.bundledRelations ?? "";
    message.bundledLayouts = object.bundledLayouts ?? "";
    message.objectsForceReindexCounter = object.objectsForceReindexCounter ?? 0;
    message.filesForceReindexCounter = object.filesForceReindexCounter ?? 0;
    message.idxRebuildCounter = object.idxRebuildCounter ?? 0;
    message.fulltextRebuild = object.fulltextRebuild ?? 0;
    message.fulltextErase = object.fulltextErase ?? 0;
    message.bundledTemplates = object.bundledTemplates ?? "";
    message.bundledObjects = object.bundledObjects ?? 0;
    message.filestoreKeysForceReindexCounter = object.filestoreKeysForceReindexCounter ?? 0;
    message.areOldFilesRemoved = object.areOldFilesRemoved ?? false;
    message.areDeletedObjectsReindexed = object.areDeletedObjectsReindexed ?? false;
    message.linksErase = object.linksErase ?? 0;
    message.marketplaceForceReindexCounter = object.marketplaceForceReindexCounter ?? 0;
    message.reindexDeletedObjects = object.reindexDeletedObjects ?? 0;
    message.reindexParticipants = object.reindexParticipants ?? 0;
    message.reindexChats = object.reindexChats ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
