import { I } from 'ts/lib';

export default [
	{ type: I.BlockType.IconPage, icon: '👋' },
	{ type: I.BlockType.Title, text: 'Import' },
	{ text: 'We value your time and develop a great timesaver for you — now you can transfer data from other sources into Anytype!' },
	{ text: 'Open settings in the dashboard or use <span class="bgColor bgColor-grey textColor textColor-red">File → Import</span> in the System menu and try. You can import all your data from Notion with the same structure for now, later we will develop more sources.' },
	{ text: '<img src="./img/help/import.png" style="width:inherit;">' },
	{ text: 'A friendly reminder. Without any imports, you can save note from another app or an article from Wikipedia, and store it forever on your computer. Just copy it there and paste into Anytype. <i>Voila!<i>' },
	{ text: 'Please, write us what you think and what source you want to import in&nbsp;Anytype!' },
	{ text: '<i class="note">10 June 2020</i>' },
	{ type: I.BlockType.Div, style: I.DivStyle.Dot },

	{ style: I.TextStyle.Header1, text: 'Mention' },
	{ text: 'Now Anytype allows you to refer to any page right in your content.' },
	{ text: 'Simply insert the <span class="bgColor bgColor-grey textColor textColor-red">@</span> sign and start typing the name of a page you want to refer to.' },
	{ text: 'You can mention any page anywhere and it will build a relationship between pages. All&nbsp;mentions will be shown in the navigation panel. It’s just a more convenient way to connect any pages inside Anytype. Hope you enjoy it and we look forward to your suggestions on how we could make it better.' },
	{ text: '<img src="./img/help/mention.gif" style="width:inherit;">' },
	{ text: '<font style="text-align: right; color:#aca996; display: block;"><i class="note">29 May 2020</i></font>' },
	{},
	{ type: I.BlockType.Div, style: I.DivStyle.Dot },
	{},
	{ style: I.TextStyle.Header1, text: 'Meet the new navigation' },
	{ text: 'All the knowledge we have in our brains organized associatively, not hierarchically. Our&nbsp;brain, in a way, is interconnected wiki. We have multiple connections between ideas or thoughts in our brains - it’s the way we navigate through our memories.' },
	{ text: 'We introduce bi-directional links that allow you to connect ideas freely; you can reuse objects and create any information structure you desire.</br>' },
	{ text: 'Now you can use a three-line icon <span class="icon nav"></span> on the top left of the application or press <span class="bgColor bgColor-grey textColor textColor-red">Cmd + O</span> to see bi-directional links between pages and navigate through them.' },
	{ text: 'You can press <span class="bgColor bgColor-grey textColor textColor-red">Cmd + S</span> and search the right page by name or information in the&nbsp;first&nbsp;paragrapgh.' },
	{},
	{ text: '<b>Now you can stop segmenting and limiting the way you connect your thoughts — just link the pages and flesh everything out more naturally.</b>' },
	{ text: '<font style="text-align: right; color:#aca996; display: block;"><i class="note">6 May 2020</i></font>' },
	{},
	{ type: I.BlockType.Div, style: I.DivStyle.Dot },
	{},
	{ style: I.TextStyle.Header1, text: 'Introducing Anytype' },
	{ text: 'We upgraded the design and backed it up with cutting edge technologies to make your experience safe, secure, and convenient.' },
	{ text: '<span class="bgColor bgColor-yellow">This version of Anytype is suitable for personal usage only</span>. In the next versions we’ll add collaborative functionality.' },

	{ style: I.TextStyle.Header3, text: 'Available features' },
	{ style: I.TextStyle.Bulleted, text: 'Editor with different kinds of blocks you need to work with notes, ideas, collections, knowledge bases, receipts, diaries, to-do lists, travel plans;' },
	{ style: I.TextStyle.Bulleted, text: 'Media content. Organize your space with playable videos, photos, and web bookmarks;' },
	{ style: I.TextStyle.Bulleted, text: 'Drag and drop everything in Anytype. Move blocks and create columns. Create pages from your desktop folders. Copy & paste content from other resources;' },
	{ style: I.TextStyle.Bulleted, text: 'Page styling. Cover the page with a picture, use emoji or custom image to enhance appearance;' },
	{ style: I.TextStyle.Bulleted, text: 'Dashboard. Add your favorite documents, sort them, and archive to reach them in&nbsp;a&nbsp;second.' },
	{},
	{ text: '<b>Create a new home for your information — private and free</b>.' },
	{},
	{ text: 'Thank you for building a new web together, writing us a review, reporting a bug, or making a feature request, moving all of us forward. 🙏' },
	{ text: 'Don’t forget to <span class="textColor textColor-red">save your seed phrase</span>  to save access to all your private data. All&nbsp;the&nbsp;new features will appear in automatic updates.' },
	{ text: '<font style="text-align: right; color:#aca996; display: block;"><i class="note">03 March 2020</i></font>' },
	{}
];
