/**
 * Icon pack: view — auto-generated by scripts/convert-icons.ts
 */
import { registerIcon } from '../../iconRegistry';

import { ViewBoardIcon } from './viewBoard';
import { ViewCalendar0Icon } from './viewCalendar0';
import { ViewCalendar1Icon } from './viewCalendar1';
import { ViewGalleryIcon } from './viewGallery';
import { ViewGallery0Icon } from './viewGallery0';
import { ViewGallery1Icon } from './viewGallery1';
import { ViewGraph0Icon } from './viewGraph0';
import { ViewGraph1Icon } from './viewGraph1';
import { ViewGridIcon } from './viewGrid';
import { ViewGrid0Icon } from './viewGrid0';
import { ViewGrid1Icon } from './viewGrid1';
import { ViewKanban0Icon } from './viewKanban0';
import { ViewKanban1Icon } from './viewKanban1';
import { ViewListIcon } from './viewList';
import { ViewList0Icon } from './viewList0';
import { ViewList1Icon } from './viewList1';

registerIcon('viewBoard', ViewBoardIcon);
registerIcon('viewCalendar0', ViewCalendar0Icon);
registerIcon('viewCalendar1', ViewCalendar1Icon);
registerIcon('viewGallery', ViewGalleryIcon);
registerIcon('viewGallery0', ViewGallery0Icon);
registerIcon('viewGallery1', ViewGallery1Icon);
registerIcon('viewGraph0', ViewGraph0Icon);
registerIcon('viewGraph1', ViewGraph1Icon);
registerIcon('viewGrid', ViewGridIcon);
registerIcon('viewGrid0', ViewGrid0Icon);
registerIcon('viewGrid1', ViewGrid1Icon);
registerIcon('viewKanban0', ViewKanban0Icon);
registerIcon('viewKanban1', ViewKanban1Icon);
registerIcon('viewList', ViewListIcon);
registerIcon('viewList0', ViewList0Icon);
registerIcon('viewList1', ViewList1Icon);

// Aliases
registerIcon('viewCalendar', ViewCalendar0Icon);
registerIcon('viewGraph', ViewGraph0Icon);
registerIcon('viewTimeline', ViewList0Icon);
