/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Action: typeof import('Lib/action').default
  const C: typeof import('Lib/api/command')
  const Dataview: typeof import('Lib/dataview').default
  const Decode: typeof import('Lib/api/struct').Decode
  const Encode: typeof import('Lib/api/struct').Encode
  const H: typeof import('Hook')
  const J: typeof import('json')
  const Key: typeof import('Lib/keyboard').Key
  const Mapper: typeof import('Lib/api/mapper').Mapper
  const Mark: typeof import('Lib/mark').default
  const Onboarding: typeof import('Lib/onboarding').default
  const Preview: typeof import('Lib/preview').default
  const Relation: typeof import('Lib/relation').default
  const Renderer: typeof import('Lib/renderer').default
  const S: typeof import('Store')
  const SYSTEM_SOUND_ID: typeof import('Lib/sound').SYSTEM_SOUND_ID
  const Sound: typeof import('Lib/sound').default
  const Survey: typeof import('Lib/survey').default
  const U: typeof import('Lib/util')
  const analytics: typeof import('Lib/analytics').analytics
  const dispatcher: typeof import('Lib/api/dispatcher').dispatcher
  const getSparkOnboardingService: typeof import('Lib/service/sparkOnboarding').getSparkOnboardingService
  const keyboard: typeof import('Lib/keyboard').keyboard
  const scrollOnMove: typeof import('Lib/scrollOnMove').scrollOnMove
  const sidebar: typeof import('Lib/sidebar').sidebar
  const translate: typeof import('Lib/translate').translate
}
