import { I } from 'ts/lib';

export default [
	{ type: I.BlockType.IconPage, icon: '👋' },
	{ style: I.TextStyle.Title, text: `Introduction` },
	{ text: `Anytype is a personal knowledge base, a digital brain that allows you to capture, describe, and connect information quickly. ` },
	{ text: `You can use Anytype to create books, tasks, notes, ideas, documents, tools and organise them any way you want. Future versions will allow you to share your work and safely collaborate with others. We want Anytype to be a global repository of knowledge.` },
	{ style: I.TextStyle.Header1, text: `Privacy and Security` },
	{ style: I.TextStyle.Header3, text: `Encryption` },
	{ text: `Your data is stored on your devices and encrypted with a keychain phrase. The keychain phrase is something only you know, please keep it safe. You need it to sign in to new devices. If you lose it Anytype cannot help you recover your data. ` },
	{ text: `<i>To read more about privacy:</i> <a href="https://community.anytype.io/knowledgebase/271-privacy-security"><i>https://community.anytype.io/knowledgebase/271-privacy-security</i></a>` },
	{ style: I.TextStyle.Header3, text: `Backup and Storage` },
	{ text: `One feature of the alpha program is a decentralised and encrypted backup node. This is provided free of charge to all alpha testers. Your objects are encrypted and synced to our cafe nodes. If your device is lost or damaged, you can restore the latest snapshot from our backup node. This feature is currently in early alpha. Data on the backup node is encrypted, and the Anytype team cannot access your data.` },
	{ text: `<i>To read more about storage:</i> <a href="https://community.anytype.io/knowledgebase/272-storage-deletion"><i>https://community.anytype.io/knowledgebase/272-storage-deletion</i></a>` },
	{ style: I.TextStyle.Header1, text: `Objects` },
	{ text: `Everything in Anytype is an object: people, books, musicians, documents, ideas, places, numbers or files. For instance, a person named "Enda", an essay to write, the music of "Pink Floyd", the film "2001", a town named "Berlin", a year, or just a simple status like "Done". ` },
	{ text: `<img src="./img/help/intro/d2b5ca33bd970f64a6301fa75ae2eb22.png" class="full" />` },
	{ style: I.TextStyle.Header3, text: `Object canvas` },
	{ text: `Every object has a flexible canvas made of simple blocks. Each block is a piece of information which you can freely move around the canvas. You can add any information you like by hitting the <kbd>+</kbd> button or in-line by typing <kbd>/</kbd>. Highlight a block to see its size or move it elsewhere on the canvas. To create a column, simply drag one block to the end of another block.` },
	{ text: `<kbd>GIF</kbd>` },
	{ text: `<b>The following blocks are available in this version of Anytype:</b>` },
	{ style: I.TextStyle.Bulleted, text: `Text: text, title, heading, subheading, highlighted` },
	{ style: I.TextStyle.Bulleted, text: `Lists: checkbox, bulleted list, numbered, toggle` },
	{ style: I.TextStyle.Bulleted, text: `Media: file, picture, video, bookmark, code-snippet` },
	{ style: I.TextStyle.Bulleted, text: `Objects: create new objects (tasks, people, documents), or link to an existing object` },
	{ style: I.TextStyle.Bulleted, text: `Relations: all relations for this object` },
	{ style: I.TextStyle.Bulleted, text: `Others: line divider, dotted divider` },
	{ style: I.TextStyle.Header3, text: `<b>Object layout</b>` },
	{ text: `Layouts help you customise how your object looks. You can align your text blocks, customise the icon type, or change the page width.` },
	{ text: `<kbd>GIF</kbd>` },
	{ text: `<b>Anytype currently supports three kinds of layout:</b>` },
	{ text: `1.  <b>Basic:</b> a classic view for notes, articles, and docs. ` },
	{ text: `2.  <b>Profile:</b> designed for contacts, people, and organisations. ` },
	{ text: `3.  <b>Action:</b> for getting things done. Perfect for tasks and plans.` },
	{ text: `We designed layouts to be extendable. In the future anyone can make new layouts.` },
	{ text: `Both the basic and profile layout support either an emoji or a photo icon. All layouts support a cover image.` },
	{ style: I.TextStyle.Header1, text: `Knowledge Graph` },
	{ text: `<img src="./img/help/intro/24e0aacf67998dbe6a39efb127ba86f4.png" class="full" />` },
	{ text: `Your objects combine to form a unique knowledge graph. It's a universal data structure, and a strong foundation for automation. We want Anytype to be a modular platform for machine learning and plan to release our first modules for the public beta. ` },
	{ style: I.TextStyle.Header1, text: `Relations` },
	{ text: `<img src="./img/help/intro/55634384f007cf8c9a5e9a4dbc97ed15.png" class="full" />` },
	{ text: `We use <b>relations</b> to connect objects in the graph. They add context and significance to each connection. For instance, Patrick was born in 1984, he lives in Berlin, and he just finished an essay. His favourite band is Pink Floyd and his favourite movie is <i>2001: A Space Odyssey</i>. Patrick is connected to each of these objects with relations like "date of birth", "location", "last task", "band", and "movie".` },
	{ text: `<b>Common Relations:</b>` },
	{ style: I.TextStyle.Bulleted, text: `<b>Name:</b> the name of an object.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Type:</b> defines how an object looks and its default relations.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Tag:</b> a typical relation used to label an object for future reference.` },
	{ style: I.TextStyle.Header3, text: `Adding relations` },
	{ text: `<img src="./img/help/intro/8283b5d6cdba44958105ad1f0f21a0bd.gif" class="full" />` },
	{ style: I.TextStyle.Bulleted, text: `You can add a relation to the canvas like any other block - with a <kbd>+</kbd> button or the in-line <kbd>/</kbd> menu.` },
	{ style: I.TextStyle.Bulleted, text: `In the relations panel found in the canvas, next to the object name. This panel shows all relations in that object. Here you can add new relations or modify existing ones.` },
	{ style: I.TextStyle.Bulleted, text: `You can feature any relation by clicking the ★ next to the relation in the relations panel. Featured relations are shown on the canvas, next to the object's name.` },
	{ text: `<img src="./img/help/intro/9b155694b27923f10da8ba104544744e.gif" class="full" />` },
	{ style: I.TextStyle.Header3, text: `Creating relations` },
	{ text: `<b>From the library:</b>` },
	{ text: `Choose from any relation available in your library. Inside the library, you will find relations created by Anytype and you. ` },
	{ text: `<img src="./img/help/intro/743391576d2cf729de4f91f4c3c92ce4.gif" class="full" />` },
	{ text: `<b>From scratch:</b>` },
	{ text: `You can easily create an entirely new relation from scratch. It will then be added to your library, ready for use across your Anytype.` },
	{ text: `<img src="./img/help/intro/bfcb7163c909213faff24a55bdaf644a.gif" class="full" />` },
	{ text: `The below types of information are currently available for relations:` },
	{ style: I.TextStyle.Bulleted, text: `<b>Text:</b> accepts text as the input. ` },
	{ style: I.TextStyle.Bulleted, text: `<b>Number:</b> for all numbers. Different formats are coming soon.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Date:</b> date, optional input for time.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Status:</b> an array of the string with a restriction on the output of only one element.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Tag:</b> another array of the string with no restrictions on the output of only one element.` },
	{ style: I.TextStyle.Bulleted, text: `<b>email/phone/URL:</b> special formats for URL, email and phone number.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Checkbox:</b> an object with a boolean, string, or link to an object.` },
	{ style: I.TextStyle.Bulleted, text: `<b>Media:</b> audio, movies, or pictures which you can view, play, or download. ` },
	{ style: I.TextStyle.Bulleted, text: `<b>Object:</b> reference to a specific object, like a person, task or document.` },
	{ text: `At present relations cannot be deleted. Be careful to avoid duplicate relations with the same name. ` },
	{ style: I.TextStyle.Header3, text: `Tips` },
	{ style: I.TextStyle.Bulleted, text: `Relations included with Anytype cannot currently be modified.` },
	{ style: I.TextStyle.Bulleted, text: `Some relations are read-only, and you cannot change their value. Relations such as <kbd>Created</kbd> or <kbd>Last modified</kbd>. Read-only relations have the 🔒 icon next to them. ` },
	{ style: I.TextStyle.Bulleted, text: `If you add a new relation to a Set, Anytype will not add empty values to the relations in that set. However, when you open an object, that relation will be suggested to you.` },
	{ style: I.TextStyle.Bulleted, text: `When creating an object, Anytype will display empty values in the list of relations.` },
	{ text: `Relations are shared across your Anytype. Renaming a relation in one object will change it's name across all objects` },
	{ style: I.TextStyle.Header1, text: `Types` },
	{ text: `Types bring definition to your objects, informing how they look and the relations they feature. You can always change your object's type. What begins as an idea can turn into a task and eventually a project. Your types and their changes sync automatically between your devices.` },
	{ text: `<img src="./img/help/intro/19baf21e72d20e02f22a7edc9375bf89.gif" class="full" />` },
	{ text: `<b>Types included with Anytype:</b>` },
	{ style: I.TextStyle.Bulleted, text: `Tasks ` },
	{ style: I.TextStyle.Bulleted, text: `Contacts` },
	{ style: I.TextStyle.Bulleted, text: `Projects` },
	{ style: I.TextStyle.Bulleted, text: `Notes` },
	{ style: I.TextStyle.Bulleted, text: `Articles` },
	{ style: I.TextStyle.Bulleted, text: `Ideas` },
	{ style: I.TextStyle.Bulleted, text: `Humans ` },
	{ style: I.TextStyle.Bulleted, text: `Books` },
	{ style: I.TextStyle.Bulleted, text: `& more` },
	{ text: `Use the <b>draft</b> to quickly create new objects and capture information. Drafts don't support templates or layouts.` },
	{ style: I.TextStyle.Header3, text: `<b>Creating types</b>` },
	{ text: `To create a new type, use the "Create a new type" button in the library. You can choose the default <b>relations</b>, <b>layout</b>, and optionally <b>create a template.</b>` },
	{ text: `<img src="./img/help/intro/09f7a59ffb9b695c0923cea821ec15ce.gif" class="full" />` },
	{ style: I.TextStyle.Header1, text: `Sets` },
	{ text: `Bring multiple objects into one view with Sets. You can make a Set for a specific type of object, like seeing every task in one view. Inside a Set, you can sort, filter and choose a view.` },
	{ text: `<img src="./img/help/intro/0c62976fba4a5a656c763bc8f4827ffe.png" class="full" />` },
	{ text: `Sets don't <b>store</b> objects. They are a way to see a portion of your knowledge graph, like objects tagged <kbd>Work</kbd>. Sets help you sort through, and create specific views to work with many objects at once.` },
	{ style: I.TextStyle.Header3, text: `<b>Creating Sets</b>` },
	{ text: `<img src="./img/help/intro/b7651775e24cea98a477ef5069955894.png" class="full" />` },
	{ text: `From the Store, choose an object type, click "Create", and choose "Create a set".` },
	{ text: `<img src="./img/help/intro/0b87284ee9efab039a9c304575ea0ce7.gif" class="full" />` },
	{ style: I.TextStyle.Header1, text: `Templates` },
	{ text: `Templates are a great way to get started with new objects. You can create a template from scratch or use one already included with Anytype` },
	{ text: `<img src="./img/help/intro/3c1bebe2a46aa4a27d551fc27a672482.png" class="full" />` },
	{ text: `Types support multiple templates, so you could, for example, have templates for different tasks or systems like GTD and OKRs. Or different templates for different kinds of book, like academic, fiction, non-fiction.` },
	{ text: `<img src="./img/help/intro/bb055fa9cdf5f1aa2f4da16607dc36c3.gif" class="full" />` },
	{ text: `<b>Current template options:</b>` },
	{ style: I.TextStyle.Bulleted, text: `Choosing the layout.` },
	{ style: I.TextStyle.Bulleted, text: `Basic, profile, or action.` },
	{ style: I.TextStyle.Bulleted, text: `Featured relations.` },
	{ style: I.TextStyle.Bulleted, text: `Canvas blocks to build a visual structure.` },
	{ text: `Existing objects can be turned into templates using the <b>···</b> button.` },
	{ text: `<img src="./img/help/intro/438eb7b559abca855553778d41ab29fd.png" class="full" />` },
	{ style: I.TextStyle.Header1, text: `Summary` },
	{ text: `This is the very first version of Anytype. An encrypted, offline-first tool for thought with robust sync on mobile and desktop. In the coming months we will release full support on iOS, Graph view, dark mode, and local APIs.` },
	{ style: I.TextStyle.Header1, text: `Thank you` },
	{ text: `We still have a long way to go, but your feedback gets us there faster. Thank you for being a part of the alpha program, and thank you for being part of this journey.` },
	{ text: `— Anton, Roman, Zhanna & the entire Anyteam.` },
];