#!/usr/bin/env sh
export PATH="$HOME/.bun/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --concurrent false

# npm run typecheck

# Checking for secrets
#gitleaks protect --verbose --redact --staged

# Checking dependencies' licenses
#npx license-checker --production --json --out licenses.json
#node check-licenses.js