#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --concurrent false
# npm run typecheck

# Checking for secrets
gitleaks protect --verbose --redact --staged

# Checking dependencies' licenses
npx license-checker --production --json --out licenses.json
node check-licenses.js