#!/usr/bin/env sh
huskydir=$(dirname -- "$0")
if [ -f "$huskydir/_/husky.sh" ]; then
  . "$huskydir/_/husky.sh"
fi

npx lint-staged --concurrent false
# npm run typecheck

# Checking for secrets
gitleaks protect --verbose --redact --staged

# Checking dependencies' licenses
npx license-checker --production --json --out licenses.json
node check-licenses.js