import * as I from 'Interface';
import { Block, Helpers } from './common';

export default (h: Helpers): Block[] => {
	const { cmd, shift, hl, icon, title, h1, h2, h3, h4, text, callout, bullet, caption, div, video, img, link } = h;
	return [
		icon('💬'),

		title(`Now We're Talking!`),
		h4(`<span>Release 0.50.0</span><span>October 1, 2025</span>`),
		text(''),
		text('We’ve always built Anytype around private, peer-to-peer collaboration. Spaces gave you a structured home for your notes, docs and databases. Now we’re taking the next step: introducing Chats, a new way to connect and collaborate while keeping your data fully in your hands.'),
		text(``),

		h1(`Welcome to Chat`),
		text(`Chat is a new type of channel in Anytype, designed for fast, conversational flow. It gives you the familiar rhythm of chatting – replying, reacting, sharing files – but with a powerful twist: you can create and edit objects together in real time.`),
		img(`50/1.png`),
		bullet(`<b>Create Objects</b> right from your chat window – turn thoughts into Pages, Tasks, or any other Type.`),
		bullet(`<b>Share existing Objects</b> – anything you drop into Chat can be opened and edited right away.`),
		bullet(`<b>Keep things organized</b> – uploads are added to the relevant Types (Audio, Images) and everything stays searchable and structured in your sidebar.`),
		bullet(`<b>Invite with ease</b> – bring new members into a conversation instantly with links that don’t require approval.`),
		text(``),
		text('You can switch between two formats: Chats and Spaces in their settings. You choose what is better for your use.'),
		text(``),

		h1(`The Vault Update`),
		text(`Your Vault now brings together Spaces and Chats with live previews and updates in one view. You can pin important chats or spaces so they’re always within reach.`),
		text(`When you’re in a Chat, the Vault shows all your conversations at a glance, making it easy to switch between them and stay in the flow. Step into a Space, and the Vault shifts its focus so you can concentrate on it.`),
		img(`50/2.png`),
		text(``),

		h1(`Widget Bar Restructure`),
		text(`We’ve reworked the Sidebar to create a clearer navigation model. The goal was to clarify the difference between shortcuts and containers.`),
		text(`The Sidebar now has two distinct collapsible sections:`),
		bullet(`<b>Pinned</b> → All the widgets you had before, kept close at hand as shortcuts.`),
		bullet(`<b>Objects</b> → Previously accessible only from Settings, these containers list all objects of a given Type and work just like widgets.`),
		img(`50/3.png`),
		text(``),
		text(`Everything you had pinned before is preserved in the Pinned widget. You can re-pin what’s needed in a new way and remove the “old” widget.`),
		text(`If you have been using <i>Recently Edited</i> or <i>Recently Opened</i>, those widgets remain, but once removed they can’t be added back. Instead, you can always create Queries to show objects by their creation or modification date.`),
		text(`At the same time, we’ve removed duplicate flows like the <i>Edit Widgets</i> button and <i>All Objects</i>, so there’s now a single, unified way to pin and organize.`),
		text(``),

		h1(`Quality of Life Improvements`),
		text(''),

		text(`<b>Manual Sorting for Property Options</b>`),
		text(`Options in ${hl('Select')}, ${hl('Multi-select')} formats – as well as a Tag property – no longer follow automatic alphabetical or creation order. You can now drag and drop them into a custom sequence, which is saved across devices and applied consistently in Queries and Collections. New options are added to the bottom of the list.`),
		text(``),

		text(`<b>App Menu Update on Windows</b>`),
		text(`The top bar has been redesigned with a cleaner menu that feels more consistent: it now works seamlessly in Dark Mode and is better tuned to Anytype’s overall design.`),
		text(``),

		text(`<b>Enter Continues List, Backspace Removes Style</b>`),
		text(`Pressing ${hl('Enter')} after an empty Bullet or Numbered block now continues the List. To remove the style, use ${hl('Backspace')} instead.`),
		text(``),

		h1(`Bug Fixes`),
		text(''),

		bullet(`<b>Chinese IME input before formatted content no longer causes unintended style changes.</b> Thanks to @${link('https://github.com/anyproto/anytype-ts/issues/1542', 'yudi-corgi')} for reporting and @${link('https://github.com/anyproto/anytype-ts/pull/1633', 'twinklestar03')} for contributing the fix!`),
		bullet(`<b>Table of Contents correctly highlights the current position on a page.</b> Thanks to @${link('https://community.anytype.io/t/28532', 'VisualNotes')}!`),
		bullet(`<b>Restored ${hl('Ctrl + Click')} support on macOS for opening object menus.</b> Thanks to @${link('https://community.anytype.io/t/can-t-right-click/28487', 'mkjohnnie')} for the report!`),
		bullet(`<b>Shortcut ${hl('Ctrl + Click')} to open objects in a new window works correctly in Queries and Collections.</b> Thanks to @${link('', 'leblanclxd')}!`),
		bullet(`<b>${hl('Right Click')} on the Graph view in Widgets works correctly.</b>`),
		bullet(`<b>Options in Select and Multi-select properties are now created correctly.</b>`),
		bullet(`<b>Code Snippet embed block now handles input correctly, including when typing in Python or HTML language mode.</b> Thanks to @${link('https://community.anytype.io/t/28613', 'Cash')}!`),
		bullet(`<b>Deeplinks now work correctly and open the target object from outside Anytype.</b> Thanks to @${link('https://community.anytype.io/t/28651', 'siousu')}!`),
		bullet(`<b>See All in Widgets has increased limits for displayed objects, making it possible to browse large lists in the sidebar.</b> Thanks to @${link('https://community.anytype.io/t/28654', 'wyn')}!`),
		bullet(`<b>Improved drag-and-drop behavior in Kanban view.</b>`),
		bullet(`<b>Improved Global Search performance, fixing freezes after creating objects with ${hl('Cmd+N')} and ensuring results display correctly.</b>`),
		bullet(`<b>Pages with a cover image and minimal content no longer scroll unnecessarily.</b> Thanks to @${link('https://community.anytype.io/t/28453', 'VisualNotes')}`),
		bullet(`<b>Fixed an issue where opening certain spaces created on mobile caused the desktop app to display a blank screen.</b> Thanks to @${link('https://community.anytype.io/t/28667', 'fei')} for the report!`),
		bullet(`<b>Browsing history is preserved after hiding and reopening the Widget Sidebar.</b> Thanks to @${link('https://community.anytype.io/t/28727', 'Shampra')}!`),
		bullet(`<b>The calendar pop-in when selecting a date via @date no longer appears behind the menu.</b> Thanks to @${link('https://community.anytype.io/t/28728', 'rphlm')}!`),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.49.0 Released!`),
		text(''),
		text('Some features didn’t fit into last week’s release – so here we are again. This update brings a long-awaited request, plus a few practical improvements and smaller fixes we wanted to share with you as soon as possible.'),
		text(``),

		h2(`Highlights`),

		h3(`Invite Links Without Approval`),
		text(`One of your most requested features has arrived. You can finally add new members to your space without manual approval: just share an invite link with Editor or Viewer access, and you're all set.`),
		text(`How it works:`),
		bullet(`Each space can have only <b>one active invite link</b> at a time.`),
		bullet(`<b>Editor/Viewer links are the same</b> – switching between them doesn’t generate a new link, but new members will get the role currently selected in space settings.`),
		bullet(`Switching to <b>Request access</b> generates a new link and <b>disables previous</b> Editor/Viewer link.`),
		bullet(`Switching back to Editor/Viewer (no approval) <b>generates a new link</b>, replacing the previous one.`),
		bullet(`Switching to <b>Link disabled</b> invalidates any active link, but does not remove existing members.`),
		img(`49/1.png`, 'c70 screen'),
		text(``),

		h3(`Updated Templates Section in Edit Type`),
		text(`The new interface displays up to 6 templates in the Edit Type sidebar and adds a visual horizontal swiper for browsing more.`),
		img(`49/2.png`, 'c70 screen'),
		text(``),

		h2(`Quality of Life Improvements`),
		text(''),

		text(`<b>Reorganized App Settings</b>`),
		text(`App settings have been slightly reorganized into three clear sections to make navigation more intuitive:`),
		bullet(`<b>Data Management</b> is now called <b>Local Storage</b>.`),
		bullet(`<b>My Sites</b> has been moved to a higher level under the <b>Data Management</b> section.`),
		bullet(`<b>Account Deletion</b> is now located under the <b>Login Key</b>.`),
		img(`49/3.png`, 'c70 screen'),
		text(``),

		text(`<b>See All in Widgets</b>`),
		text(`Widgets now show a ${hl('See all')} button when they contain more objects than are currently visible. It opens a widget view similar to system widgets like Pinned or Recently Edited, making it clear there’s more to explore.`),
		img(`49/4.png`, 'c70 screen'),
		text(``),

		text(`<b>Shortcut Conflicts Resolution</b>`),
		text(`Assigning a shortcut that’s already in use now shows a confirmation prompt – offering the option to <b>Override</b> (clears the old mapping) or <b>Remove</b> (clears the new one). Certain system shortcuts that can’t be reassigned are now also protected from accidental value deletion.`),
		img(`49/5.png`, 'c70 screen'),
		text(``),

		text(`<b>PIN Code Reworked on Keychain</b>`),
		text(`The PIN code is now stored in the system keychain, along with your Vault Key, for better security.`),
		text(`For backward compatibility, it will continue to be used from local storage <b>until you save it again</b> – so if you want to fully switch to the new system, just update or save your PIN again.`),
		text(``),

		text(`<b>Remote Storage Banners</b>`),
		text(`New indicators are here to keep you in the loop about your remote storage usage, with banners appearing from 55% usage and showing your current percentage in the Sync Status menu.`),
		text(``),

		text(`<b>Copy Identity from Member Card</b>`),
		text(`You can now copy a member’s identity (or their name.any) from the space member's card.`),
		text(``),

		h2(`Bug Fixes`),
		text(''),

		bullet(`Fixed an issue where code formatting wasn't triggered when a backtick was followed by a tilde (${hl(' ~ ')}). Thanks to @${link('https://community.anytype.io/t/24194', 'dantefromhell')} and @${link('https://community.anytype.io/t/26055', 'dave2')} for reporting!`),
		bullet(`In the Calendar view and views within Inline Collections, properties configured in filters are now correctly added to new objects. Thanks to @${link('https://community.anytype.io/t/28504', 'sturdily')}!`),
		bullet(`When multiple widgets point to the same Query but use different views, clicking the widget title now opens the corresponding view. Thanks to @${link('https://community.anytype.io/t/27530', 'siousu')}!`),
		bullet(`Navigating back to a Query with the ${hl('<')} button now restores the previously open view. Thanks to @${link('https://community.anytype.io/t/26928', 'Shampra')}!`),
		bullet(`After adding a bookmark to the Editor, pressing ${hl('Enter')} now adds a new block so you can continue writing without interruption.`),
		bullet(`Fixed unreadable "Out of storage" indicator in the Sync Status menu when using dark mode. Thanks to @${link('https://community.anytype.io/t/28543', 'Alan71')}!`),
		bullet(`The Pin option has been removed from templates, since they aren’t supported in widgets. We recognize this made quick access easier for some workflows – thanks to @${link('https://community.anytype.io/t/28537', 'C.c')} for raising the point.`),
		bullet(`Fixed an issue where the date picker overlapped the edit field when editing date properties in lower rows of a Grid view. Thanks to @${link('https://community.anytype.io/t/date-picker-overlaps-itself-with-the-date-edit-filed/28278', 'Code-Jack')}!`),
		bullet(`Custom Sort order in Collections now applies correctly in widgets.`),
		bullet(`Long space names are no longer cut off in the Deletion pop-up.`),
		bullet(`The update animation no longer remains after a network error interrupts the download process.`),
		bullet(`Improved performance when handling large code blocks in the Editor.`),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.48.0 Released!`),
		text(''),
		text('<b>Hey, Anytype Community!</b>'),
		text('Last cycle, we focused on improving Import and Export. This time around it\'s all about <i>polish</i>. We’ve been working through the app, focusing on stability and improvements, including a surprising number of scroll-related bugs (who knew scrolling could be so dramatic?)'),
		text('This release is packed with fixes that should make your daily flow noticeably better. As always, a huge thanks to all of you who reported issues, we seriously couldn’t do this without you.'),
		text('Meanwhile, we’re also putting the final touches on something <i>big</i>. Some of you might already know what’s coming… Stay tuned!'),
		text(''),


		callout(`<b>TL;DR:</b> List View with properties on the right, new ToC menu in the sidebar, 18 quality-of-life improvements and 68+ bug fixes across 16 categories.`, '📃'),

		h2(`Highlights`),

		h3(`Polished List View`),
		text(`We’ve given the List View some well-deserved attention. It’s a simple and practical way to manage your objects, and now it’s smoother to use:`),
		bullet(`<b>Properties now appear on the right-hand side by default, making them easier to scan.`),
		bullet(`You can also place <b>properties before the object name</b>, if that suits your workflow better.`),
		bullet(`<b>In-place editing</b> lets you click a property to edit it on the go, speeding up multi-object workflows.`),
		bullet(`<b>Visual refinements</b> bring a cleaner, more consistent layout.`),
		video('48/1.mp4', 'c70 screen'),
		text(``),

		h3('Table of Contents'),
		text(`A new ToC menu on the right side of the Editor makes it easier to navigate and manage long pages. For a steady overview while editing, you can also open it in the sidebar.`),
		text(`Thanks for the contribution, @${link('https://github.com/anyproto/anytype-ts/pull/1493', 'CamilleHbp')}!`),
		video('48/2.mp4', 'c70 screen'),
		text(''),

		h2(`Quality of Life Improvements`),
		text(''),

		text('<b>Add Properties in Kanban and Calendar Views</b>'),
		text(`You can now quickly add a new property directly from the Layout menu when configuring ${hl('Group by')} in Kanban or ${hl('Date Property')} in Calendar view.`),
		img(`48/1.png`, 'c70 screen'),
		text(''),

		text('<b>Year Filters for Date Properties</b>'),
		text(`When working with projects across years, you can now filter by <i>Last Year</i>, <i>Current Year</i> or <i>Next Year</i> – no need to manually enter date ranges.`),
		img(`48/2.png`, 'c70 screen'),
		text(''),

		text('<b>Bookmark Preview Before Creation</b>'),
		text(`When adding a bookmark, you’ll now see a preview of the link and have the option to include page content. This helps ensure you’re saving what you expect.`),
		img(`48/3.png`, 'c70 screen'),
		text(''),

		text('<b>Auto-Filled Link Input with Selected Text</b>'),
		text(`When you create a link with text selected, the selected text now pre-fills the input field, making link creation much faster.`),
		text(`Thanks to @${link('https://community.anytype.io/t/highlight-and-auto-populate-texts-in-link-cmd-ctrl-k-menu/26408/4', 'sturdily')} & @${link('https://community.anytype.io/t/highlight-and-auto-populate-texts-in-link-cmd-ctrl-k-menu/26408', 'C.c')}!`),
		img(`48/4.png`, 'c50 screen'),
		text(''),

		text('<b>Spotify Embeds</b>'),
		text(`You can now embed a fully playable Spotify player in your pages using the new embed block.`),
		text(`Thanks for the contribution, @${link('https://github.com/anyproto/anytype-ts/pull/1530', 'phil-gru')}!`),
		img(`48/5.png`, 'c50 screen'),
		text(''),

		text('<b>Sticky Space Widget During Scroll</b>'),
		text(`The system Space Widget now remains visible when scrolling through widgets. This ensures the most important actions stay accessible.`),
		text(`Thank you for the suggestion @${link('https://community.anytype.io/t/make-the-space-widget-fixed/26539', 'VisualNotes')}!`),
		text(''),

		text('<b>Add Widget Context Menu: Create Objects Instantly</b>'),
		text(`When no matching results appear in the ${hl('Add Widget')} search, you can now create a new object directly from your input, and a widget will be added for it right away.`),
		text(''),

		text('<b>Pin Spaces in the Vault</b>'),
		text(`Keep your most important Spaces at the top of the Vault for quicker navigation. Right-click the icon of a Space to open the pin/unpin option, and drag to reorder them as needed.`),
		text(''),

		text('<b>Jump to a Space Shortcut</b>'),
		text(`Quickly switch between your first 9 Spaces using ${hl('⌘ + 1–9')} (or Ctrl on Windows/Linux).`),
		text(''),

		text('<b>Keyboard Shortcuts for Text Color & Highlight</b>'),
		text(`Cycle through color and highlight options using new shortcuts: ${hl('⌘ + ⇧ + C')} for text color and ${hl('⌘ + ⇧ + H')} for highlight (reassignable in settings).`),
		text(`Thanks to @${link('https://community.anytype.io/t/27783', 'LarsB24')}!`),
		text(''),

		text('<b>Improved Sorting on Manual Reordering in Collections</b>'),
		text(`Manually reordering objects in a Collection now removes existing sorting rules upon confirmation. This ensures the new order is preserved and avoids conflicts in the sorting logic.`),
		text(''),

		text('<b>Default Sorting by Creation Date</b>'),
		text(`When no sort is applied in a View, new objects are now automatically sorted by their creation date in descending order.`),
		text(''),

		text('<b>Updated Accent Colors</b>'),
		text(`We tweaked our accent color palette for improved consistency across light and dark themes.`),
		text(''),

		text('<b>Auto-Open File Picker When Inserting Media</b>'),
		text(`When you use the ${hl('/ command')} menu to add an image, file or video block, the correct system picker will now open automatically, skipping an extra click.`),
		text(''),

		text('<b>New Shortcut for Copying Deeplinks</b>'),
		text(`You can now assign a custom shortcut to copy an object’s deeplink from anywhere in the app.`),
		text(`Thanks to @${link('https://community.anytype.io/t/copy-deeplink-shortcut/28203', 'siousu')}!`),
		text(''),

		text('<b>Improved LaTeX Handling in Text</b>'),
		text(`LaTeX formatting is now more precise: accidental use of ${hl('$')} symbols won’t unexpectedly trigger math mode.`),
		text(`Thanks to @${link('https://community.anytype.io/t/incorrect-interpretation-of-the-syntax-of-inline-formulas-symbols-issue/26014', 'Snomstor')}!`),
		text(''),

		text('<b>YouTube Links from Embeds</b>'),
		text(`Clicking the YouTube logo in an embedded video now opens the video in your browser, making it easier to switch to YouTube when needed.`),
		text(`Thanks to @${link('https://community.anytype.io/t/watch-on-youtube-not-working/23814', 'Khang')}!`),
		text(''),

		text('<b>Updated Figma Embed Interface</b>'),
		text(`We’ve repositioned the Edit button in Figma embed blocks so it no longer overlaps with the Fullscreen button.`),
		text(`Thanks to ${link('https://community.anytype.io/t/embed-edit-button-overlaps-with-embed-fullscreen-button/26390', '@Obe and @Felipe')}!`),
		text(''),

		h2(`Bug Fixes`),
		text(''),

		text('<b>Editor</b>'),
		bullet(`The text tools menu no longer appears while holding ${hl('Shift')} to select multiple lines, preventing it from blocking your view. Thanks to @${link('https://community.anytype.io/t/prevent-the-text-tools-menu-if-shift-is-pressed/20626', 'Code-Jack')}!`),
		bullet(`Selecting a block to insert no longer causes the menu to scroll erratically. Thanks to @${link('https://community.anytype.io/t/28388', 'VisualNotes')}!`),
		bullet(`Cancelling a drag-and-drop operation no longer causes glitches or block duplication.`),
		bullet(`No part of an object title remains selected after using ${hl('Ctrl+X')}. Thanks to @${link('https://community.anytype.io/t/part-of-a-title-remains-selected-after-cutting-a-part-of-that-title/28335', 'Code-Jack')}!`),
		bullet(`Double-clicking or pressing ${hl('Enter')} while creating a mention no longer results in duplicated text or mention blocks.`),
		bullet(`Locked pages now correctly block edits. Thanks to @${link('https://community.anytype.io/t/28281', 'danddinh')}!`),
		bullet(`Fixed an issue where editing a page body and then reselecting the same page via a widget would erase the recent changes.`),
		bullet(`${hl('Ctrl + Shift + Up/Down')} now properly reorders rows in simple tables. Thanks to @${link('https://community.anytype.io/t/19164', 'Code-Jack')}!`),
		bullet(`Pasting a URL before a mention no longer breaks the formatting or duplicates the content. Thanks to @${link('https://community.anytype.io/t/25187', 'Alan71')}!`),
		bullet(`Deleting a block no longer scrolls the page back to the top.`),
		bullet(`Fixed a bug where moving a block between columns could cause it to become unresponsive.`),
		bullet(`Resolved an issue where rapidly switching pages caused Chinese input to be lost. Thanks to @${link('https://community.anytype.io/t/28343', '4thHydro')}!`),
		text(''),

		text('<b>Performance</b>'),
		bullet(`Fixed a crash caused by recursive widget structures when loading complex pages.`),
		bullet(`Resolved a freeze that occurred when opening notes with embedded audio recordings. Thanks to @${link('https://community.anytype.io/t/workspace-freeze-when-opening-notes-with-audio-recordings/28161', 'Miguel.Vo')}!`),
		bullet(`Optimized loading of large collections so that RAM usage and load times stay consistent, even after repeated access.`),
		bullet(`Opening a page with an embedded FLAC audio file in a modal window no longer causes the app to freeze. Thanks to @${link('https://community.anytype.io/t/28358', 'VisualNotes')}!`),
		text(''),

		text('<b>Workspace Management</b>'),
		bullet(`Removed users no longer retain access to a space if it was open at the time of removal.`),
		text(''),

		text('<b>Navigation</b>'),
		bullet(`Fixed an issue where the previously opened space couldn't be reopened after visiting App Settings.`),
		bullet(`Fixed issues with keyboard navigation and scrolling after DnD actions in Filter, Sort and Group settings menus in List and Kanban views.`),
		bullet(`The ${hl('Back')} button works correctly when returning from Preferences. Thanks to @${link('https://community.anytype.io/t/sometimes-no-back-from-the-preferences/28076', 'Code-Jack')}!`),
		bullet(`Fixed unresponsive top navigation buttons (${hl('Back')}, ${hl('Forward')}, ${hl('Graph')}) after clicking a link to another object. Thanks to @${link('https://community.anytype.io/t/buttons-not-working/28207', 'cameronray')}!`),
		bullet(`Fixed an issue where arrow key navigation in the ${hl('/ command')} menu didn't scroll to the bottom of the list.`),
		text(''),

		text('<b>Links</b>'),
		bullet(`Fixed an issue where links to local files or folders on macOS would break if the path contained spaces.`),
		bullet(`Dragging and dropping an object link onto itself no longer creates a self-link. Thanks to @${link('https://community.anytype.io/t/26722', 'siousu')}!`),
		bullet(`${hl('Paste as link')} is no longer hidden behind the formatting pane when pasting URLs. Thanks to @${link('https://community.anytype.io/t/15656', 'Salsa')}!`),
		bullet(`Editing multiple links on the same line no longer causes some of them to disappear. Thanks to @${link('https://community.anytype.io/t/editing-multiple-links-on-one-line-will-cause-some-of-them-to-be-lost/21134', 'Ming_anytype')}!`),
		bullet(`Fixed ${hl('file://')} links with special characters (like é, à) so they now open correctly. Thanks to @${link('https://github.com/anyproto/anytype-ts/issues/1214', 'thibaudba')}!`),
		bullet(`Fixed an issue where links containing ${hl('<')} or ${hl('>')} characters broke formatting due to incorrect parsing.`),
		text(''),

		text('<b>Shortcuts</b>'),
		bullet(`${hl('Zoom in/out')} via shortcut now works correctly on German keyboards. Thanks to @${link('https://community.anytype.io/t/28085', 'Code-Jack')}!`),
		bullet(`Fixed several broken keyboard shortcuts, including ${hl('Ctrl + N')}, ${hl('Ctrl + K')} and ${hl('Ctrl + Alt + O')}. Thanks to @${link('https://community.anytype.io/t/some-shortcuts-dont-work/27722', 'Code-Jack')}!`),
		text(''),

		text('<b>Views</b>'),
		bullet(`After creating a new object via built-in type Queries, the cursor now appears in the title field. Thanks to @${link('https://community.anytype.io/t/cursor-removed-after-adding-new-object-in-built-in-type-queries/28289', 'sandyeggo')}!`),
		bullet(`Changing a column's width in a Query no longer causes it to move position.`),
		bullet(`Scrolling a table in Grid layout no longer clears unsaved input. Thanks to @${link('https://community.anytype.io/t/scrolling-a-table-clears-unsaved-input/27492', 'spiffytech')}!`),
		bullet(`Converting a Note to another type in a modal window no longer scrolls the background to scroll. Thanks to @${link('https://community.anytype.io/t/28129', 'Code-Jack')}!`),
		bullet(`Menus in Grid and List views no longer overflow over the sidebar when scrolling horizontally.`),
		text(''),

		text('<b>Search</b>'),
		bullet(`Fixed a visual glitch where the placeholder text in the search bar would overlap the first typed character.`),
		bullet(`Fixed an issue where search in the Gallery view didn't return expected results.`),
		text(''),

		text('<b>Widgets</b>'),
		bullet(`Fixed inconsistent behavior where hovering over ${hl('Create New Object')} and moving the cursor below could close the widget creation popup.`),
		bullet(`The space widget now prevents overlapping text from other widgets while editing.`),
		bullet(`Fixed a bug where creating a new object via the Object Widget resulted in duplicated block IDs. Thanks to @${link('https://community.anytype.io/t/page-widget-create-new-object-behaves-strangely/28078', 'VisualNotes')}!`),
		bullet(`Newly created objects within the Collection Widget correctly appear in the related collection. Thanks to @${link('https://community.anytype.io/t/collection-widget-newly-created-objects-dont-get-added/28126', 'krst')}!`),
		text(''),

		text('<b>Sidebar</b>'),
		bullet(`Sidebar scrolls automatically when dragging and dropping widgets.`),
		bullet(`Resizing the sidebar while auto-show/hide is enabled no longer causes it to close unexpectedly.`),
		text(''),

		text('<b>Types</b>'),
		bullet(`The layout width slider now displays and updates values correctly when adjusted. Thanks to @${link('https://community.anytype.io/t/0-47-40-beta-setting-the-exact-default-page-type-width-is-currently-based-on-guessing/28342', 'VisualNotes')}!`),
		bullet(`Type icons from the ${hl('Icon')} category update and display properly in settings.`),
		bullet(`Fixed an issue where object types couldn't be viewed or changed while editing a Type with Properties set to List view. Thanks to @${link('https://community.anytype.io/t/unable-to-view-or-change-object-type-when-editing-type-properties-view-set-to-list/28094', 'vizou')}!`),
		bullet(`Removed the ${hl('Edit Type')} button for Templates and Space member Types.`),
		bullet(`The ${hl('Save')} button now works correctly when setting an image as a type icon in Type Settings.`),
		text(''),

		text('<b>Properties</b>'),
		bullet(`Fixed a problem where renaming a tag would cancel the input mid-edit, especially when typing slowly. Thanks to @${link('https://community.anytype.io/t/issue-with-renaming-tags/28108', 'Code-Jack')}!`),
		bullet(`After pasting a valid date into a property, the picker now closes properly once the value is accepted. Thanks to @${link('https://community.anytype.io/t/28282', 'Code-Jack')}!`),
		text(''),

		text('<b>Sync Status</b>'),
		bullet(`Scroll no longer breaks in the sync status menu.`),
		bullet(`The sync status menu properly displays both files and other syncing items.`),
		text(''),

		text('<b>Sorting</b>'),
		bullet(`Fixed improper alphabetical sorting of properties options that contain numbers.`),
		bullet(`Times set to 00:00 are now correctly ordered within date/time property sorting. Thanks to @${link('https://community.anytype.io/t/24378', 'C.c')}!`),
		bullet(`Fixed inconsistent behavior when sorting by the ${hl('Done')} relation.`),
		text(''),

		text('<b>Settings</b>'),
		bullet(`Fixed an issue where drag-and-drop didn't behave correctly when changing the Default Object Type.`),
		bullet(`Improved scroll behavior in Remote Storage settings. Thanks to @${link('https://community.anytype.io/t/27889', 'telmob')}!`),
		bullet(`The pin code settings window now updates correctly after disabling the pin code.`),
		bullet(`For accounts created in Local-Only Mode, the Vault Deletion section has been removed from Settings, since this action isn't relevant in local-only use.`),
		text(''),

		text('<b>TOC</b>'),
		bullet(`Clicking a Table of Contents entry now correctly jumps to content inside closed toggles. Thanks to @${link('https://community.anytype.io/t/toc-does-not-jump-into-a-closed-toggle/28230', 'Code-Jack')}!`),
		bullet(`Fixed an issue where the Table of Contents popup didn't appear next to Inline Queries using Grid or Kanban layouts. Thanks to @${link('https://community.anytype.io/t/toc-popup-doesnt-show-on-page-when-next-to-an-inline-query-with-layout-set-to-grid-or-kanban/28250', 'Jimlaurie')}!`),
		text(''),

		text('<b>Embeds</b>'),
		bullet(`Links to SVG embeds like Drawio work as expected. Thanks to @${link('https://community.anytype.io/t/28189', 'Shampra')}!`),
		bullet(`Codepen embeds now render correctly in iframe blocks.`),
		bullet(`Figma links now open in your browser as expected. Thanks to @${link('https://community.anytype.io/t/26389', 'Obe')}!`),
		text(''),

		text('<b>Media</b>'),
		bullet(`Downloading an image now saves the original resolution.`),
		bullet(`Fixed an issue where bookmark thumbnails appeared in search but couldn't be deleted or located in Queries or the Bin. Thanks to @${link('https://community.anytype.io/t/bookmark-thumbnails-ghosts/28040', 'dxn0')}!`),
		text(''),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.47.4 Released!`),
		text(''),
		text('At Anytype, we’re committed to true user ownership of data. As a local first software, your information stays with you, independent and accessible for the long term. We want to bring our community a strong sense of reassurance, which is why we’ve made our Markdown support more robust: so your notes and ideas can go wherever you need, now and far into the future.'),
		text(''),

		h2(`Markdown Export: Properties and Types`),
		text(`Exporting your data to Markdown now includes properties and types. This ensures your ${hl('.md')} backups are more complete and your information remains organized, without losing important context. Since Markdown is the most widely supported format across software, it’s a reliable way to keep your data portable and under your control.`),
		text(''),

		h2(`Markdown Import: Smoother Transitions`),
		text('Markdown import also supports properties and types, improving the way you bring your data back into Anytype. This update includes support for <b>importing properties from Obsidian</b> and simplifies moving your notes and projects from applications like Evernote, Bear and others, with less need for manual setup.'),
		text(''),
		text('This is a new iteration and it’s not the last. Your feedback guides us, please let us know what works and what’s missing. More improvements are on the way!'),

		text(''),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.47.0 Released!`),
		text(''),
		text('This update brings a range of improvements across the app, from visual refinements to quality of life updates, all designed to make your experience smoother and more consistent. In the meantime, we’re continuing our ongoing work to support data ownership, easier backups and long-term resilience.'),
		text(''),

		h2(`Highlights`),

		h3(`Import Improvements`),
		text(`Obsidian import supports ${hl('[[double bracket]]')} links, allowing internal links to be correctly converted to object links in Anytype. The ${hl('[[')} shortcut is also supported inside Anytype for linking between objects.`),
		img(`47/1.png`, 'c70'),
		text(``),


		h3(`Sidebar Design Refresh`),
		text(`We’ve refreshed the Sidebar with several design and usability improvements:`),
		bullet(`The <b>${hl('New')} button</b> for creating objects has a new design`),
		bullet(`<b>Favorites</b> have been renamed to <b>Pinned</b>, with a new icon and updated empty state`),
		bullet(`<b>Help menu ${hl('?')}</b> has been moved to the bottom of the sidebar`),
		bullet(`The <b>Bottom bar</b> now has a transparent gradient for a smoother visual transition`),
		img(`47/2.png`, 'c70'),
		text(``),

		h3('<b>Type Links in Graph</b>'),
		text('New setting to connect Types to Objects has been added to the Graph.'),
		img(`47/5.png`, 'c70'),
		text(''),

		h2(`Quality of Life Improvements`),
		text(''),

		text('<b>Quick Access to Templates</b>'),
		text(`You can now manage templates directly from the Edit Type menu, accessible from every object.`),
		img(`47/3.png`, 'c70'),
		text(''),

		text('<b>Header Properties Column View</b>'),
		text('Added column view for the properties displayed in the object header, which you can switch to from the line view when editing a Type layout.'),
		img(`47/4.png`, 'c70'),
		text(''),

		text('<b>Bookmark Paste Menu</b>'),
		text(`Creating a new object with the Bookmark type now instantly opens the ${hl('Paste link')} menu.`),
		img(`47/6.png`, 'c40'),
		text(''),

		text('<b>Add to Pinned</b>'),
		text(`The new ${hl('Add to Pinned')} button in the navigation bar lets you quickly save objects to the Pinned widget (formerly Favorites).`),
		img(`47/7.png`, 'c40'),
		text(''),

		text('<b>Draw.io Embeds</b>'),
		text(`Draw.io diagrams are now supported in embed blocks. Big thanks to @${link('https://github.com/anyproto/anytype-ts/pull/1399', 'Shampra')} for the contribution!`),
		text(''),

		text('<b>Improved Sorting Logic</b>'),
		text('Ascending sort now places empty values at the end by default.'),
		text(''),

		text('<b>Type Page Default View</b>'),
		text('The Type page was updated to use List view by default.'),
		text(''),

		text('<b>Calendar Drag and Drop</b>'),
		text('You can now drag and drop objects in the Calendar when using a custom date property.'),
		text(''),

		text('<b>New Shortcuts</b>'),
		text('Added new shortcuts to create Widgets, open Space settings, Pin / Unpin objects, open Bin and more.'),
		text(''),

		text('<b>Access Pop-up Update</b>'),
		text('Updated the "No access to this space" pop-up with clearer messaging and a new icon.'),
		text(''),

		text('<b>Space Name and Description Limits</b>'),
		text('Set character limits for Space name (50) and description (200).'),
		text(''),

		h2(`Bug Fixes`),
		bullet(`Addressed an issue where using Raycast snippets in empty object titles on macOS added an unintended new line. Thanks to @${link('https://community.anytype.io/t/raycast-snippet-issue-in-object-titles-macos/27209', 'Simon Lanz')}!`),
		bullet(`Fixed a bug where using a reassigned CapsLock key caused selected blocks to be deleted instead of copied. Thanks to @${link('https://community.anytype.io/t/cant-copy-blocks-with-reasigned-capslock/26603', 'pytat0')}!`),
		bullet(`Fixed a macOS issue where the Finder window didn’t close automatically after uploading a Space profile image. Thanks to @${link('https://community.anytype.io/t/uploading-image-to-space-profile/23537', 'Khang')}!`),
		bullet(`Fixed an issue where text selection in the Editor would break when autoscroll was triggered, causing the start and end points to shift unexpectedly. Thanks to @${link('https://community.anytype.io/t/marking-a-text-area-with-the-mouse-autoscroll-causes-problem/18769', 'Code-Jack')}!`),
		bullet(`Text selection now works correctly in formatted blocks: highlighting part of a bold, italic or underlined string no longer selects the entire block. Thanks again to @${link('https://community.anytype.io/t/formatted-substring-marking-with-the-mouse-does-always-select-the-whole-block/24586', 'Code-Jack')}!`),
		bullet(`Fixed a visual glitch where a horizontal line briefly appeared at the top of Queries and Collections when switching from another page. Thanks to @${link('https://community.anytype.io/t/weird-horizontal-line-glitch-on-top-of-sets-and-collections/24852', 'Divinity')}!`),
		bullet(`The text cursor no longer disappears when clicking on or near emphasized text (such as underlined or italic) from a block in the Editor. Thanks to @${link('https://community.anytype.io/t/cursor-disappears-when-clicking-into-blocks-on-emphasis-text/26381', 'zewwo')}!`),
		bullet(`Newly added properties now appear in the menu when selecting which properties to display in a view on the Type page. Thanks to @${link('https://community.anytype.io/t/added-properties-dont-show-up-in-built-in-object-list-of-type/27606', 'r0the')}!`),
		bullet(`Locked objects fully prevent all changes to Properties. Thanks to @${link('https://community.anytype.io/t/its-possible-to-change-properties-of-an-object-on-a-locked-page/27909', 'VisualNotes')}!`),
		bullet(`Fixed a bug where the Description field was incorrectly shown in the header. Thanks to @${link('https://community.anytype.io/t/description-stuck-in-header/28007', 'sandyeggo')}!`),
		bullet(`Fixed an issue where the "Name" property was missing in Queries created via widgets. Thanks to @${link('https://community.anytype.io/t/name-property-not-seen-in-sets-created-through-widgets/27656', 'HarshaRaj')} & @${link('https://community.anytype.io/t/name-property-not-displayed-in-grid-and-gallery-views-in-old-spaces/27949', 'BadWorld')}!`),
		bullet(`Improved performance when switching between Grid and Gallery views with a large number of objects in the Query. Transitions are now smoother and more responsive. Thanks for the detailed report @${link('https://community.anytype.io/t/15-seconds-lag-while-switching-from-a-giant-grid-view-to-a-small-gallery-view/28017', 'Code-Jack')}!`),

		bullet(`Clearing date properties works correctly when using bulk edit in Grid view. Thanks to @${link('https://community.anytype.io/t/date-relations-cant-be-cleared-when-doing-a-bulk-edit-of-the-relation-in-a-grid-view/27432', 'garyp')}!`),
		bullet(`Search now works correctly in Queries that were previously Sets before the new structure migration. Thanks to @${link('https://community.anytype.io/t/search-broken-for-queries/27467', 'stendekoniko')}!`),
		bullet(`Changing bullets to checkboxes now correctly applies to all selected items, including multi-level lists. Thanks to @${link('https://community.anytype.io/t/changing-bullets-to-checkboxes-in-bulk-doesnt-change-whole-selection/27825', 'spiffytech')}!`),
		bullet(`Resolved an issue where some Queries could appear reset. Thanks to @${link('https://community.anytype.io/t/some-queries-are-reset-after-updating-to-0-46-21-beta/27845', 'boots')}!`),
		bullet(`Resolved an issue where some Templates were not displayed for certain Types. Thanks again to @${link('https://community.anytype.io/t/loss-of-templates-after-updating-to-0-46-21-beta/27843', 'boots')}!`),
		bullet(`Fixed a bug where some objects could appear without a title and showed as "Untitled".`),

		bullet(`Vertical videos maintain their correct orientation when resized.`),
		bullet(`Opening a Property in the settings no longer causes the title bar to flicker when the window is narrow.`),
		bullet(`Fixed an issue where switching Spaces after unlocking the app with a PIN code didn’t work on the first attempt.`),
		bullet(`Fixed drag-and-drop behavior for Properties in the ${hl('Edit Type')} menu within the modal window.`),
		bullet(`Fixed an issue where the Name column in a Query could shift when rearranging other columns in the modal window.`),
		bullet(`Lock icon is no longer shown on Types for users with Viewer access.`),
		bullet(`Profile icons now display with the correct background in Widgets.`),
		bullet(`Objects permanently deleted via the sync menu now close automatically.`),
		bullet(`Switching to the backlinks in Global Search no longer causes the selection to reset while navigating results with the keyboard.`),
		bullet(`Navigation back works correctly after clicking a link to an object in the Editor.`),
		bullet(`Switching to Kanban in view Settings no longer causes layout issues in the Settings menu.`),
		bullet(`Long titles from Notes are now correctly displayed in the top navigation bar.`),
		bullet(`Fixed an issue where Select and Multi-select property searches didn’t work on locked pages.`),

		text(''),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.46.6 Released!`),
		text(''),
		text('This release marks an exciting and long-awaited moment in Anytype’s evolution: the <b>first iteration of our Local API</b> is here! It opens up powerful new possibilities for an ecosystem of plugins, automations and third-party integrations.'),
		text('Alongside this launch, we’re polishing the new structure around Types, delivering performance fixes and enhancing workflows with an upgraded Raycast extension.'),
		text(''),

		h2(`Anytype Local API (Developer Preview)`),
		text(''),
		text('Our API is now available and directly included with the desktop app, running entirely on localhost. It operates fully offline, meaning you can build and use integrations without any cloud dependencies - even while flying!'),
		text('This initial release targets developers, and we’re eager to see what the community creates with it!'),
		text(''),

		h3(`Key Highlights`),
		bullet(`<b>Secure Authentication</b>: Authenticate once via a 4-digit challenge in the desktop app, generating an API key. This key acts as a bearer token to authenticate subsequent requests. Additionally, API keys can be managed and generated directly through the desktop client's settings, making it easy to share keys with third-party integrations.`),
		bullet(`<b>Comprehensive Documentation</b>: The OpenAPI specification and full documentation are available on our new ${link('https://developers.anytype.io/', 'Developer Portal')}.`),
		bullet(`<b>Robust API Capabilities</b>: Endpoints offer core Anytype functionality: creating objects, editing, querying and much more.`),
		bullet(`<b>Growing Developer Ecosystem</b>: Early SDKs and community-driven tools are already underway: Python and Go clients, MCP server and Raycast extension.`),
		text(''),

		callout(`<b>Important Security Notice</b>: By providing an API key or using extensions, you grant limited access to your Anytype vault, enabling operations such as editing or deleting objects. Ensure you <b>use only trusted extensions</b>.`, '⚠️'),
		text(''),

		h2(`Raycast Extension Updates`),
		text(''),
		text('As a companion to our Local API, we’ve just shipped great improvements for our Raycast extension.'),
		text('Here’s what’s new:'),
		bullet(`<b>Quickly create</b> new spaces, objects, types, properties, or tags with the shortcut ${hl('CMD+N')} while browsing your spaces.`),
		bullet(`<b>Easily edit</b> your selected items (spaces, objects, types, properties or tags) using ${hl('CMD+E')}.`),
		bullet(`<b>Conveniently add objects</b> to lists either through the new ${hl('Add object to list')} command or directly from the context menu ${hl('CMD+K')}.`),
		img(`46.x/1.jpg`, 'c70'),
		text(''),

		h2(`Quality of Life Improvements`),
		text(''),

		text('<b>Extra safety step for deleting</b>'),
		text('To help prevent accidental deletions, space removal now includes an added confirmation layer.'),
		text(''),

		text('<b>Improved date interactions in widgets</b>'),
		text('Added an expand icon and helpful hover cues in calendar widgets to make date menus more discoverable.'),
		text(''),


		text('<b>Optimized widget behaviour</b>'),
		text('Widgets are now preserved when switching between spaces, and adding new objects works more smoothly.'),
		text(''),


		text('<b>Adjusted property picker in Query menu</b>'),
		text('Minor UX improvements for a more intuitive setup.'),
		text(''),

		h2(`Bug Fixes`),
		bullet(`Fixed an issue where some objects were not being indexed by the full-text search engine.`),
		bullet(`Resolved a bug causing type objects to not persist after app restart.`),
		bullet(`Fixed text deletion in the Description field.`),
		bullet(`Fixed misplaced volume bar. Thanks for flagging it, @${link('https://community.anytype.io/t/volume-bar-is-misplaced/27771/1', 'Shoyo')}!`),
		bullet(`Typing in Date fields works as expected (<i>no more 31.12.1969 issues!</i>). Thanks for the heads-up, @${link('https://community.anytype.io/t/can-t-manually-type-in-a-date/27724', 'natanyberry')}!`),
		bullet(`Icons now appear correctly in Queries.`),
		bullet(`Kanban views display correctly in widgets.`),
		bullet(`Fixed cursor jumping to the beginning of the line in the type creation panel.`),
		bullet(`Fixed objects displaying in Kanban when opened in modal window.`),
		bullet(`Improved drag-and-drop and block insertion behaviour in column layouts. Thanks for reporting, @${link('https://community.anytype.io/t/two-bugs-with-content-in-columns-on-a-page-solved/27337', 'VisualNotes')}!`),
		bullet(`Fixed incorrect pop-up link positioning in text.`),
		bullet(`Improved performance when renaming images in Gallery view. Thanks to @${link('https://community.anytype.io/t/its-a-pain-to-rename-pictures-in-the-gallery-view-if-you-have-lots-of-objects-loaded/24461', 'Code-Jack')}!`),
		bullet(`Fixed issue preventing blocks from being moved into the end position of a toggle. Yet another great catch from @${link('https://community.anytype.io/t/toggles-impossible-to-move-a-block-from-outside-into-the-toggle-at-the-end-position/27715', 'Code-Jack')}!`),
		bullet(`Unable to delete bullet points – resolved.`),
		bullet(`Multi-line selection is no longer replaced by the key-name (e.g. ${hl('PageDown')}).`),
		bullet(`Opening Preferences from a modal window no longer causes a blank screen. Thanks for catching it, @${link('https://community.anytype.io/t/modal-open-open-preferences-all-blank/27801', 'krst')}!`),
		bullet(`Fixed severe scroll jump when switching views in inline Queries.`),
		bullet(`Empty names no longer appear when the singular form of a Type name is unset.`),
		bullet(`Fixed issue preventing properties from being placed at the first or last position within a section in the panel.`),
		text(''),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.46.0 Released!`),
		text(''),
		text('Hi dear Anytypers!'),
		text(`We're thrilled to announce a major update and introduce a fundamental shift in Anytype's core organizing structure. We\'re streamlining our user experience by eliminating the current behavior and bringing a clearer, more intuitive way to use <b>Types</b>.`),
		text('The new Anytype reimagine Types. Now, you can define layouts and properties within a Type and all associated objects will automatically inherit these settings.'),
		text('Along with this transformation, we’ve included many new improvements and bug fixes.'),
		text(`Add objects to lists using the new "Add object to list" command, or from the context menu.`),

		h2(`Meet the new Anytype`),
		text(``),

		bullet(`<b>Relations</b> are now called <b>Properties</b>.`),
		bullet(`<b>Sets</b> are now called <b>Queries</b>.`),
		bullet(`<b>Types</b> are now the primary structure of objects, determining all attached properties.`),
		bullet(`<b>Properties</b> that were previously set at the object level are now defined by Type, including both featured properties, such as backlinks or tags, and specific ones, such as date or source.`),
		bullet(`<b>Templates</b> will now focus only on the content of objects, primarily organizing blocks. Adding blocks, setting a cover or assigning an icon are now key aspects of creating a template. Properties are managed separately at the Type level. Changing a property at the Type level will affect all objects of that Type.`),
		bullet(`<b>Layout</b> of an object is also defined by its Type. For example, all Task objects will follow the same layout, and you won’t be able to customize them individually. If you need a different layout with a center header position or increased width, you should create a new Type.`),
		video(`46/1.mp4`),
		text(``),

		h3(`Queries for Types`),
		text(`Each Type page now comes with a built-in inline Query, making it easier to access and organize related objects.`),
		text(``),

		h3(`Templates for Queries and Collections`),
		text(`You can save and reuse your configurations, including view settings, applied filters, cover and icon. Just like with regular objects, select ${hl('Use as Template')} from the three-dots menu or add templates via the Query or Collection Type page.`),
		text(``),

		h3(`Right Sidebar and Set Up Menu`),
		text(`The <b>Properties</b> icon lets you view, add and remove values to the properties of a specific object. `),
		text(`The ${hl('Edit type')} button allows you to manage the properties of its Type. From there you can add, remove and organize them into different sections:`),
		bullet(`<b>Header</b> properties appear in the header part of every object of that Type.`),
		bullet(`<b>Sidebar</b> properties are the ones you choose to show in the Properties panel.`),
		bullet(`<b>Hidden</b> properties live under the ${hl('Show more')} button.`),
		bullet(`<b>Local</b> properties: After updating to the new version or when changing an object’s Type, some properties (formerly relations) might not match the new Type’s predefined structure. Properties that were once unique to individual objects will now appear as local properties. You can either unify them by adding them to the Type or create a new Type, if you need.`),
		text(``),
		text(``),

		h2(`Quality of Life Improvements`),
		text(``),

		h3(`New Icons for Types`),
		text(`Custom icons can now be assigned at the Type level, making it easier to identify whether you are working with Types or Objects. You can now choose from a dedicated collection of hundreds of fresh icons for a consistent and structured look.`),
		img(`46/2.png`, 'c70'),
		text(``),

		h3(`Type Widgets`),
		text(`You can now add widgets based on object Types, making it easier to organize and display relevant content. We’ve also introduced <b>Automatic Widget</b> creation to help users seamlessly discover and adopt widgets, creating a more personalized and intuitive workspace.`),
		bullet(`When you create the first object of a Type, a dedicated widget is automatically added to your sidebar. This widget displays all objects of that Type within the space, giving you quick access without any extra setup.`),
		bullet(`<b>Automatic Widgets are optional</b> – you can remove any widget at any time via ${hl('Edit')} button or by right-clicking. Once removed, they won’t reappear unless manually added. Automatic widget creation can also be disabled in Settings.`),
		img(`46/3.png`, 'c70'),
		text(``),

		h3(`Settings Update`),
		text(`Both General and Space Settings have been updated to a full-page layout instead of a pop-up, with sections now located in the left sidebar. `),
		text(`As part of this update, Types and Properties now live in your Space Settings, bringing everything related to your space configuration into one place.`),
		img(`46/4.png`, 'c70'),
		text(``),

		h3(`Custom Shortcuts`),
		text(`We've expanded the number of actions available for keyboard shortcuts, giving you more capabilities than ever before. Most shortcuts are customizable, and certain actions support two different key combinations for more flexibility.`),
		img(`46/5.png`, 'c70'),
		text(``),

		h3(`Raycast Extension Updates`),
		text(`We've introduced several enhancements based on your requests and feedback, plus Anytype for Raycast is now an <b>AI&nbsp;Extension</b> – search through spaces and objects using natural language or create new ones just by instructing ${hl('@anytype')}.`),
		bullet(`<b>Improved Pinning & Navigation</b>: Pin objects, types, members and spaces for quicker access. Objects of a certain Type now appear below their templates for better organization.`),
		bullet(`<b>Better Collection Management</b>: Create objects directly within collections and browse collection items with ease.`),
		bullet(`<b>Customization & Visibility</b>: Choose ${hl('Open Object in Anytype')} as the default action, show custom properties in the Detail sidebar, toggle metadata in object details and apply templates when creating new objects.`),
		img(`46/6.png`, 'c50'),

		h3(`Choose your Week Start Day`),
		text(`You can now choose whether your week starts on Sunday or Monday. Head to your updated settings to make the switch in the date picker.`),
		text(``),

		h3(`All Objects as a System Widget`),
		text(`The All Objects section is now available as a system widget that can be added or removed from the sidebar. While core functionality like sorting and search remains the same, Types and Properties are now managed from your Space Settings.`),
		text(``),

		h3(`Use [[ to Link in Editor`),
		text(`The editor now supports the ${hl('[[')} syntax for linking. This Markdown pattern works similarly to ${hl('@mention')}, allowing you to reference other objects.`),
		text(``),

		h3(`HTTPS Links for Objects`),
		text(`You can now copy an HTTPS link for any object via the three-dots menu by selecting ${hl('Copy Link')}. Users without the Anytype app can click on these links to download the app and access the object after installation. When opened inside the App, these links directly open the object without any redirection.`),
		text(``),

		h3(`Web Publishing Updates`),
		text(`We continue to refine and optimize the rendering process and have also improved support for layouts including alignment, width and featured properties to align with the new Primitives structure.`),
		text(``),

		h3(`Alert when Switching to the Release Channel`),
		text(`To prevent confusion when switching the release channel, an alert has been added. This alert clarifies that changing the release channel will store data in a separate sub-directory, which may cause unsynced files or objects to become inaccessible.`),
		text(``),

		h3(`Drag-to-Select on Graph Page`),
		text(`Added a drag-to-select feature to the graph page, making it easier to select multiple items at once. Now you can grab and move a bunch of objects with just a simple drag. Many thanks for the contribution to @${link('https://github.com/anyproto/anytype-ts/pull/1211', 'ShirayukiRin')}!`),
		text(``),

		h3(`Type Filters in Graph`),
		text(`In addition to existing clustering by Type, you can now filter the Graph to display only selected object Types – helping you focus on exactly what you need.`),
		text(``),

		h3(`fa-IR Language`),
		text(`Added support for Persian (fa-IR) language as part of our right-to-left language expansion.`),
		text(``),
		text(``),

		h2(`Bug fixes`),
		bullet(`Multiple open windows no longer revert to the login screen or display a black screen after the device resumes from suspension. Thanks to @${link('https://community.anytype.io/t/black-screen-multiple-windows-after-suspend/25878', 'krst')} & @${link('https://community.anytype.io/t/some-windows-returned-to-login-screen/20865', 'C.c')}!`),
		bullet(`Default Object Type remains set. This issue was detected again and resolved after fixing the initialization problem. Thanks for the heads-up, @${link('https://community.anytype.io/t/default-object-type-keeps-changing-to-page/25748', 'zma17')}!`),
		bullet(`Fixed an issue where the cursor keys could stop working after editing templates in Sets.`),
		bullet(`The pop-up menu when adding a widget closes correctly.`),
		bullet(`Fixed the Grid’s sum function to prevent unnecessary decimal places from appearing in calculations. Thanks for the feedback, @${link('https://community.anytype.io/t/calculating-a-sum-shows-one-zero-too-much/26363', 'Code-Jack')}!`),
		bullet(`Fixed an issue where checking a checkbox would remove LaTeX formatting within the block. Thanks, @${link('https://community.anytype.io/t/inline-latex-breaks-when-placed-in-a-checkbox-that-is-then-checked/26610', 'personnotman')}!`),
		bullet(`Inline LaTeX now correctly renders ${hl('$\\mathbb R$')}, which previously did not display while other letters worked. Double thanks, @${link('https://community.anytype.io/t/inline-latex-mathbb-r-doesnt-work/26781', 'personnotman')}!`),
		bullet(`The ${hl('Show menu bar')} setting works correctly. Thanks, @${link('https://community.anytype.io/t/settings-show-menu-bar-works-incorrectly/25475', 'AndCycle')}!`),
		bullet(`${hl(`${'&#8984;'} + W`)} now correctly closes only the active window on Mac. Thanks, @${link('https://community.anytype.io/t/command-w-closes-the-app-instead-of-the-active-window-mac/23099', 'Kite')}!`),
		bullet(`Files added to Favorites are properly displayed in the widget.`),
		bullet(`Embed Kroki Graphs now scale correctly, preventing them from being cut off. Thanks, @${link('https://community.anytype.io/t/kroki-graphs-cutoff-instead-of-scaled/26875', 'bartl')}!`),
		bullet(`The ${hl('Create new Object')} button in the list view widget for Kanban boards is now working correctly. Thanks, @${link('https://community.anytype.io/t/button-create-new-object-in-list-view-widget-for-kanban-boards-stopped-working-in-anytype-desktop-0-45/26916', 'Self-Perfection')}!`),
		bullet(`The nested long table, when moved inside a column, now displays correctly.`),
		bullet(`Fixed the ${hl('Back to Dashboard')} button on deleted Objects.`),
		bullet(`Fixed hyperlinks in PDF export.`),
		bullet(`Embedded links in Bookmarks are now parsed and rendered correctly when an Object is exported to PDF.`),
		bullet(`The Audio Player timeline is now resized properly in exported PDF.`),
		bullet(`Tables in multiple-column layouts align properly in resized windows without overlapping adjacent columns. Thanks to @${link('https://community.anytype.io/t/issue-with-the-table-in-resized-window/19901', 'cpobharat')}!`),
		bullet(`All Objects panel now remembers the last scroll position when reopened. Thanks, @${link('https://community.anytype.io/t/all-objects-doesnt-remember-the-last-scroll-position/24548', 'Code-Jack')}!`),
		bullet(`Corrected forward navigation in All Objects to be consistently clickable.`),
		bullet(`Horizontal scrolling in All Objects tabs works consistently with external mice.`),
		bullet(`All Objects correctly display the selected tab when opened.`),
		bullet(`Fixed filters in Graph, ensuring Objects with bi-directional links or relations are displayed correctly when the corresponding ${hl('Show on Graph')} option is enabled. Thanks for catching this, @${link('https://community.anytype.io/t/show-relations-filter-from-the-graph-doesnt-work-properly/25196', 'HoneycombGlasses')}!`),
		bullet(`Moving a block out of the Anytype window no longer causes the view to scroll upwards.`),
		bullet(`The ${hl('Create Object')} button in the widget now correctly links the newly created object to the target one.`),
		bullet(`Relations are not displayed anymore after they have been moved to the Bin in the relations panel. Thanks for contributing, @${link('https://github.com/anyproto/anytype-ts/pull/1206', 'ShirayukiRin')}!`),
		bullet(`The Drag-to-Select box has been improved to ensure it displays correctly in sets and collections. Additionally, it now appears when selecting a single block in the editor. Thanks again, @${link('https://github.com/anyproto/anytype-ts/pull/1221', 'ShirayukiRin')}!`),
		bullet(`Fixed incorrect input direction switching on Armenian keyboard.`),
		bullet(`Deleted objects are correctly displayed in the Bin. Thanks, @${link('https://community.anytype.io/t/deleted-objects-are-not-displayed-in-the-bin/27083', 'boots')}!`),
		bullet(`The last active Space opens when launching the App and after refresh. Thanks for flagging this, @${link('https://community.anytype.io/t/last-used-space-is-not-the-space-shown-at-application-startup-when-there-are-multiple-instances-of-anytype/27097', 'C.c')}!`),
		bullet(`Exporting to PDF now consistently reflects the current color scheme in dark mode. If you need an object to be exported as a standard PDF document with a white background while dark mode is enabled, you can use the Printing option instead. Appreciate your report, @${link('https://community.anytype.io/t/exporting-to-pdf-in-dark-mode-creates-different-and-unexpected-results/26235', 'DennisG')}!`),
		bullet(`The calendar selection menu no longer moves when switching months. Thanks to @${link('https://community.anytype.io/t/calendar-selection-menu-moves-when-changing-months/26982', 'Magiccheese1')}!`),

		div(),
		// --------------------------------------------//

		title(`Desktop 0.45.0 Released!`),
		text('Hello Anytypers! We’re excited to share a major update you’ve been eagerly awaiting. Version 0.45.0 introduces Web Publishing, a Raycast extension, RTL support, and a host of quality-of-life improvements — all inspired by your requests and feedback. Thank you for helping us shape Anytype into a friendlier, more powerful tool for everyone.'),
		text(''),

		h2(`Highlights`),
		h3(`Web Publishing`),
		text(`You can now publish Objects as static web pages (HTTPS links) on your personal subdomain if you have *any name. These pages are uploaded to our servers as unencrypted HTML files.`),
		text(`This is an early version — mobile optimization, linked Objects, and blocks like Sets and Collections aren’t supported yet. Multi-page publishing and other enhancements are on the way, and we’d love your feedback to guide these improvements.`),
		img(`45/2.png`),
		text(``),

		h3(`Redesigned Space Panel & Navigation`),
		text(`We’ve relocated the navigation controls to the Space Panel for a smoother experience. You can now navigate back and forth, search for Objects, and create new ones from a familiar place.`),
		text(`Pro tip: if your sidebar is hidden, press ${hl(`${cmd} + S`)} to open Global Search or ${hl(`${cmd} + N`)} to create a new Object.`),
		img(`45/1.png`),
		text(``),

		h3(`Raycast Extension (macOS)`),
		text(`Our long-awaited API is beginning to take shape! The first step is Raycast integration, allowing you to create, read, and delete Spaces, Objects, and Types, as well as search across them, all from Raycast on macOS.`),
		text(`While this initial version focuses on a basic set of features, we’re laying the groundwork for an open API that will eventually support bulk import and export, NoCode tools, and more integrations. We’re excited to see what you’ll build!`),
		text(`${link('https://www.raycast.com/any/anytype', 'Install the Raycast Extension here')}`),
		img(`45/3.png`),
		text(``),

		h3(`RTL Support`),
		text(`We’re happy to introduce right-to-left language support! This first iteration might need some extra polish, so your feedback is invaluable. Let us know what works and what needs a bit more attention.`),
		video(`45/4.mp4`),
		text(``),

		h2(`Quality-of-Life`),
		text(``),
		h3(`Add Existing Objects to a Collection`),
		text(`We’ve added an option to add existing Objects into a Collection. Look for it in the updated arrow menu alongside other content settings.`),
		img(`45/5.png`, `c50`),
		text(``),

		h3(`Horizontal Alignment in Grid Layout`),
		text(`Columns in the Grid layout can now be aligned left, center, or right.`),
		img(`45/6.png`, `c60`),
		text(``),

		h3(`Simplified Widget Settings Menu`),
		bullet(`Appearance options are now limited to changing the widget’s view (Compact List, List, View, Link).`),
		bullet(`The "Number of Objects" setting has moved to its own section.`),
		img(`45/7.png`, `c40`),
		text(``),

		h3(`Clickable Links in Kroki Diagrams`),
		text(`Kroki embed blocks now support links within diagrams. Thanks to @${link('https://community.anytype.io/t/kroki-links-are-not-usable/25543', 'siousu')} for the suggestion!`),
		text(``),

		h3(`Improved Dark Mode Text Selection`),
		text(`We tweaked the selection color for better visibility. Shout-out to @${link('https://community.anytype.io/t/selected-text-background-color-on-a-given-object-heavily-dependent-on-monitor-settings/25509', 'kermit_frog')} for flagging this!`),
		text(``),

		h3(`Inline Set Header Resize Adjustments`),
		text(`Inline Set headers now adapt when resizing to keep controls from overlapping neighboring blocks.`),
		text(``),

		h3(`Better Image Pasting on macOS Safari`),
		text(`Images copied from Safari will now paste into the object editor as files instead of URLs.`),
		text(``),

		h3(`Standardized QR Code Appearance`),
		text(`All QR codes in Anytype now follow a consistent style.`),
		text(``),

		h3(`Improved LaTeX Support`),
		text(`Inline LaTeX is now rendered in the Table of Contents block and in link blocks, including titles and descriptions. Thanks to @${link('https://community.anytype.io/t/inline-latex-not-applied-in-table-of-contents/24056', 'mewald')}!`),
		text(``),

		h2(`Bug Fixes`),
		bullet(`Making changes to Kanban in the Version History is now disabled. Thanks, @${link('https://community.anytype.io/t/making-changes-to-kanban-in-version-history-breaks-all-versions/26141', 'HeavensRegent')}!`),
		bullet(`Resolved an issue that could cause the App to freeze.`),
		bullet(`Dragging headers in the Grid to rearrange columns no longer highlights the text of other headers. Thanks, @${link('https://community.anytype.io/t/moving-column-headers-in-the-grid-to-swap-columns-selects-all-headers/26100', 'Code-Jack')}!`),
		bullet(`Fixed keyboard navigation in the Command menu. Thanks, @${link('https://community.anytype.io/t/adding-a-link-cursor-jumps-too-deep-in-the-selection-box/25763', 'Code-Jack')}!`),
		bullet(`Bin Search works correctly, without causing Objects to be filtered out.`),
		bullet(`Relations containing angle brackets (e.g., ${hl('&lt;abc&gt;')}) are saved correctly. Thanks, @${link('https://community.anytype.io/t/angle-brackets-in-relation-will-disappear-when-clicking-it/25534', 'CoolGuy')}!`),
		bullet(`Input to Date type relations works correctly. Thanks, @${link('https://community.anytype.io/t/date-entry-not-working/26112', 'flypenguin')}!`),
		bullet(`Removed the option to paste YouTube channel links as Embed. Thanks, @${link('https://community.anytype.io/t/pasting-a-link-to-an-yt-channel-paste-as-embed-shouldnt-appear/26297', 'Code-Jack')}!`),
		bullet(`Fixed an issue where pasting with all blocks selected in the object editor would wipe out content without pasting from the clipboard. Thanks, @${link('https://community.anytype.io/t/pasting-when-all-blocks-in-the-object-editor-are-selected-will-wipe-out-everything-but-will-not-paste-whats-in-the-clipboard/25040', 'sky1')}!`),
		bullet(`Copy-pasting relations between Objects using ${hl(`${cmd} + C`)} and ${hl(`${cmd} + V`)} works correctly. Thanks, @${link('https://community.anytype.io/t/fail-to-paste-relations-from-one-object-to-another-by-ctrl-c-v/25809', 'RichardZ')}!`),
		bullet(`Improved behavior of the Command menu when using non-English language with IME. Thanks, @${link('https://community.anytype.io/t/slash-menu-doesnt-always-appear/21879', 'C.c')} and @${link('https://community.anytype.io/t/multiple-functions-not-working-after-inputted-or-using-cangjie/25364', 'Lipiesu')}!`),
		bullet(`Filter and Search functions now work correctly with non-English IMEs. Thanks, @${link('https://community.anytype.io/t/any-filter-or-search-function-doesnt-work-with-non-english-ime-on-mac/21496', 'vennetong')}!`),
		bullet(`Resolved an issue with Tag creation when typing non-English characters. Thanks, @${link('https://community.anytype.io/t/unable-to-create-chinese-tag-at-pinned-tag-relation/23800', 'crimx')}!`),
		bullet(`${hl('Text')} option in the Relation Type menu is highlighted when the cursor is hovered over. Thanks, @${link('https://community.anytype.io/t/text-option-does-not-highlight-when-making-a-new-relation/26051', 'PianoMacPower')}!`),
		bullet(`Toggle Block works correctly when pressing Enter to insert new lines. Thanks, @${link('https://community.anytype.io/t/a-toggle-block-throws-me-out-if-i-try-to-insert-two-new-lines-between-existing-lines/26032', 'Code-Jack')}!`),
		bullet(`Template Type is no longer displayed in the right-click menu under the ${hl('Change type')} option.`),
		bullet(`Fixed PDF export for Simple Tables. Thanks, @${link('https://community.anytype.io/t/simple-tables-look-wrong-when-using-pdf-export/25630', 'BIG艺术家')}!`),
		bullet(`Fixed an error that occurred when switching from Flow to an Object. Thanks, @${link('https://community.anytype.io/t/switching-to-flow-open-a-note-i-was-in-with-cmd-k-i-get-an-errorne/24955', 'krst')}!`),
		bullet(`The order of Space icons remains properly arranged. Thanks, @${link('https://community.anytype.io/t/order-of-spaces-in-the-sidebar-suddenly-rearranged/24114', 'siousu')}!`),
		bullet(`Hovering over "Move to" in the right-click menu no longer causes the page to scroll up.`),
		bullet(`Duplicating a locked relation no longer causes a popup in the corner.`),
		bullet(`Fixed the Filter menu in Sets.`),
		bullet(`Fixed an issue where ${hl(`${cmd} + A`)} and ${hl(`${cmd} + V`)} in an overlay affected the underlying Object. Thanks, @${link('https://community.anytype.io/t/overlay-cmd-a-cmd-v-also-pastes-in-the-object-underneath/25864', 'krst')}!`),
		bullet(`Date window in the Command menu no longer freezes when the cursor is moved away.`),
		bullet(`Fixed keyboard up navigation in the Command menu.`),
		bullet(`Fixed the behavior of the Enter key when creating a new Vault.`),
		bullet(`Adjusted the layout of Types to display the dates without cropping.`),
		bullet(`Default Object Type remains set. Thanks, @${link('https://community.anytype.io/t/default-object-type-keeps-changing-to-page/25748', 'zma17')}!`),
		bullet(`Fixed an issue with fast-clicking on inline object links. Thanks, @${link('https://community.anytype.io/t/fast-click-on-inline-object-link-does-not-work-on-macos/23818', 'aytigra')}!`),
		bullet(`Fixed an issue that could prevent title input in newly created Objects. Thanks, @${link('https://community.anytype.io/t/cannot-type-title-in-newly-created-object/22494', 'reachar')}!`),
		bullet(`Webclipper's authorisation process has been reworked to eliminate issues with pop-ups.`),
		bullet(`The selection rectangle now correctly toggles off when selecting text.`),

		div(),
		// --------------------------------------------//

		h1(`Desktop 0.44.0 Released!`),
		text(`Before we say goodbye to the year, we're happy to share this final update packed with some nice improvements. In addition to bug fixes and reliability/performance enhancements, we would like to introduce two long-anticipated features. We hope you enjoy this update and wish you a joyful holiday season!`),
		text(``),

		h2(`Highlights`),

		h3(`Date as an Object`),
		text(`You can now open any date as a separate object to view the entire context related to that date, including mentions (@date), automatically created dates and custom date relations. Dates are accessible from relations, layouts, graph, calendar view and more.`),
		text(`In addition, there are new Date and Time settings, and @date supports relative date formats such as @today or @tomorrow.`),
		img(`44/1.png`),
		text(``),

		h3(`Simple Formulas`),
		text(`The long-requested functionality is now available for Sets and Collections. You can count objects in the Grid view and perform simple math and aggregation functions with all types of relations.`),
		img(`44/2.png`),
		text(``),

		h2(`Quality-of-Life`),
		bullet(`Files and markups from the HTML and bookmarks are no longer created as objects when you place them in the app. This enhances the functionality of the Web Clipper and clipboard, resulting in a cleaner app without unnecessary file clutter.`),
		bullet(`The Entry space can now be deleted if it’s no longer needed or if you prefer to use only shared spaces. You can export and import it into any other spaces (better to use the any-block format).`),
		bullet(`Deeplinks to Objects include an invitation to the shared space when using the ${hl('Copy Link')} option, making collaboration and access more seamless.`),
		bullet(`Added the ability to import data during the creation of a second space, simplifying the setup process.`),
		bullet(`The Audio Player has been slightly restyled, with a background with a subtle shadow, slightly repositioned controls and updated icons.`),
		bullet(`Some colour updates for both light and dark modes.`),
		bullet(`The ${hl('Add Relation')} option has been removed from the File layout.`),
		bullet(`Added an option to enable or disable custom CSS. Thanks, @${link('https://community.anytype.io/t/custom-css-in-anytype-directly/24498', 'Shampra')}!`),
		text(``),

		h2(`Bug Fixes`),
		bullet(`Resolved an issue where the Link option in the widget settings menu could not be selected.`),
		bullet(`Fixed an issue in global search where the cursor would jump from its position when entering or deleting text, particularly after switching apps. Thanks, @${link('https://community.anytype.io/t/cursor-jumping-in-global-search/25012', 'dzlg')}!`),
		bullet(`Re-fixed an issue where local links with "$" in their path would cause the super link text to appear in some source text.`),
		bullet(`Search queries retain entered symbols, resolving an issue with missing characters.`),
		bullet(`Search results remain consistent when reopening the search panel.`),
		bullet(`Mermaid diagrams remain visible simultaneously. Thanks, @${link('https://community.anytype.io/t/only-one-mermaid-diagram-at-the-time-0-43-21-beta/25619', 'langtind')}!`),
		bullet(`The checkbox ticks as expected when attempting to delete a Vault.`),
		bullet(`The Brazilian currency symbols (R$) are displayed correctly. Thanks, @${link('https://community.anytype.io/t/bug-when-inserting-reference-to-values-in-brl-reais/24380', 'perereco')}!`),
		bullet(`Inline LaTeX with multiple standalone backslash commands now renders correctly. Thanks, @${link('https://community.anytype.io/t/inline-latex-for-multiple-standalone-backslash-commands-not-rendering/25537', 'zewwo')}!`),
		bullet(`Applying formatting via keyboard shortcuts affects all selected text across multiple levels of indentation. Thanks, @${link('https://community.anytype.io/t/formatting-shortcuts-only-apply-to-the-top-indent-level/24745', 'ferdzso')}!`),
		bullet(`The ${hl('Local Only')} tooltip in Network Mode is now clearly visible when the operating system is set to dark mode. Thanks, @${link('https://community.anytype.io/t/tooltip-local-only-in-network-mode-barely-visible-when-the-os-is-in-dark-mode/25317', 'krst')}!`),
		bullet(`${hl(`${cmd} + A`)} in an overlay now selects only the content within the overlay, without affecting the object underneath. Thanks, @${link('https://community.anytype.io/t/ctrl-cmd-a-in-an-overlay-also-selects-in-the-object-underneath/23642', 'krst')}!`),
		bullet(`${hl('Click')} handlers in Mermaid embed blocks open external links in a browser. Unfortunately, internal resource links within Anytype can't be fixed as they're purified by Mermaid. Thanks, @${link('https://community.anytype.io/t/mermaid-embed-block-mermaid-click-not-working-as-expected/24948', 'francodgstn')}!`),
		bullet(`Converting multiple blocks using shortcuts works correctly. Thanks, @${link('https://community.anytype.io/t/converting-multiple-blocks-with-shortcuts-not-working-anymore/25523', 'siousu')}!`),
		bullet(`Fixed an issue where element outlines would become visible. Thanks, @${link('https://community.anytype.io/t/outlines-visible-when-zooming-in-and-out/25500', 'zma17')}!`),
		bullet(`The right-click menu is correctly updated after an object or type is removed from the All Objects. Thanks, @${link('https://community.anytype.io/t/after-deleting-one-type-under-all-objects-the-right-click-menu-does-not-refresh-its-content-correctly/25295', 'Facility6384')} and @${link('https://community.anytype.io/t/after-deleting-one-type-under-all-objects-the-right-click-menu-does-not-refresh-its-content-correctly/25295', 'endlessblink')}!`),
		bullet(`Frequently clicking on the ${hl('Get My Key')} button does not result in an error.`),
		bullet(`Long space names no longer overlap with the sidebar button.`),
		bullet(`Links starting with tel: are not prepended with https:// anymore. Thanks, @${link('https://community.anytype.io/t/tel-urls-work-incorrectly-on-desktop/25178', 'fieldnote')}!`),
		bullet(`Formatting text as monospace using backticks ${hl('\`\`')} is applied without shifting the formatting of subsequent words in a paragraph. Thanks, @${link('https://community.anytype.io/t/monospace-formatting-with-backticks-shifts-following-formatting-left/24584', 'yuritem')}!`),
		bullet(`Reordering views in Sets and Collections is consistent and the drop-down list remains open after reordering for additional adjustments.`),
		bullet(`Resolved a crash caused by an ENOENT error.`),
		bullet(`The search icon in Sets and Collections displays correctly.`),
		bullet(`Fixed an issue where an Object name might not be saved when entering it for a new Object in a Set.`),
		bullet(`Fixed unexpected behaviour of the context menu when it could follow the mouse cursor and lose the context of the element it refers to. Thanks, @${link('https://community.anytype.io/t/actions-popup-follows-mouse-and-loses-context-to-element/25705', 'krst')}!`),
		text(``),

		callout(`Please be reminded that we no longer support macOS Catalina.`, '⚠️'),

		div(),
		// --------------------------------------------//

		h1(`Desktop 0.43.7 Released!`),
		callout(`This follow-up update to the previous release brings improved performance and a few additional enhancements.`, '📃'),
		text(''),

		h2(`Changelog `),
		bullet(`Improved stabilization and overall app performance.`),
		bullet(`Added support for Chinese language search.`),
		bullet(`Headers in Sets and Collections are now fixed at the top when scrolling in Grid view.`),
		bullet(`Added an ${hl('Open as Object')} action for images and videos opened in fullscreen.`),
		bullet(`Typing text with multiple selected blocks now deletes them and starts a new text block.`),
		bullet(`Implemented a new progress bars system.`),
		bullet(`Fixed an issue where pressing Enter or arrow keys didn’t create a new block below callouts. Thanks, @${link('https://community.anytype.io/t/24175', 'Daria_Sweet97')}!`),
		text(''),

		div(),
		// --------------------------------------------//

		h1(`Desktop 0.43.0 Released!`),
		callout(`A big thank you to our amazing Community for the valuable suggestions and reports that continue to help us along the way!`, '💌'),

		h2(`Highlights on this release`),
		text(`In this update, we've focused on important technical improvements. Although the major changes are under the hood, they lay the groundwork for future features and enhancements. Alongside this fundamental work, we have also made a number of smaller upgrades and fixes - let's dive in.`),

		h3(`Improved Full-Text Search Speed`),
		text(`We’ve upgraded our search functionality with a new library to improve speed, particularly for large spaces. Users with extensive spaces will experience faster search.`),

		h3(`Enhanced Any-Store for Faster Performance`),
		text(`We have implemented a new local database to enhance performance significantly. Users with large spaces will enjoy faster loading times and smoother interactions throughout the app.`),

		h3(`All Objects`),
		text(`Our <b>improved navigation</b> makes it much easier to browse through all your content. Now, you can search across all your Objects, Sets & Collections, and Media & Files in one place, with options to sort by Date or Name. Additionally, the simplified Library and the Bin also live in the new widget.`),
		video('43/1.mp4'),
		text(``),

		h3(`More Views & Widgets`),
		text(`..have been updated to improve visual usability.`),
		bullet(`<b>Gallery</b> has a fresh appearance for widgets.`),
		bullet(`<b>Kanban</b> supports displaying page covers on cards in a layout.`),
		video('43/2.mp4'),
		text(``),

		h2(`Quality-of-Life`),
		bullet(`Pressing Enter inside empty list and toggle blocks behaves as ${shift} + Tab for that block: moves up a level. Thanks, @${link('https://community.anytype.io/t/move-indented-bullet-points-to-the-left-using-enter-key/12082', 'purplekiwi')} & @${link('https://community.anytype.io/t/move-indented-bullet-points-to-the-left-using-enter-key/12082', 'Shampra')}!`),
		bullet(`Updated batch relation editing to allow adding new options and removing existing ones: now, when editing tags/objects/files the values are added or deleted instead of replacing with a new value. Thanks, @${link('https://community.anytype.io/t/option-to-append-tags-instead-of-replacing-them-when-using-batch-editing-with-multi-select-relations/21362', 'Shampra')}!`),
		bullet(`Created relations in batch editing are now automatically added to the Set or Collection view.`),
		bullet(`Updated icons for multiple file formats, including generic files, images, videos and more.`),
		bullet(`Updated icons for relation formats: select, multi-select, date, checkbox, and email.`),
		bullet(`Color of toggle icon is based on a block text color.`),
		bullet(`Updated layout of the File object type.`),
		bullet(`Added the option to paste text without its original formatting. Thanks, @${link('https://community.anytype.io/t/paste-text-without-its-formatting/8810', 'Shampra')}!`),
		bullet(`Spellcheck language is based on the language selected in your preferences by default.`),
		bullet(`Added an option to save search results to a new or existing collection via the right-click menu in a search query.`),
		bullet(`Added the ability to create an object in the Calendar Set or Collection View, similar to the Calendar Widget.`),
		bullet(`Kanban cards now support cover previews. Thanks, @${link('https://community.anytype.io/t/display-cover-or-image-content-in-kanban-view/9018', 'Elias')}!`),
		bullet(`Relation cells in read-only Spaces or read-only objects now provide the ability to read the full value of that relation cell.`),
		bullet(`Warning switch to ${hl('Local Only')} network: we've added a notification and additional confirmation before selection.`),
		bullet(`Potentially harmful URLs have a warning before opening them.`),
		bullet(`Create new objects in Sets faster by using ${hl(`${shift} + Enter`)}. Thanks, @${link('https://community.anytype.io/t/paste-text-without-its-formatting/8810', 'Pretzel')}!`),
		bullet(`Added an ability to multi-edit the Done relation.`),
		bullet(`Added tooltips to the Calendar view that display the full name of an object when the cursor is briefly hovered over it. Thanks, @${link('https://community.anytype.io/t/tooltip-on-calendar/24086', 'MrDaisyBates')}!`),
		bullet(`Updated the plus icon and block menu icon.`),
		bullet(`When changing the format of a block from a list to text, the background color and styles are now cleared when pressing ${hl('Enter')}.`),
		bullet(`Updated menu button on the Template type.`),
		bullet(`Disabled the ability to change an object type to Template.`),
		bullet(`Default Space icons now display the first letter of the Space name.`),
		bullet(`Dark mode colors have been updated.`),
		bullet(`Improved Code snippet readability when nested within a Callout block.`),
		bullet(`Removed the three dots from the drag and drop handle for a cleaner interface.`),
		bullet(`Added restrictions to prevent Templates from being created in multiple unintended locations.`),
		text(``),

		h2(`Performance`),
		bullet(`Calendar has been greatly optimized (& is no longer freezable). Thanks, @${link('https://community.anytype.io/t/calendar-view-freezes/12323/5', 'C.c')}! `),
		bullet(`Databases for different spaces have been separated to improve overall application performance.`),
		text(``),

		h2(`Bug Fixes`),
		bullet(`Pin Code is now numeric for newly created PINs, allowing only number input. Thanks, @${link('https://community.anytype.io/t/pin-code-should-be-numeric/20435', 'isllll')}!`),
		bullet(`Fixed an issue where pasting a Pin Code was not working.`),
		bullet(`Non-Latin characters in PDF files are now displayed correctly. Thanks, @${link('https://community.anytype.io/t/korean-characters-dont-appear-in-pdf/22446', 'BloomJieun')}!`),
		bullet(`PDF blocks added on Mobile platforms now display correctly on Desktop after sync. Thanks, @${link('https://community.anytype.io/t/pdf-block-added-on-mobile-doesnt-display-properly-on-desktop/23187', 'BCSharp')}!`),
		bullet(`Set Widget is synced with objects in the list and has a default View option when the type is changed.`),	
		bullet(`Creating an object relation works correctly.`),
		bullet(`Updated menu actions for Sets and Collections moved to Bin.`),
		bullet(`Fixed the invalid key error that occurred when entering the phrase from the keyboard during the login.`),
		bullet(`Selecting ${hl('Last Opened Object')} as the Homepage now correctly opens to the last accessed object. Thanks, @${link('https://community.anytype.io/t/homepage-last-opened-object-does-not-work/22079', 'stendekoniko')}!`),
		bullet(`Text highlighting does not change when an object is locked. Thanks, @${link('https://community.anytype.io/t/empty-space-highlighting-lost-on-locked-pages/22592', 'Terit')}!`),
		bullet(`A right-click on an object in Calendar View now correctly opens the context menu instead of opening the object. Thanks, @${link('https://community.anytype.io/t/a-right-click-on-an-object-in-calendar-view-opens-it/23225', 'Code-Jack')}!`),
		bullet(`Individual orphan nodes are farther from larger clusters of objects on the Graph. Thanks, @${link('https://community.anytype.io/t/individual-orphan-note-not-distanced-from-other-nodes/10934', 'C.c')}!`),
		bullet(`Fixed unexpected behavior where clicking on a Link could redirect to a Homepage. Thanks, @${link('https://community.anytype.io/t/strange-bug-when-clicking-links-get-forwarded-to-welcome-page/16444', 'kellertuer')}!`),
		bullet(`Color of numbered and bulleted lists changes according to the color of a block. Thanks, @${link('https://community.anytype.io/t/strange-bug-when-clicking-links-get-forwarded-to-welcome-page/16444', 'dzlg')}!`),
		bullet(`Resolved the issue causing a black screen when opening Anytype on Linux. Thanks, @${link('https://community.anytype.io/t/black-screen-when-open-anytype-on-linux/23333', 'Jefferson')}!`),
		bullet(`Text changes no longer disappear when the slash menu is open.`),
		bullet(`Locked objects are now fully protected from being accidentally modified in Sets and Collections.`),
		bullet(`Fixed an issue where local links with ${hl('$')} in their path would cause the super link text to appear in some source text. Thanks, @${link('https://community.anytype.io/t/if-a-local-link-has-in-its-path-the-super-link-text-would-show-in-some-source-text/23262', '4thHydro')}!`),
		bullet(`Thumbnails in the image library are now displayed correctly. Thanks, @${link('https://community.anytype.io/t/incorrect-image-display-in-library-tab-when-changing-page-icon/23379', 'a44')}!`),
		bullet(`Adjusted buttons in the link editor pop-up window in German localization. Thanks, @${link('https://community.anytype.io/t/ui-issue-with-bookmark-popup-when-the-buttons-are-too-big-long/23464', 'VisualNotes')}!`),
		bullet(`Fixed an issue preventing the creation of types that end with accented characters, such as ${hl('à')}.`),
		bullet(`Restored the ability to move blocks between objects by dragging them to the sidebar. Thanks, @${link('https://community.anytype.io/t/latest-update-broke-ability-to-drag-blocks-to-the-sidebar/23525', 'Andris')}!`),
		bullet(`Inserting a toggle no longer causes scrolling to the top of a page. Thanks, @${link('https://community.anytype.io/t/copy-pasting-a-non-empty-toggle-makes-anytype-jump-to-the-top/13373', 'SwiftyChicken')}!`),
		bullet(`Links following inline LaTeX in a line are now placed correctly. Thanks, @${link('https://community.anytype.io/t/links-behaving-wierd-with-inline-latex/23549', 'eloitor')}!`),
		bullet(`The count of selected objects works correctly.`),
		bullet(`When editing multiple objects in a Type view from the Library, relations are displayed according to the list in a Type. Thanks, @${link('https://community.anytype.io/t/type-multiple-objects-selected-edit-relations-bug/23540', 'bee6000')}!`),
		bullet(`Fixed an issue that could cause square brackets to appear in an Object's title when modifying its content or supported relations. Thanks, @${link('https://community.anytype.io/t/18916', 'C.c')}!`),
		bullet(`Drop-down menu with [Editor / Viewer / Remove member] options has been removed for a Space owner.`),
		bullet(`Mermaid diagram now switches a color style according to the color mode of the App.`),
		bullet(`Multiple file selection on import is fixed.`),
		bullet(`When adding an object relation to Set, the selection popup correctly closes instantly.`),
		bullet(`Fixed an issue on Linux where the menu visibility toggle was not working correctly through the window menu.`),
		text(``),

		h2(`Platform Updates`),
		bullet(`Starting with the next release, we will <b>no longer support MacOS Catalina (10.15)</b>. This decision comes as Apple has officially dropped support for this version, and maintaining compatibility requires significant development effort on our end. We understand this change may affect some users, but it's a necessary step to ensure smoother updates.`),

		div(),
		// --------------------------------------------//

		h1(`Anytype 0.42.3 Hotfix Released!`),
		text(`We're releasing this hotfix just three days after the 0.42.0 update to address important feedback from our community and better align with user expectations. This patch bundles all the features of 0.42.0 (see previous notes) along with UI improvements, primarily the sidebar display settings, and several bug fixes. Thank you for your swift feedback and continued support!`),
		text(''),
		text(`Here's what's new in this hotfix:`),
		text(''),

		h2(`Quality-of-Life 🌿 `, I.BlockHAlign.Center),
		bullet(`Added display options for Vault Sidebar to ${hl('Settings → Personalization tab')}.`),
		bullet(`Moved settings from the Appearance tab to the Personalization tab for consistency; renamed the Appearance tab to Color Mode.`),
		bullet(`Improved sidebar animation and delay. Thanks, @${link('https://community.anytype.io/t/23066', 'code-jack')}!`),
		text(''),															  

		h2(`Bug Fixes 🪲`, I.BlockHAlign.Center),															  
		bullet(`Fixed an issue with the default auto-hide sidebar behavior. Previous logic caused problems for users with auto-hide enabled in fixed mode. The setting is now updated, so please reconfigure your auto-hide/show preferences.`),
		bullet(`Corrected the positioning of the sidebar toggle icon and header on Windows and Linux.`),
		bullet(`Cleared saved search state in Global Search when the clear button is used.`),
		bullet(`Fixed a bug preventing ${hl('0')} values from appearing in Number relations. Thanks, @${link('https://community.anytype.io/t/23048', 'mattred1')}!`),															  
		bullet(`Resolved an issue with markdown parsing that caused inline links to add ${hl('…')} at the end. Thanks, @${link('https://community.anytype.io/t/23083', 'ferdzso')}!`),
		bullet(`Fixed a middleware problem with macOS 11 builds. Thanks, @${link('https://community.anytype.io/t/23068', '_martin')}!`),															  
		bullet(`Fixed an issue with URL previews not displaying correctly on mouse hover. Thanks, @${link('https://community.anytype.io/t/23079', 'candidchronicles')}!`),															  
		bullet(`Fixed issue with PDFs exporting black background in dark mode. Thanks, @${link('https://community.anytype.io/t/23133', '2PJs')}!`),
		bullet(`Fixed numbers remaining when switching from a numbered list to a bulleted list. Thanks, @${link('https://community.anytype.io/t/23114', 'elias')}!`),
		
		text(''),
		text(`Thanks again for your patience and feedback as we work to improve Anytype 🫶`),	

		div(),
		// --------------------------------------------//

		title(`Anytype Desktop 0.42.0 Released!`),
		text(`This release brings a redesigned sidebar, brand-new widgets, and the highly anticipated inline LaTeX feature, along with numerous quality-of-life improvements and bug fixes for an even smoother Anytype experience. Don’t miss our new sync status indicator—it’s like having a little tech guru keeping you informed! Enjoy exploring the updates 🏄‍♀️`),
		text(''),

		h2(`Highlights 💫`, I.BlockHAlign.Center),
		text(''),

		h3(`Redesigned Sidebar 🌐`),
		text(`Our sleek new sidebar makes hopping between Spaces a breeze. Think of it as your personal GPS for easier navigation.`),
		img(`42/1.png`),
		caption(`Simply click to hide the entire sidebar, or right-click the icon for additional options.`),
		text(''),

		h3(`New Widgets 🧩`),
		text(`We're bringing you Widgets that are more flexible than a yoga master. Now, you can display Widgets in three new layouts: Calendar, Kanban, and Gallery.`),
		img(`42/2.png`),
		text(''),

		h3(`New Sync Status Indicator 🧘`),
		text(`Now, you'll get more informative updates for Objects and files. Look out for these handy indicators when there's no network connection or sync. `),
		img(`42/3.png`),
		text(''),

		h3(`Inline LaTeX 🧑‍🔬`),
		text(`We’re absolutely geeked to finally deliver ${link('https://community.anytype.io/t/2315', 'this long-awaited feature to the community')}! You can now easily add mathematical notation right into your text, making it possible to include complex equations and formulas. Thanks everyone who voted for it! `),
		video(`42/4.mp4`),
		text(''),

		h2(`Quality-of-Life 🪷 `, I.BlockHAlign.Center),
		bullet(`Menu item was added to Object settings for faster "add to Collection" workflow.`),
		bullet(`Sharing Anytype with others got simpler—just grab the link from the help menu and share away (Desktop only).`),
		bullet(`Navigate Tables using only arrow keys to enter, jump cells &amp; exit to the next block. Thanks, @Code-Jack!`),
		bullet(`Added an option to copy the URL from bookmark blocks. Thanks, @maxitg!`),
		bullet(`Reduced mouse action needed after creating a new page in Collections. Thanks, @Code-Jack!`),
		bullet(`"Turn into Object" adapts to default Templates now. Thanks, @${link('https://community.anytype.io/t/turn-into-object-did-not-adapt-to-default-template/21983', 'LSK')}!`),
		bullet(`Added option to disable preview on graph view. Thanks, @${link('https://community.anytype.io/t/21898', 'iamWing')}!`),
		bullet(`Typed text after a linked object no longer becomes part of the link and can be unlinked. Thanks, @${link('https://community.anytype.io/t/8075', 'floseq')}!`),
		bullet(`Select all ${hl(`${cmd} + A`)} twice now excludes the title. Thanks, @${link('https://community.anytype.io/t/ctrl-a-behaviour-inconsistent-unpredictable/7612', 'qualquertipo')}!`),
		bullet(`You can now use crypto (BTC, ETH, USDT, USDC, BNB, Dai, etc.) to pay for memberships.`),
		bullet(`Added a menu for selecting filter/sorting options after clicking "New Sort/Filter".`),
		bullet(`Clicking the "Join" button on the Pricing page will now open the app to purchase the subscription if it’s installed, or take you to the download page if it’s not.`),
		bullet(`Search panel now reopens with previously entered text and selected objects in "Related to" mode.`),
		text(''),
		
		h3(`Technical Update 🛠️`),
		bullet(`Electron updated to 31.0.0`),
		text(''),

		h2(`Bug Fixes 🦂`, I.BlockHAlign.Center),	
		bullet(`Number relations with values less than 1 million are now evenly spaced. Thanks, @${link('https://community.anytype.io/t/7497', 'matylda')}!`),
		bullet(`Mermaid diagrams now display correctly with dark mode backgrounds. Thanks, @${link('https://community.anytype.io/t/20228', 'BoxOfWood')}!`),
		bullet(`Top menu no longer shows up below the cover in sets when using the modal window. Thanks, ${link('https://community.anytype.io/t/22009', 'Elias')}!`),
		bullet(`Fixed a problem with carriage when adding tags or objects to corresponding relations. Thanks, @${link('https://community.anytype.io/t/10219', 'dzlg')}!`),
		bullet(`Relations with number type can now have a value of 0. Thanks, @${link('https://community.anytype.io/t/cant-store-0-s-in-a-number-type-relation/3583', 'gcsapo')}!`),
		bullet(`Widget pop-ups at the bottom of the sidebar are no longer hidden by the app border. Thanks, @${link('https://community.anytype.io/t/19954', 'Tamalika')}!`),
		bullet(`Deleted media files now appear as non-existent when embedded in an object. Thanks, @${link('https://community.anytype.io/t/deleted-files-are-not-shown-as-deleted/11208', 'Balcion')}!`),
		bullet(`First sentence of an Object no longer appears on title bar when the app is locked. Thanks, @${link('https://community.anytype.io/t/21551', 'NoteMyBrain')}`),
		bullet(`Search pane now displays correctly on smaller screen sizes. Thanks, @${link('https://community.anytype.io/t/22130', 'C.c.')}!`),
		bullet(`Search in Relation options now shows results even if options were scrolled.`),
		bullet(`Checkbox sorting in Set has been restored. Thanks, @${link('https://community.anytype.io/t/22266', 'effreyh')}!`),
		bullet(`The Query of the set now updates correctly in the pop-up.`),
		bullet(`Fixed issue with using library images for type Icons. Thanks, @${link('https://community.anytype.io/t/22297', 'Self-Perfection')}!`),
		bullet(`Keyboard cursor no longer disappears after cutting a whole line (block). Thanks, @${link('https://community.anytype.io/t/20781', 'SirCaptain')}!`),
		bullet(`Clarified the prompt for image uploads when no images are present.`),
		bullet(`Made sizes dropdown menu consistent throughout UI.`),
		bullet(`Fixed manual reordering of favorites in the widget. Thanks, @elias`),
		bullet(`Fixed issue where cursor couldn't break out of box when using text-style inline code. Thanks, @${link('https://community.anytype.io/t/8944', 'Xonline')}!`),
		bullet(`Fixed Markdown behavior for underscores and dashes. Thanks, @${link('https://community.anytype.io/t/17152', 'katcher')}!`),
	];
};
