import { Block, Helpers } from './common';

export default (h: Helpers): Block[] => {
	const { cmd, shift, hl, icon, title, h2, h4, text, bullet, toggle, link, img } = h;
	return [
		icon('🗣️'),

		title(`Let's Discuss`),
		h4(`<span>Release 0.55.0</span>`),
		text(``),
		text(`This release introduces Object Discussions — comment and have threaded conversations directly inside any Object. Spaces and Chats merge into Channels with a redesigned creation flow, files become first-class Objects you can upload and organize, Bookmarks get a dedicated layout, and the new Anytype Agents' Skill lets AI coding agents read, create, and manipulate your data.`),
		text(`On top of that: a redesigned Bin with delete permissions, a new Sidebar view mode, pinned messages, and a long list of fixes and quality-of-life improvements across the app.`),
		text(``),

		h2(`Object Discussions`),
		text(`You can now start a discussion and comment directly inside any Object – no need to switch to a separate Chat. Post a comment, reply to others, and build a conversation right where the work happens.`),
		text(`Discussion posts support rich content: code blocks, checkboxes, attachments, embeds, and inline links. You can edit your posts after sending, react with emoji, and reply to specific messages to keep threads organized.`),
		img('55/1.png'),
		text(``),

		h2(`Updated Channel Creation`),
		text(`Spaces and Chats have been merged into a single concept: Channel. Instead of choosing between "create a Space" or "create a Chat", you now create a Channel and pick what opens as its Home – a Chat, a Page, or a Collection.`),
		text(`The creation flow walks you through it step by step: name your Channel, invite members, and select the Home.`),
		img('55/2.png'),
		text(``),

		h2(`Personal Favorites`),
		text(`Each Channel now has two distinct mechanisms: My Favorites, visible only to you, and Shared Pins, visible to all members. Any user can add objects to My Favorites for quick access without affecting what other members see. Shared Pins remain available to Owners who need to surface important docs for the whole team. Both appear in the Widget Bar in clearly separated sections.`),
		img('55/3.png'),
		text(``),

		h2(`File & Media Uploads`),
		text(`You can now upload files directly as standalone Objects. Choose Image, Video, Audio, or File from the "Create" menu, drag files onto a Type page or widget, or paste from the clipboard – each file becomes its own Object that you can find, link, and organize like anything else in Anytype. Drop a folder and it converts into a Collection that mirrors the original structure.`),
		img('55/4.png'),
		text(``),

		h2(`Bookmark Layout`),
		text(`Bookmarks now have their own dedicated layout. Instead of inheriting the Page layout, each bookmark displays the site's preview image, a short URL with the site icon, and a prominent "Open Website" button.`),
		text(`The paste menu has also been updated: when you paste a URL, you can now choose to insert it as a Mention, a Bookmark, an Embed, or a plain link.`),
		img('55/5.png'),
		text(``),

		h2(`Anytype Agents' Skill`),
		text(`The new open-source ${link('https://github.com/anyproto/anytype-agents-skill', 'anytype-agents-skill')} provides a lightweight, isolated JavaScript runtime for executing code against your Anytype data, and exposes around 30 high-level methods to read, create, search, and manipulate objects in your Channels. Give your favorite AI agent – Claude Code, Cursor, Gemini CLI, GitHub Copilot, and others – the skill, and let it handle bulk edits, data transformations, and repetitive tasks for you – gluing your data efficiently with the full power of a programming language.`),
		text(``),

		h2(`Quality of Life Improvements`),
		text(``),

		text(`<b>Sidebar Links View</b>`),
		text(`A new option in Channel Preferences lets you switch the sidebar between two display modes: Widgets (the default), which shows rich previews, or Links – a compact view that lists objects as simple links.`),
		img('55/6.png'),
		text(``),

		text(`<b>Redesigned Bin with Delete Permissions</b>`),
		text(`The Bin now displays objects in a columned list with Name, Deleted date, and Created By columns. In shared Channels, editors can only permanently delete objects they created – protecting the team from accidental data loss. Owners and Admins can empty the entire Bin from a new menu.`),
		img('55/7.png'),
		text(``),

		text(`<b>Redesigned Option Menus</b>`),
		text(`Select, Multi-select, Object, and Attachment property menus have been redesigned with a cleaner layout, better keyboard navigation, and more consistent behavior across the app.`),
		text(``),

		text(`<b>Pin Messages in Chats</b>`),
		text(`You can now pin important messages in Chat. Pinned messages appear in a persistent banner at the top of the conversation. When multiple messages are pinned, click the banner to cycle through them from newest to oldest.`),
		text(``),

		text(`<b>Multi-Cell Selection in Tables</b>`),
		text(`You can now select multiple cells in a table at once, making it easier to copy, delete, or format table content in bulk.`),
		text(``),

		text(`<b>Full Width Toggle</b>`),
		text(`The layout width slider in Type Settings has been replaced with a simple "Full Width" toggle, making it faster to switch between standard and full-width layouts.`),
		text(``),

		text(`<b>Configurable File Download Size Limit</b>`),
		text(`You can now set a maximum file size for automatic downloads in shared Channels. Files above the limit won't be fetched automatically, keeping your storage usage under control.`),
		text(``),

		text(`<b>Size Setting in List View</b>`),
		text(`List view now offers a Regular mode alongside the compact default – you can choose between two modes in a new Size setting.`),
		text(``),

		text(`<b>Consistent ${hl(`${cmd}+Click`)} Across Views</b>`),
		text(`${hl(`${cmd}+Click`)} and ${hl(`${cmd}+${shift}+Click`)} now behave consistently across Grid, Gallery, List, and Board views – opening objects in new tabs or windows as expected.`),
		text(``),

		text(`<b>Reaction Counters and Notifications</b>`),
		text(`Emoji reactions in Chat now show a counter next to each reaction, and you receive notifications when someone reacts to your message.`),
		text(``),

		text(`<b>Disable Automatic Text Replacements</b>`),
		text(`A new setting lets you turn off automatic Unicode sequence replacements (like arrows and em dashes), so what you type stays exactly as you typed it.`),
		text(``),

		text(`<b>Emoji Search Popup</b>`),
		text(`Typing ${hl(':')} followed by a keyword now opens an emoji search popup, so you can find and insert emoji without leaving the keyboard.`),
		text(``),

		text(`<b>Copy Object Link with ${hl(`${cmd}+C`)}</b>`),
		text(`When no text is selected, pressing ${hl(`${cmd}+C`)} now copies a link to the current Object. You can paste it elsewhere to create a quick reference.`),
		text(``),

		text(`<b>Auto-resolve Pasted Links in Chat</b>`),
		text(`Pasting an Anytype Object link into the Chat input now automatically converts it into an attachment card, so recipients see a rich preview instead of a raw URL.`),
		text(``),

		text(`<b>Return to Scroll Position</b>`),
		text(`Navigating away from a Type or Collection and coming back now restores your scroll position, so you don't lose your place.`),
		text(``),

		text(`<b>PDF Export Background Color</b>`),
		text(`You can now choose a background color when exporting to PDF, so your exports match the look you want. Thanks to @${link('https://community.anytype.io/t/29978', 'Petefln')}!`),
		text(``),

		text(`<b>Multi-line Indentation in Code Blocks</b>`),
		text(`You can now select multiple lines in a code block and indent or outdent them all at once with ${hl('Tab')} and ${hl(`${shift}+Tab`)}. Thanks to @${link('https://community.anytype.io/t/30051', 'dpr')}!`),
		text(``),

		text(`<b>Updated Keyboard Shortcuts</b>`),
		text(`Shortcut labels throughout the app have been updated for accuracy, and several new shortcuts have been added.`),
		text(``),

		text(`<b>Auto-open Filter Values</b>`),
		text(`Selecting a property in the filter menu now automatically opens the values picker, saving you an extra click.`),
		text(``),

		text(`<b>Download Spinner on File Objects</b>`),
		text(`File Objects now show a spinner while downloading, so you can see the progress at a glance.`),
		text(``),

		text(`<b>New Notification Sound</b>`),
		text(`The desktop notification sound has been replaced with a new, more pleasant tone.`),
		text(``),

		text(`<b>Locale-aware Date Filters</b>`),
		text(`Date inputs in filters now respect your system locale, displaying dates in the format you're used to.`),
		text(``),

		text(`<b>Description Toggle Preserves Modified Date</b>`),
		text(`Toggling the Description field visibility on an object no longer changes its Modified Date, so your "recently modified" sorting stays accurate.`),
		text(``),

		text(`<b>Inline Image Indentation</b>`),
		text(`Inline images can now be indented with ${hl('Tab')}, just like text blocks.`),
		text(``),

		text(`<b>Close Table of Contents on Navigation</b>`),
		text(`The Table of Contents panel now closes automatically when you navigate to a different Object.`),
		text(``),

		text(`<b>Open New Window from Dock</b>`),
		text(`You can now open a new Anytype window directly from the dock icon context menu.`),
		text(``),

		text(`<b>Markdown Panel Inline Code Hint</b>`),
		text(`The Markdown cheat sheet now correctly shows single backticks for inline code instead of double.`),
		text(``),

		h2(`Visual Refresh`),
		text(``),

		text(`<b>Unified Context Menus</b>`),
		text(`Context menus across the app – object settings, widgets, editor blocks, and text blocks – have been redesigned with a consistent structure, action grouping, and visual style.`),
		text(``),

		text(`<b>Updated Color Palette</b>`),
		text(`Colors across the app have been refreshed with an updated palette – including new text colors in dark mode and improved contrast for highlights and selections.`),
		text(``),

		text(`<b>Improved Text Selection & Highlighting</b>`),
		text(`Text selection and block highlighting now use updated colors with better contrast, making it easier to see what you've selected in both light and dark modes.`),
		text(``),

		text(`<b>Updated Task & Checkbox Icons</b>`),
		text(`Task and checkbox icons have been refreshed with a cleaner, more modern look across the app.`),
		text(``),

		text(`<b>Refreshed Object Type Icons</b>`),
		text(`Object type icons (Task, Bookmark, Note, File, Chat, and others) and the import icon have been updated for a more consistent visual style.`),
		text(``),

		text(`<b>Table of Contents Scroll Tracking</b>`),
		text(`The Table of Contents now highlights the heading you're currently viewing, so you always know where you are in long documents.`),
		text(``),

		text(`<b>Redesigned Input Fields</b>`),
		text(`Input fields across the app have been updated with a cleaner design, building on the new style introduced with Advanced Filters.`),
		text(``),

		text(`<b>Muted and Hidden Chat Styling</b>`),
		text(`Muted and hidden Chats now use grey text styling, making it easier to tell them apart from active conversations.`),
		text(``),

		h2(`Bug Fixes`),
		text(``),

		toggle(`<b>Chat & Messaging (14)</b>`, [
			bullet(`Messages can no longer be edited to whitespace-only content, which previously caused them to appear empty.`),
			bullet(`The "Scroll to Bottom" button now works on the first tap.`),
			bullet(`The upload indicator now displays correctly when sending images.`),
			bullet(`The "Meet the most powerful private chat" tooltip no longer renders incorrectly.`),
			bullet(`Replying to an older message now correctly shows the reply in the current scroll position.`),
			bullet(`Right-clicking in Chat no longer causes the view to shake.`),
			bullet(`Links in 1-on-1 Chats now open correctly.`),
			bullet(`Chat message links no longer resolve to the wrong Chat or fail to open.`),
			bullet(`The message editing state is no longer carried over when switching between Chats.`),
			bullet(`Chat now scrolls to the first unread message when opened.`),
			bullet(`The order of adding objects, links, and images to Chat messages has been corrected.`),
			bullet(`Editing or changing an image in a Chat message now updates immediately.`),
			bullet(`The endless file upload spinner in Chat has been fixed.`),
			bullet(`Chat Objects in the Bin now show a clear "deleted" state instead of appearing as if they're still active.`),
		]),

		toggle(`<b>Editor & Blocks (41)</b>`, [
			bullet(`Pressing multiple ${hl('Enter')} keys in the middle of a toggle no longer exits the indentation.`),
			bullet(`Callout block rendering and behavior issues have been fixed.`),
			bullet(`A newline is no longer incorrectly added to code blocks in certain situations.`),
			bullet(`Pressing ${hl('Enter')} no longer spams new lines when an empty block follows the current one. Thanks to @${link('https://community.anytype.io/t/30210', 'lumeno.kotobazza')}!`),
			bullet(`Modifier keys no longer insert unwanted characters during text formatting. Thanks to @${link('https://community.anytype.io/t/30129', 'trialsin')}!`),
			bullet(`Duplicating a toggle block no longer nests the copy inside the deepest grandchild.`),
			bullet(`Unlinking a URL from text no longer triggers an undo action.`),
			bullet(`Heading behavior after pressing ${hl('Enter')} has been corrected.`),
			bullet(`Multiple editor issues with block operations have been resolved.`),
			bullet(`Markdown and code block conflicts have been fixed.`),
			bullet(`Toggles can now be opened and closed when blocks are highlighted.`),
			bullet(`Line breaks in headings now work correctly.`),
			bullet(`Pasting a URL to create a bookmark no longer overwrites the block above it.`),
			bullet(`Table of Contents now renders correctly when the document contains toggle headings.`),
			bullet(`Deleting an empty line above a toggle no longer closes or removes it. Thanks to @${link('https://community.anytype.io/t/28039', 'Code-Jack')}!`),
			bullet(`Highlighting single link blocks now works correctly.`),
			bullet(`Markdown replacement whitespace behavior has been fixed. Thanks to @${link('https://community.anytype.io/t/27193', 'flypenguin')}!`),
			bullet(`Inconsistent emoji editing behavior has been corrected. Thanks to @${link('https://community.anytype.io/t/25770', 'herb')}!`),
			bullet(`Text entered before a hyperlink no longer becomes part of the link. Thanks to @${link('https://community.anytype.io/t/25349', 'a44')}!`),
			bullet(`Text is no longer duplicated after inserting an emoji.`),
			bullet(`Mentions can now be correctly copied and cut.`),
			bullet(`The cursor no longer disappears when the first Mention in a block is deleted.`),
			bullet(`Selecting a block with a triple click now correctly deletes mentions and text together.`),
			bullet(`Chinese character input now works in Embed blocks. Thanks to @${link('https://community.anytype.io/t/28942', 'AlfredZhang')}!`),
			bullet(`Display issues when editing blocks in Chinese next to inline links have been fixed. Thanks to @${link('https://community.anytype.io/t/28419', 'M.D1')}!`),
			bullet(`The cursor can now move past folded toggles with nested content.`),
			bullet(`Inline code blocks no longer malform text containing recognized symbols. Thanks to @${link('https://community.anytype.io/t/30211', 'spiffytech')}!`),
			bullet(`Pressing ${hl('Enter')} in the middle of a heading now converts the text in the next block to regular style.`),
			bullet(`Pressing ${hl('Enter')} at the beginning of a heading now creates a regular text block above it.`),
			bullet(`Backspace no longer out-indents a block and inherits the next set as children.`),
			bullet(`Pressing ${hl('Enter')} twice on a highlight block now correctly exits it.`),
			bullet(`Pressing ${hl('Enter')} inside a highlight block now creates a sibling block, not a child.`),
			bullet(`Pressing ${hl('Enter')} after a collapsed toggle heading now creates a line break outside the toggle.`),
			bullet(`The ${hl('/')} shortcut now works correctly at the beginning of a block.`),
			bullet(`Block type conversion no longer sends multiple block IDs unnecessarily.`),
			bullet(`You can now place the cursor at the very first character of an inline code span without it jumping. Thanks to @${link('https://community.anytype.io/t/27826', 'spiffytech')}!`),
			bullet(`Applying underline or other text formatting no longer extends the style to trailing whitespace.`),
			bullet(`Duplicate toggle behavior has been corrected.`),
			bullet(`Pasting a heading into an empty toggle no longer replaces the toggle – the heading becomes the toggle's title instead. Thanks to @${link('https://community.anytype.io/t/29661', 'Code-Jack')}!`),
			bullet(`Backspacing in a bulleted list no longer causes unexpected indentation of the blocks below.`),
			bullet(`Empty file block placeholders can now be copied and pasted correctly.`),
		]),

		toggle(`<b>Graph (5)</b>`, [
			bullet(`Long-pressing and then releasing an Object in the graph no longer opens it.`),
			bullet(`Long-pressing an Object no longer causes it to float away.`),
			bullet(`Images are no longer shown in the graph when the toggle for them is off.`),
			bullet(`High CPU usage when viewing the graph has been resolved.`),
			bullet(`Graph View filters now apply correctly when the graph is first opened. Thanks to @${link('https://community.anytype.io/t/30081', 'lhewett946')}!`),
		]),

		toggle(`<b>Objects & Views (29)</b>`, [
			bullet(`Google "My Maps" embeds now render correctly.`),
			bullet(`Opening another Object in a new tab no longer opens the currently active Object instead.`),
			bullet(`The "+Create option" button in Select and Multi-select properties now works correctly.`),
			bullet(`Tag creation has been fixed.`),
			bullet(`Copying the source link from a Bookmark now returns the correct URL.`),
			bullet(`Clicking on the sidebar while editing a property option now closes the menu.`),
			bullet(`Advanced Filters now work correctly.`),
			bullet(`${hl(`${cmd}+A`)} now correctly selects all objects in a Type, Query, or Collection.`),
			bullet(`Shortened links now open correctly instead of failing with "..". Thanks to @${link('https://community.anytype.io/t/30276', 'Shampra')}!`),
			bullet(`Inline Queries with a default sort applied no longer return empty results.`),
			bullet(`Restored properties now appear in the Query immediately without re-opening.`),
			bullet(`Deleted properties via Channel Settings no longer remain accessible in Query views.`),
			bullet(`Pressing ${hl('Enter')} while creating a property no longer causes unexpected behavior.`),
			bullet(`New options in Select properties now display immediately without a refresh.`),
			bullet(`Manual sorting within Collections has been restored.`),
			bullet(`List View in Regular mode now shows the divider line when manually sorted.`),
			bullet(`Templates can now be filtered out in queries. Thanks to @${link('https://community.anytype.io/t/30110', 'Uvann')}!`),
			bullet(`The "Create Object" option no longer appears in the ${hl('/link')} menu.`),
			bullet(`Gallery view scrolling performance has been improved. Thanks to @${link('https://community.anytype.io/t/30143', 'dpr')}!`),
			bullet(`Scrolling now works correctly in Gallery layout.`),
			bullet(`Graph view links can now be turned off again in query view. Thanks to @${link('https://community.anytype.io/t/30155', 'riblek')}!`),
			bullet(`Object Types found in search now correctly load their properties.`),
			bullet(`Searching by Multi-select property values in Collections now finds all matching entries. Thanks to @${link('https://community.anytype.io/t/29626', 'Code-Jack')}!`),
			bullet(`File syncing between devices and with the Anytype network now works reliably. Thanks to @${link('https://community.anytype.io/t/30312', 'NicolasJouanin')}!`),
			bullet(`Cover images in Gallery view now display with correct dimensions, matching what you see when the object is opened.`),
			bullet(`Properties now correctly disappear from the Advanced Filter after removal.`),
			bullet(`The date format is now displayed correctly in property filters.`),
			bullet(`The "Include time" switch in Advanced Filters now works as expected.`),
			bullet(`Duplicating an Object from the sidebar context menu now automatically opens the new copy. Thanks to @${link('https://community.anytype.io/t/30105', 'Chrispy163')}!`),
		]),

		toggle(`<b>UI & Rendering (18)</b>`, [
			bullet(`The app no longer turns white after extended inactivity.`),
			bullet(`Checkbox properties no longer shrink when placed as the first column with a reduced width.`),
			bullet(`An invisible button on the interface has been removed.`),
			bullet(`Tooltip text for layout settings is no longer cut off.`),
			bullet(`The Edit Type screen no longer breaks when the window is small.`),
			bullet(`The editor layout no longer breaks after toggling the sidebar via keyboard shortcut.`),
			bullet(`The Properties menu in Settings has been fixed.`),
			bullet(`The PIN entry screen after inactivity is now visible without resizing the window. Thanks to @${link('https://community.anytype.io/t/30259', 'mdmdj')}!`),
			bullet(`Sidebar state and tabs are now preserved correctly when installing updates.`),
			bullet(`Title Fullscreen mode no longer hides the menu bar on Linux.`),
			bullet(`Scrolling in Remote Storage now works when hovering over objects.`),
			bullet(`The filter list popup no longer renders too small.`),
			bullet(`Search pane animation is no longer choppy. Thanks to @${link('https://community.anytype.io/t/30092', 'dpr')}!`),
			bullet(`The Object Type header font size is no longer oversized on Mac. Thanks to @${link('https://community.anytype.io/t/30085', 'henrywu')}!`),
			bullet(`The "Object Type: Name" selection box now closes after clicking an option. Thanks to @${link('https://community.anytype.io/t/30148', 'Hexara')}!`),
			bullet(`Odd behavior when typing an account name has been fixed. Thanks to @${link('https://community.anytype.io/t/28866', 'Regis')}!`),
			bullet(`A crash on new MacBook M5 models at app startup has been fixed. Thanks to @${link('https://community.anytype.io/t/30394', 'kic')}!`),
			bullet(`Profile images uploaded on iOS now display correctly on Desktop.`),
		]),

		toggle(`<b>Navigation & Tabs (18)</b>`, [
			bullet(`The app no longer unexpectedly redirects to the auth screen.`),
			bullet(`Logging in with two vaults on the same device no longer briefly shows the previous vault.`),
			bullet(`Duplicated tabs now load correctly.`),
			bullet(`Closing a tab now opens the correct neighboring tab.`),
			bullet(`The sidebar no longer closes unexpectedly in a new tab with "Automatically hide sidebar" enabled.`),
			bullet(`Opening another Channel from a pinned tab now opens the correct Channel.`),
			bullet(`The interface no longer disappears after re-opening the application.`),
			bullet(`White screen after importing data has been fixed. Thanks to @${link('https://community.anytype.io/t/30074', 'Shampra')}!`),
			bullet(`Creating an account in different windows no longer causes issues.`),
			bullet(`The window can now be dragged and maximized when the menu bar is turned off.`),
			bullet(`The right-click context menu in the Bin now opens at the correct position.`),
			bullet(`The "Transfer ownership" option no longer appears incorrectly in the Vault.`),
			bullet(`The Property Panel is no longer visible in the Bin.`),
			bullet(`The description and shortcut for Pin/Unpin Tab have been corrected.`),
			bullet(`Pinning a tab that's already open no longer creates a duplicate – the existing tab is pinned instead.`),
			bullet(`Returning to the members list no longer shows a blank screen.`),
			bullet(`The closed sidebar no longer reopens unexpectedly. Thanks to @${link('https://community.anytype.io/t/30089', 'C.c')}!`),
			bullet(`The "Automatically hide sidebar" setting now applies immediately to all open tabs, not just the active one.`),
		]),

		toggle(`<b>Keyboard & Shortcuts (6)</b>`, [
			bullet(`${hl(`${cmd}+/`)} now correctly triggers the "View Shortcuts" panel.`),
			bullet(`Typing to filter block actions now auto-selects the first matching option. Thanks to @${link('https://community.anytype.io/t/30224', 'nathan.connor')}!`),
			bullet(`CSS formatting now correctly follows the selection in preferences. Thanks to @${link('https://community.anytype.io/t/30250', 'Shampra')}!`),
			bullet(`"Jump to Previous/Next Block" hotkeys now work on Windows. Thanks to @${link('https://community.anytype.io/t/30128', 'trialsin')}!`),
			bullet(`Keyboard shortcut for selecting text right-to-left has been fixed.`),
			bullet(`The ${hl('@')} mention search now works correctly after switching to a non-Latin keyboard layout.`),
		]),

		toggle(`<b>Notifications & Counters (5)</b>`, [
			bullet(`Muted and hidden Chats are no longer counted in the Channel unread badge in the Vault.`),
			bullet(`The unread message counter now correctly appears instead of the pinned icon for pinned Channels.`),
			bullet(`The Pin and Counter icons no longer overlap when "Mention Only" is enabled.`),
			bullet(`Muted and "Mention Only" counters are no longer hidden from the Vault sidebar.`),
			bullet(`Notification badges now display consistently in both collapsed and expanded sidebar states.`),
		]),
	];
};
