name: "CLA Check"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
  
jobs:
  cla-check:
    uses: anyproto/open/.github/workflows/cla.yml@main
    secrets: inherit
